package got.common.entity;

import got.common.entity.animal.*;
import got.common.entity.dragon.GOTEntityDragon;
import got.common.entity.essos.GOTEntityIfekevron;
import got.common.entity.essos.GOTEntityRedPriest;
import got.common.entity.essos.GOTEntityShryke;
import got.common.entity.essos.GOTEntityStoneMan;
import got.common.entity.essos.asshai.*;
import got.common.entity.essos.braavos.*;
import got.common.entity.essos.dothraki.GOTEntityDothraki;
import got.common.entity.essos.dothraki.GOTEntityDothrakiArcher;
import got.common.entity.essos.dothraki.GOTEntityDothrakiKhal;
import got.common.entity.essos.dothraki.GOTEntityDothrakiKhalin;
import got.common.entity.essos.ghiscar.*;
import got.common.entity.essos.gold.GOTEntityGoldenBannerBearer;
import got.common.entity.essos.gold.GOTEntityGoldenCaptain;
import got.common.entity.essos.gold.GOTEntityGoldenSpearman;
import got.common.entity.essos.gold.GOTEntityGoldenWarrior;
import got.common.entity.essos.ibben.*;
import got.common.entity.essos.jogos.*;
import got.common.entity.essos.legendary.GOTEntityMissandei;
import got.common.entity.essos.legendary.captain.*;
import got.common.entity.essos.legendary.quest.GOTEntityBuGai;
import got.common.entity.essos.legendary.quest.GOTEntityDaenerysTargaryen;
import got.common.entity.essos.legendary.quest.GOTEntityJaqenHghar;
import got.common.entity.essos.legendary.quest.GOTEntityMellario;
import got.common.entity.essos.legendary.trader.GOTEntityIllyrioMopatis;
import got.common.entity.essos.legendary.trader.GOTEntityMoqorro;
import got.common.entity.essos.legendary.trader.GOTEntityTychoNestoris;
import got.common.entity.essos.legendary.trader.GOTEntityXaroXhoanDaxos;
import got.common.entity.essos.legendary.warrior.*;
import got.common.entity.essos.lhazar.*;
import got.common.entity.essos.lorath.*;
import got.common.entity.essos.lys.*;
import got.common.entity.essos.mossovy.*;
import got.common.entity.essos.myr.*;
import got.common.entity.essos.norvos.*;
import got.common.entity.essos.pentos.*;
import got.common.entity.essos.qarth.*;
import got.common.entity.essos.qohor.*;
import got.common.entity.essos.tyrosh.*;
import got.common.entity.essos.volantis.*;
import got.common.entity.essos.yiti.*;
import got.common.entity.other.*;
import got.common.entity.sothoryos.sothoryos.*;
import got.common.entity.sothoryos.summer.*;
import got.common.entity.westeros.GOTEntityMaester;
import got.common.entity.westeros.GOTEntityMercenary;
import got.common.entity.westeros.GOTEntitySepton;
import got.common.entity.westeros.arryn.*;
import got.common.entity.westeros.crownlands.*;
import got.common.entity.westeros.dorne.*;
import got.common.entity.westeros.dragonstone.*;
import got.common.entity.westeros.gift.GOTEntityGiftBannerBearer;
import got.common.entity.westeros.gift.GOTEntityGiftBlacksmith;
import got.common.entity.westeros.gift.GOTEntityGiftGuard;
import got.common.entity.westeros.gift.GOTEntityGiftMan;
import got.common.entity.westeros.hillmen.*;
import got.common.entity.westeros.ice.GOTEntityIceSpider;
import got.common.entity.westeros.ice.GOTEntityWhiteWalker;
import got.common.entity.westeros.ice.GOTEntityWight;
import got.common.entity.westeros.ice.GOTEntityWightGiant;
import got.common.entity.westeros.ironborn.*;
import got.common.entity.westeros.legendary.GOTEntityCrasterWife;
import got.common.entity.westeros.legendary.captain.*;
import got.common.entity.westeros.legendary.deco.*;
import got.common.entity.westeros.legendary.quest.*;
import got.common.entity.westeros.legendary.reborn.*;
import got.common.entity.westeros.legendary.trader.*;
import got.common.entity.westeros.legendary.warrior.*;
import got.common.entity.westeros.north.*;
import got.common.entity.westeros.north.hillmen.*;
import got.common.entity.westeros.reach.*;
import got.common.entity.westeros.riverlands.*;
import got.common.entity.westeros.stormlands.*;
import got.common.entity.westeros.westerlands.*;
import got.common.entity.westeros.wildling.*;
import got.common.entity.westeros.wildling.thenn.*;
import got.common.faction.GOTFaction;

public class GOTEntity {
	private GOTEntity() {
	}

	@SuppressWarnings({"UnusedAssignment", "ValueOfIncrementOrDecrementUsed"})
	public static void preInit() {
		int id = 0;
		GOTEntityRegistry.register(GOTEntityBison.class, id++, 7488812);
		GOTEntityRegistry.register(GOTEntityBear.class, id++, 7492416);
		GOTEntityRegistry.register(GOTEntityBird.class, id++, 7451872);
		GOTEntityRegistry.register(GOTEntityBeaver.class, id++, 7492416);
		GOTEntityRegistry.register(GOTEntityButterfly.class, id++, 16119285);
		GOTEntityRegistry.register(GOTEntityCamel.class, id++, 13150061);
		GOTEntityRegistry.register(GOTEntityCrocodile.class, id++, 2896659);
		GOTEntityRegistry.register(GOTEntityDeer.class, id++, 5978669);
		GOTEntityRegistry.register(GOTEntityDesertScorpion.class, id++, 16376764);
		GOTEntityRegistry.register(GOTEntityDikDik.class, id++, 12023867);
		GOTEntityRegistry.register(GOTEntityDirewolf.class, id++, 0x808080);
		GOTEntityRegistry.register(GOTEntityDragon.class, id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityElephant.class, id++, 9605778);
		GOTEntityRegistry.register(GOTEntityFish.class, id++, 7053203);
		GOTEntityRegistry.register(GOTEntityFlamingo.class, id++, 16087966);
		GOTEntityRegistry.register(GOTEntityGemsbok.class, id++, 11759423);
		GOTEntityRegistry.register(GOTEntityGiraffe.class, id++, 13608551);
		GOTEntityRegistry.register(GOTEntityGorcrow.class, id++, 928034);
		GOTEntityRegistry.register(GOTEntityHorse.class, id++, 8601889);
		GOTEntityRegistry.register(GOTEntityJungleScorpion.class, id++, 2630945);
		GOTEntityRegistry.register(GOTEntityWhiteBison.class, id++, 16702665);
		GOTEntityRegistry.register(GOTEntityLion.class, id++, 13345354);
		GOTEntityRegistry.register(GOTEntityLioness.class, id++, 13346908);
		GOTEntityRegistry.register(GOTEntityMammoth.class, id++, 5653040);
		GOTEntityRegistry.register(GOTEntityManticore.class, id++, 0x2B3F19);
		GOTEntityRegistry.register(GOTEntityMidges.class, id++, 5653040);
		GOTEntityRegistry.register(GOTEntityMossovyWerewolf.class, id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityRabbit.class, id++, 9860178);
		GOTEntityRegistry.register(GOTEntityRedScorpion.class, id++, 0x7c0a02);
		GOTEntityRegistry.register(GOTEntityRhino.class, id++, 6118481);
		GOTEntityRegistry.register(GOTEntitySeagull.class, id++, 15920107);
		GOTEntityRegistry.register(GOTEntityShadowcat.class, id++, 0x282728);
		GOTEntityRegistry.register(GOTEntitySnowBear.class, id++, 15594495);
		GOTEntityRegistry.register(GOTEntitySwan.class, id++, 16119285);
		GOTEntityRegistry.register(GOTEntityTermite.class, id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityWalrus.class, id++, 7053203);
		GOTEntityRegistry.register(GOTEntityWhiteOryx.class, id++, 16381146);
		GOTEntityRegistry.register(GOTEntityBoar.class, id++, 6635562);
		GOTEntityRegistry.register(GOTEntityWoolyRhino.class, id++, 5653040);
		GOTEntityRegistry.register(GOTEntityWyvern.class, id++, 2896659);
		GOTEntityRegistry.register(GOTEntityZebra.class, id++, 15000804);
		GOTEntityRegistry.register(GOTEntityShryke.class, id++, 2896659);

		GOTEntityRegistry.register(GOTEntityLightSkinBandit.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityLightSkinThief.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityLightSkinScrapTrader.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityDarkSkinBandit.class, id++, 13345354);
		GOTEntityRegistry.register(GOTEntityDarkSkinThief.class, id++, 13345354);
		GOTEntityRegistry.register(GOTEntityDarkSkinScrapTrader.class, id++, 13345354);

		GOTEntityRegistry.register(GOTEntityProstitute.class, id++, 16087966);
		GOTEntityRegistry.register(GOTEntityMaester.class, id++, 0xffffff);
		GOTEntityRegistry.register(GOTEntitySepton.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityRedPriest.class, id++, 0x7c0a02);
		GOTEntityRegistry.register(GOTEntityIronbornPriest.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityBarrowWight.class, id++, 2896659);
		GOTEntityRegistry.register(GOTEntityMarshWraith.class, id++, 10524036);
		GOTEntityRegistry.register(GOTEntityStoneMan.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityMercenary.class, id++, 0xBABABA);

		GOTEntityRegistry.register(GOTEntityWhiteWalker.class, id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityWight.class, id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityIceSpider.class, id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityWightGiant.class, id++, GOTFaction.WHITE_WALKER);

		GOTEntityRegistry.register(GOTEntityWildling.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingArcher.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingAxeThrower.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingBannerBearer.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingChieftain.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityGiant.class, id++, GOTFaction.WILDLING);

		GOTEntityRegistry.register(GOTEntityThenn.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennArcher.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennAxeThrower.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBannerBearer.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBerserker.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennMagnar.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBlacksmith.class, id++, GOTFaction.WILDLING);

		GOTEntityRegistry.registerHidden(GOTEntityCrasterWife.class, id++);

		GOTEntityRegistry.register(GOTEntityGiftMan.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftBlacksmith.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftGuard.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftBannerBearer.class, id++, GOTFaction.NIGHT_WATCH);

		GOTEntityRegistry.register(GOTEntityNorthMan.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLevyman.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLevymanArcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthSoldier.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthSoldierArcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthGuard.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBannerBearer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthCaptain.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBlacksmith.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthGoldsmith.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFarmer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFarmhand.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBartender.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthMiner.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLumberman.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthMason.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBrewer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFlorist.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthButcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFishmonger.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBaker.class, id++, GOTFaction.NORTH);

		GOTEntityRegistry.register(GOTEntityNorthHillman.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanWarrior.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanCannibal.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanMercenary.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanArcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanAxeThrower.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanBannerBearer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanChieftain.class, id++, GOTFaction.NORTH);

		GOTEntityRegistry.register(GOTEntityIronbornMan.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLevyman.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLevymanArcher.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornSoldier.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornSoldierArcher.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBannerBearer.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornCaptain.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBaker.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBartender.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornGoldsmith.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBlacksmith.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBrewer.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornButcher.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFarmer.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFarmhand.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFishmonger.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFlorist.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornMiner.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLumberman.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornMason.class, id++, GOTFaction.IRONBORN);

		GOTEntityRegistry.register(GOTEntityWesterlandsMan.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLevyman.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLevymanArcher.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsSoldier.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsSoldierArcher.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsGuard.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBannerBearer.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsCaptain.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBaker.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBartender.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBlacksmith.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsGoldsmith.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBrewer.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsButcher.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFarmer.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFarmhand.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFishmonger.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFlorist.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsMiner.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLumberman.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsMason.class, id++, GOTFaction.WESTERLANDS);

		GOTEntityRegistry.register(GOTEntityRiverlandsMan.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLevyman.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLevymanArcher.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsSoldier.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsSoldierArcher.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBannerBearer.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsCaptain.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBaker.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBartender.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBlacksmith.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsGoldsmith.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBrewer.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsButcher.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFarmer.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFarmhand.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFishmonger.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFlorist.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsMiner.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLumberman.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsMason.class, id++, GOTFaction.RIVERLANDS);

		GOTEntityRegistry.register(GOTEntityHillman.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanWarrior.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanArcher.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanAxeThrower.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBerserker.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBannerBearer.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanWarlord.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBartender.class, id++, GOTFaction.HILL_TRIBES);

		GOTEntityRegistry.register(GOTEntityArrynMan.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLevyman.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLevymanArcher.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynSoldier.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynSoldierArcher.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynGuard.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBannerBearer.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynCaptain.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBaker.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBartender.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBlacksmith.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynGoldsmith.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBrewer.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynButcher.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFarmer.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFarmhand.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFishmonger.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFlorist.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynMiner.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLumberman.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynMason.class, id++, GOTFaction.ARRYN);

		GOTEntityRegistry.register(GOTEntityDragonstoneMan.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLevyman.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLevymanArcher.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneSoldier.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneSoldierArcher.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBannerBearer.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneCaptain.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBaker.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBartender.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBlacksmith.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneGoldsmith.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBrewer.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneButcher.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFarmer.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFarmhand.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFishmonger.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFlorist.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneMiner.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLumberman.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneMason.class, id++, GOTFaction.DRAGONSTONE);

		GOTEntityRegistry.register(GOTEntityCrownlandsMan.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLevyman.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLevymanArcher.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsGuard.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBannerBearer.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityKingsguard.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsCaptain.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBaker.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBartender.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBlacksmith.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsGoldsmith.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBrewer.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsButcher.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFarmer.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFarmhand.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFishmonger.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFlorist.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsMiner.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLumberman.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsMason.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsAlchemist.class, id++, GOTFaction.CROWNLANDS);

		GOTEntityRegistry.register(GOTEntityStormlandsMan.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLevyman.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLevymanArcher.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsSoldier.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsSoldierArcher.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBannerBearer.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsCaptain.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBaker.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBartender.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBlacksmith.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsGoldsmith.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBrewer.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsButcher.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFarmer.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFarmhand.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFishmonger.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFlorist.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsMiner.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLumberman.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsMason.class, id++, GOTFaction.STORMLANDS);

		GOTEntityRegistry.register(GOTEntityReachMan.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLevyman.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLevymanArcher.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachSoldier.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachSoldierArcher.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachGuard.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBannerBearer.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachCaptain.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBaker.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBartender.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBlacksmith.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachGoldsmith.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBrewer.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachButcher.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFarmer.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFarmhand.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFishmonger.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFlorist.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachMiner.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLumberman.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachMason.class, id++, GOTFaction.REACH);

		GOTEntityRegistry.register(GOTEntityDorneMan.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLevyman.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLevymanArcher.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneSoldier.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneSoldierArcher.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBannerBearer.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneCaptain.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBaker.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBartender.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBlacksmith.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneGoldsmith.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBrewer.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneButcher.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFarmer.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFarmhand.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFishmonger.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFlorist.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneMiner.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLumberman.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneMason.class, id++, GOTFaction.DORNE);

		GOTEntityRegistry.register(GOTEntityBraavosMan.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosLevyman.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosLevymanArcher.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosSoldier.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosSoldierArcher.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBannerBearer.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosGeneral.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBaker.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBartender.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBlacksmith.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBrewer.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosButcher.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosFarmer.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosFarmhand.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosFishmonger.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosFlorist.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosGoldsmith.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosLumberman.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosMason.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosMiner.class, id++, GOTFaction.BRAAVOS);

		GOTEntityRegistry.register(GOTEntityVolantisMan.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisLevyman.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisLevymanArcher.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSoldier.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSoldierArcher.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBannerBearer.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisGeneral.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSlave.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSlaver.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBaker.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBartender.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBlacksmith.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBrewer.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisButcher.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisFishmonger.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisFlorist.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisGoldsmith.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisLumberman.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisMason.class, id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisMiner.class, id++, GOTFaction.VOLANTIS);

		GOTEntityRegistry.register(GOTEntityPentosMan.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosLevyman.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosLevymanArcher.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosGuard.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBannerBearer.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosGuardCaptain.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBaker.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBartender.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBlacksmith.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBrewer.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosButcher.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosFarmer.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosFarmhand.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosFishmonger.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosFlorist.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosGoldsmith.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosLumberman.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosMason.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosMiner.class, id++, GOTFaction.PENTOS);

		GOTEntityRegistry.register(GOTEntityNorvosMan.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosLevyman.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosLevymanArcher.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosGuard.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBannerBearer.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosGuardCaptain.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBaker.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBartender.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBlacksmith.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBrewer.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosButcher.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosFarmer.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosFarmhand.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosFishmonger.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosFlorist.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosGoldsmith.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosLumberman.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosMason.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosMiner.class, id++, GOTFaction.NORVOS);

		GOTEntityRegistry.register(GOTEntityLorathMan.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathLevyman.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathLevymanArcher.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathSoldier.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathSoldierArcher.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBannerBearer.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathGeneral.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBaker.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBartender.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBlacksmith.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBrewer.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathButcher.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathFarmer.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathFarmhand.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathFishmonger.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathFlorist.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathGoldsmith.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathLumberman.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathMason.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathMiner.class, id++, GOTFaction.LORATH);

		GOTEntityRegistry.register(GOTEntityQohorMan.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorLevyman.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorLevymanArcher.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorGuard.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorUnsullied.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBannerBearer.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorGuardCaptain.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBaker.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBartender.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBlacksmith.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBrewer.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorButcher.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorFarmer.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorFarmhand.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorFishmonger.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorFlorist.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorGoldsmith.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorLumberman.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorMason.class, id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorMiner.class, id++, GOTFaction.QOHOR);

		GOTEntityRegistry.register(GOTEntityLysMan.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysLevyman.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysLevymanArcher.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSoldier.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSoldierArcher.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBannerBearer.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysGeneral.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSlave.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSlaver.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBaker.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBartender.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBlacksmith.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBrewer.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysButcher.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysFishmonger.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysFlorist.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysGoldsmith.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysLumberman.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysMason.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysMiner.class, id++, GOTFaction.LYS);

		GOTEntityRegistry.register(GOTEntityMyrMan.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrLevyman.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrLevymanArcher.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSoldier.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSoldierArcher.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBannerBearer.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrGeneral.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSlave.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSlaver.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBaker.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBartender.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBlacksmith.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBrewer.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrButcher.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrFishmonger.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrFlorist.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrGoldsmith.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrLumberman.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrMason.class, id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrMiner.class, id++, GOTFaction.MYR);

		GOTEntityRegistry.register(GOTEntityGoldenWarrior.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenSpearman.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenBannerBearer.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenCaptain.class, id++, 0xffd700);

		GOTEntityRegistry.register(GOTEntityTyroshMan.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshLevyman.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshLevymanArcher.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSoldier.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSoldierArcher.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBannerBearer.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshGeneral.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSlave.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSlaver.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBaker.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBartender.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBlacksmith.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBrewer.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshButcher.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshFishmonger.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshFlorist.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshGoldsmith.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshLumberman.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshMason.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshMiner.class, id++, GOTFaction.TYROSH);

		GOTEntityRegistry.register(GOTEntityGhiscarMan.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarLevyman.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarLevymanArcher.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarUnsullied.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarCorsair.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarCorsairArcher.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarGuard.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarGladiator.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarHarpy.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBannerBearer.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarSlave.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarSlaver.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarAdmiral.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBaker.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBartender.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBlacksmith.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBrewer.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarButcher.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarFishmonger.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarFlorist.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarGoldsmith.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarLumberman.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarMason.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarMiner.class, id++, GOTFaction.GHISCAR);

		GOTEntityRegistry.register(GOTEntityQarthMan.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthLevyman.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthLevymanArcher.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthGuard.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBannerBearer.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthWarlock.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthGuardCaptain.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBaker.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBartender.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBlacksmith.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBrewer.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthButcher.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthFarmer.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthFarmhand.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthFishmonger.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthFlorist.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthGoldsmith.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthLumberman.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthMason.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthMiner.class, id++, GOTFaction.QARTH);

		GOTEntityRegistry.register(GOTEntityLhazarMan.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarWarrior.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarArcher.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBannerBearer.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarWarlord.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBlacksmith.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarMason.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarButcher.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBrewer.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarFishmonger.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBaker.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarMiner.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarGoldsmith.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarLumberman.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBartender.class, id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarFarmer.class, id++, GOTFaction.LHAZAR);

		GOTEntityRegistry.register(GOTEntityDothraki.class, id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.register(GOTEntityDothrakiArcher.class, id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.register(GOTEntityDothrakiKhal.class, id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.register(GOTEntityDothrakiKhalin.class, id++, GOTFaction.DOTHRAKI);

		GOTEntityRegistry.register(GOTEntityIbbenMan.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenWarrior.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenArcher.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenAxeThrower.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenWarlord.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBlacksmith.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBartender.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBannerBearer.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenFarmhand.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenFarmer.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenLumberman.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenMason.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBrewer.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenButcher.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenFishmonger.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBaker.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenFlorist.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenMiner.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenGoldsmith.class, id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIfekevron.class, id++, GOTFaction.IBBEN);

		GOTEntityRegistry.register(GOTEntityJogos.class, id++, GOTFaction.JOGOS);
		GOTEntityRegistry.register(GOTEntityJogosArcher.class, id++, GOTFaction.JOGOS);
		GOTEntityRegistry.register(GOTEntityJogosBannerBearer.class, id++, GOTFaction.JOGOS);
		GOTEntityRegistry.register(GOTEntityJogosChief.class, id++, GOTFaction.JOGOS);
		GOTEntityRegistry.register(GOTEntityJogosShaman.class, id++, GOTFaction.JOGOS);

		GOTEntityRegistry.register(GOTEntityMossovyMan.class, id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyWitcher.class, id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyBlacksmith.class, id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyFarmer.class, id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyBartender.class, id++, GOTFaction.MOSSOVY);

		GOTEntityRegistry.register(GOTEntityYiTiMan.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiLevyman.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiLevymanCrossbower.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiSoldier.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiSoldierCrossbower.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFrontier.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFrontierCrossbower.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiSamurai.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBombardier.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBannerBearer.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFireThrower.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiShogune.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFarmhand.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBlacksmith.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiLumberman.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiMason.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiButcher.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBrewer.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFishmonger.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBaker.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiMiner.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFlorist.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFarmer.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiGoldsmith.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBartender.class, id++, GOTFaction.YI_TI);

		GOTEntityRegistry.register(GOTEntityAsshaiMan.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiWarrior.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiBannerBearer.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiShadowbinder.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiSpherebinder.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiAlchemist.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiCaptain.class, id++, GOTFaction.ASSHAI);

		GOTEntityRegistry.register(GOTEntitySothoryosMan.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosWarrior.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosBannerBearer.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosChieftain.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosBlowgunner.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosShaman.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosFarmer.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosFarmhand.class, id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosSmith.class, id++, GOTFaction.SOTHORYOS);

		GOTEntityRegistry.register(GOTEntitySummerMan.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerWarrior.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerArcher.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBannerBearer.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerWarlord.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBlacksmith.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBartender.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerLumberman.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerMason.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerButcher.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBrewer.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerFishmonger.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBaker.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerMiner.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerFarmhand.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerFarmer.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerFlorist.class, id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerGoldsmith.class, id++, GOTFaction.SUMMER_ISLANDS);

		GOTEntityRegistry.register(GOTEntityUlthosSpider.class, id++, GOTFaction.ULTHOS);
		GOTEntityRegistry.register(GOTEntityBlizzard.class, id++, GOTFaction.WHITE_WALKER);

		GOTEntityRegistry.registerLegendaryNPC(GOTEntityNightKing.class, id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityCraster.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityManceRayder.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTormund.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityYgritte.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAemonTargaryen.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAlliserThorne.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBenjenStark.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityCotterPyke.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDenysMallister.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityEdd.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHarmune.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJeorMormont.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJonSnow.JonSnowLife1.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMullin.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySamwellTarly.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityYoren.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAryaStark.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBarbreyDustin.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBranStark.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityCatelynStark.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityCleyCerwyn.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHelmanTallhart.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHodor.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHowlandReed.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJohnUmber.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLuwin.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMaegeMormont.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityOsha.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRamsayBolton.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRickardKarstark.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRickonStark.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRobbStark.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRodrikCassel.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRodrikRyswell.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRooseBolton.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityWymanManderly.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAeronGreyjoy.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAndrikTheUnsmilling.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBaelorBlacktyde.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBalonGreyjoy.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDagmer.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDunstanDrumm.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityErikIronmaker.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityEuronGreyjoy.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGoroldGoodbrother.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGylbertFarwynd.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHarrasHarlaw.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMaronVolmark.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRodrikHarlaw.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTheonGreyjoy.TheonGreyjoyNormal.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityVictarionGreyjoy.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityYaraGreyjoy.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAddamMarbrand.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAmoryLorch.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDavenLannister.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityForleyPrester.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGregorClegane.GregorCleganeAlive.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHarysSwyft.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJaimeLannister.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityKevanLannister.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLeoLefford.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLyleCrakehall.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityPolliver.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityQuentenBanefort.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityQyburn.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySebastonFarman.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTyrionLannister.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTytosBrax.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTywinLannister.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBericDondarrion.BericDondarrionLife1.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBlackWalderFrey.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBryndenTully.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityClementPiper.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityEdmureTully.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHosterTully.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHotPie.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJasonMallister.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJonosBracken.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLotharFrey.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityThoros.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTytosBlackwood.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityWalderFrey.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityWilliamMooton.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAnyaWaynwood.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBenedarBelmore.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGeroldGrafton.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGilwoodHunter.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHarroldHardyng.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHortonRedfort.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLynCorbray.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLysaArryn.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRobinArryn.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySymondTempleton.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityYohnRoyce.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityArdrianCeltigar.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAuraneWaters.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDavosSeaworth.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMatthosSeaworth.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMelisandra.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMonfordVelaryon.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySelyseBaratheon.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityShireenBaratheon.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityStannisBaratheon.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBarristanSelmy.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityCerseiLannister.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityEbrose.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGendryBaratheon.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHighSepton.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityIlynPayne.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJanosSlynt.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJoffreyBaratheon.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLancelLannister.LancelLannisterNormal.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMerynTrant.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMyrcellaBaratheon.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityPetyrBaelish.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityPodrickPayne.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityPycelle.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySandorClegane.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySansaStark.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityShae.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTobhoMott.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTommenBaratheon.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityVarys.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBrienneTarth.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityEldonEstermont.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGulianSwann.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRenlyBaratheon.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySelwynTarth.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGarlanTyrell.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLeytonHightower.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityLorasTyrell.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMaceTyrell.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMargaeryTyrell.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMathisRowan.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMoribaldChester.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityOlennaTyrell.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityOrtonMerryweather.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityPaxterRedwyne.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityQuennRoxton.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRandyllTarly.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityWillasTyrell.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAndersYronwood.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAreoHotah.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityArianneMartell.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBericDayne.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDoranMartell.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityEllaryaSand.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityFranklynFowler.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGeroldDayne.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHarmenUller.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityManfreyMartell.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityOberynMartell.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityQuentynMartell.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityQuentynQorgyle.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTrystaneMartell.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTychoNestoris.class, id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityIllyrioMopatis.class, id++, GOTFaction.PENTOS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMellario.class, id++, GOTFaction.NORVOS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJaqenHghar.class, id++, GOTFaction.LORATH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntitySalladhorSaan.class, id++, GOTFaction.LYS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJonConnington.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityYoungGriff.class, id++, GOTFaction.TYROSH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHizdahrZoLoraq.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityKraznysMoNakloz.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMissandei.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityRazdalMoEraz.class, id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityXaroXhoanDaxos.class, id++, GOTFaction.QARTH);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDaenerysTargaryen.class, id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJorahMormont.class, id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityTugarKhan.class, id++, GOTFaction.JOGOS);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBuGai.class, id++, GOTFaction.YI_TI);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityAsshaiArchmag.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityMoqorro.class, id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityBronn.class, id++, GOTFaction.UNALIGNED);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityDaarioNaharis.class, id++, GOTFaction.UNALIGNED);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityGreyWorm.class, id++, GOTFaction.UNALIGNED);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityHarryStrickland.class, id++, GOTFaction.UNALIGNED);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityThreeEyedRaven.class, id++, GOTFaction.UNALIGNED);
		GOTEntityRegistry.registerLegendaryNPC(GOTEntityVargoHoat.class, id++, GOTFaction.UNALIGNED);
		GOTEntityRegistry.registerHidden(GOTEntityBericDondarrion.BericDondarrionLife2.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityBericDondarrion.BericDondarrionLife3.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityBericDondarrion.BericDondarrionLife4.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityBericDondarrion.BericDondarrionLife5.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityBericDondarrion.BericDondarrionLife6.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityGregorClegane.GregorCleganeDead.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityJonSnow.JonSnowLife2.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityLancelLannister.LancelLannisterReligious.class, id++);
		GOTEntityRegistry.registerHidden(GOTEntityTheonGreyjoy.TheonGreyjoyTormented.class, id++);

		GOTEntityRegistry.registerHidden(GOTEntityPortal.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntitySmokeRing.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityBomb.class, id++, 160, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntitySpear.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityPlate.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityThrowingAxe.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityCrossbowBolt.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityPebble.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityMysteryWeb.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityTraderRespawn.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityThrownRock.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityBarrel.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityInvasionSpawner.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityThrownTermite.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityConker.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityFishHook.class, id++, 64, 5, true);
		GOTEntityRegistry.registerHidden(GOTEntityDart.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityNPCRespawner.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityFallingTreasure.class, id++, 160, 20, true);
		GOTEntityRegistry.registerHidden(GOTEntityFallingFireJar.class, id++, 160, 20, true);
		GOTEntityRegistry.registerHidden(GOTEntityFirePot.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityArrowPoisoned.class, id++, 64, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityArrowFire.class, id++, 64, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityLionRug.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityBearRug.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityGiraffeRug.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityBanner.class, id++, 160, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityBannerWall.class, id++, 160, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityLingeringPotion.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityLingeringEffect.class, id++, 64, 1, true);
		GOTEntityRegistry.registerHidden(GOTEntityCargocart.class, id++, 80, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityPlowcart.class, id++, 80, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityMarshWraithBall.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntitySnowball.class, id++, 64, 1, true);

		GOTEntityRegistry.registerHidden(GOTEntityHummel009.class, id++);
	}
}