package got.common.entity;

import got.common.entity.animal.*;
import got.common.entity.dragon.GOTEntityDragon;
import got.common.entity.essos.*;
import got.common.entity.essos.asshai.*;
import got.common.entity.essos.braavos.*;
import got.common.entity.essos.dothraki.*;
import got.common.entity.essos.ghiscar.*;
import got.common.entity.essos.gold.*;
import got.common.entity.essos.ibben.*;
import got.common.entity.essos.jogos.*;
import got.common.entity.essos.legendary.GOTEntityMissandei;
import got.common.entity.essos.legendary.captain.*;
import got.common.entity.essos.legendary.quest.*;
import got.common.entity.essos.legendary.trader.*;
import got.common.entity.essos.legendary.warrior.*;
import got.common.entity.essos.lhazar.*;
import got.common.entity.essos.lorath.*;
import got.common.entity.essos.lys.*;
import got.common.entity.essos.mossovy.*;
import got.common.entity.essos.myr.*;
import got.common.entity.essos.norvos.*;
import got.common.entity.essos.pentos.*;
import got.common.entity.essos.qarth.*;
import got.common.entity.essos.qohor.*;
import got.common.entity.essos.tyrosh.*;
import got.common.entity.essos.volantis.*;
import got.common.entity.essos.yiti.*;
import got.common.entity.other.*;
import got.common.entity.sothoryos.sothoryos.*;
import got.common.entity.sothoryos.summer.*;
import got.common.entity.westeros.*;
import got.common.entity.westeros.arryn.*;
import got.common.entity.westeros.crownlands.*;
import got.common.entity.westeros.dorne.*;
import got.common.entity.westeros.dragonstone.*;
import got.common.entity.westeros.gift.*;
import got.common.entity.westeros.hillmen.*;
import got.common.entity.westeros.ice.*;
import got.common.entity.westeros.ironborn.*;
import got.common.entity.westeros.legendary.captain.*;
import got.common.entity.westeros.legendary.deco.*;
import got.common.entity.westeros.legendary.quest.*;
import got.common.entity.westeros.legendary.reborn.*;
import got.common.entity.westeros.legendary.trader.*;
import got.common.entity.westeros.legendary.warrior.*;
import got.common.entity.westeros.north.*;
import got.common.entity.westeros.north.hillmen.*;
import got.common.entity.westeros.reach.*;
import got.common.entity.westeros.riverlands.*;
import got.common.entity.westeros.stormlands.*;
import got.common.entity.westeros.westerlands.*;
import got.common.entity.westeros.wildling.*;
import got.common.entity.westeros.wildling.thenn.*;
import got.common.faction.GOTFaction;

public class GOTEntity {
	public static int id = 0;

	public static void preInit() {
		GOTEntityRegistry.register(GOTEntityBison.class, "Aurochs", id++, 7488812);
		GOTEntityRegistry.register(GOTEntityBear.class, "Bear", id++, 7492416);
		GOTEntityRegistry.register(GOTEntityBird.class, "Bird", id++, 7451872);
		GOTEntityRegistry.register(GOTEntityButterfly.class, "Butterfly", id++, 16119285);
		GOTEntityRegistry.register(GOTEntityCamel.class, "Camel", id++, 13150061);
		GOTEntityRegistry.register(GOTEntityCrocodile.class, "Crocodile", id++, 2896659);
		GOTEntityRegistry.register(GOTEntityDeer.class, "Deer", id++, 5978669);
		GOTEntityRegistry.register(GOTEntityDesertScorpion.class, "DesertScorpion", id++, 16376764);
		GOTEntityRegistry.register(GOTEntityDikDik.class, "DikDik", id++, 12023867);
		GOTEntityRegistry.register(GOTEntityDirewolf.class, "Direwolf", id++, 0x808080);
		GOTEntityRegistry.register(GOTEntityDragon.class, "Dragon", id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityElephant.class, "Elephant", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityFish.class, "Fish", id++, 7053203);
		GOTEntityRegistry.register(GOTEntityFlamingo.class, "Flamingo", id++, 16087966);
		GOTEntityRegistry.register(GOTEntityGemsbok.class, "Gemsbok", id++, 11759423);
		GOTEntityRegistry.register(GOTEntityGiraffe.class, "Giraffe", id++, 13608551);
		GOTEntityRegistry.register(GOTEntityGorcrow.class, "Gorcrow", id++, 928034);
		GOTEntityRegistry.register(GOTEntityHorse.class, "Horse", id++, 8601889);
		GOTEntityRegistry.register(GOTEntityJungleScorpion.class, "JungleScorpion", id++, 2630945);
		GOTEntityRegistry.register(GOTEntityWhiteBison.class, "KineAraw", id++, 16702665);
		GOTEntityRegistry.register(GOTEntityLion.class, "Lion", id++, 13345354);
		GOTEntityRegistry.register(GOTEntityLioness.class, "Lioness", id++, 13346908);
		GOTEntityRegistry.register(GOTEntityMammoth.class, "Mammoth", id++, 5653040);
		GOTEntityRegistry.register(GOTEntityManticore.class, "Manticore", id++, 0x2B3F19);
		GOTEntityRegistry.register(GOTEntityMidges.class, "Midges", id++, 5653040);
		GOTEntityRegistry.register(GOTEntityMossovyWerewolf.class, "MossovyWerewolf", id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityRabbit.class, "Rabbit", id++, 9860178);
		GOTEntityRegistry.register(GOTEntityRedScorpion.class, "RedScorpion", id++, 0x7c0a02);
		GOTEntityRegistry.register(GOTEntityRhino.class, "Rhino", id++, 6118481);
		GOTEntityRegistry.register(GOTEntitySeagull.class, "Seagull", id++, 15920107);
		GOTEntityRegistry.register(GOTEntityShadowcat.class, "Shadowcat", id++, 0x282728);
		GOTEntityRegistry.register(GOTEntitySnowBear.class, "Polarbear", id++, 15594495);
		GOTEntityRegistry.register(GOTEntitySwan.class, "Swan", id++, 16119285);
		GOTEntityRegistry.register(GOTEntityTermite.class, "Termite", id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityWalrus.class, "Walrus", id++, 7053203);
		GOTEntityRegistry.register(GOTEntityWhiteOryx.class, "WhiteOryx", id++, 16381146);
		GOTEntityRegistry.register(GOTEntityWildBoar.class, "Boar", id++, 6635562);
		GOTEntityRegistry.register(GOTEntityWoolyRhino.class, "WoolyRhino", id++, 5653040);
		GOTEntityRegistry.register(GOTEntityWyvern.class, "Wyvern", id++, 2896659);
		GOTEntityRegistry.register(GOTEntityZebra.class, "Zebra", id++, 15000804);

		GOTEntityRegistry.register(GOTEntityWhore.class, "Whore", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityMaester.class, "Maester", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntitySepton.class, "Septon", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityRedPriest.class, "RedPriest", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityIronbornPriest.class, "IronbornPriest", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityBandit.class, "WesterosBandit", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityThief.class, "Thief", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityEssosBandit.class, "EssosBandit", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityBarrowWight.class, "BarrowWight", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityScrapTrader.class, "ScrapTrader", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityStoneman.class, "StoneMan", id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityMercenary.class, "Mercenary", id++, 0xBABABA);

		GOTEntityRegistry.register(GOTEntityWhiteWalker.class, "WhiteWalker", id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityWight.class, "Wicht", id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityIceSpider.class, "IceSpider", id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityWightGiant.class, "WichtGiant", id++, GOTFaction.WHITE_WALKER);

		GOTEntityRegistry.register(GOTEntityWildling.class, "Wildling", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingArcher.class, "WildlingArcher", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingAxeThrower.class, "WildlingAxeThrower", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingBannerBearer.class, "WildlingBannerBearer", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingChieftain.class, "WildlingChieftain", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityGiant.class, "Giant", id++, GOTFaction.WILDLING);

		GOTEntityRegistry.register(GOTEntityThenn.class, "Thenn", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennArcher.class, "ThennArcher", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennAxeThrower.class, "ThennAxeThrower", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBannerBearer.class, "ThennBannerBearer", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBerserker.class, "ThennBerserker", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennMagnar.class, "ThennMagnar", id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBlacksmith.class, "ThennBlacksmith", id++, GOTFaction.WILDLING);

		GOTEntityRegistry.register(GOTEntityCrasterWife.class, "CrasterWife", id++);

		GOTEntityRegistry.register(GOTEntityGiftMan.class, "GiftMan", id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftBlacksmith.class, "GiftBlacksmith", id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftGuard.class, "GiftGuard", id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftBannerBearer.class, "GiftGuardBannerBearer", id++, GOTFaction.NIGHT_WATCH);

		GOTEntityRegistry.register(GOTEntityNorthMan.class, "NorthMan", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLevyman.class, "NorthLevyman", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLevymanArcher.class, "NorthLevymanArcher", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthSoldier.class, "NorthSoldier", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthSoldierArcher.class, "NorthSoldierArcher", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthGuard.class, "NorthGuard", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBannerBearer.class, "NorthBannerBearer", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthCaptain.class, "NorthCaptain", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBlacksmith.class, "NorthBlacksmith", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthGoldsmith.class, "NorthGoldsmith", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFarmer.class, "NorthFarmer", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFarmhand.class, "NorthFarmhand", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBartender.class, "NorthBartender", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthGreengrocer.class, "NorthGreengrocer", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLumberman.class, "NorthLumberman", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthMason.class, "NorthMason", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBrewer.class, "NorthBrewer", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFlorist.class, "NorthFlorist", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthButcher.class, "NorthButcher", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFishmonger.class, "NorthFishmonger", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBaker.class, "NorthBaker", id++, GOTFaction.NORTH);

		GOTEntityRegistry.register(GOTEntityNorthHillman.class, "NorthHillman", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanWarrior.class, "NorthHillmanWarrior", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanCannibal.class, "NorthHillmanCannibal", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanMercenary.class, "NorthHillmanMercenary", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanArcher.class, "NorthHillmanArcher", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanAxeThrower.class, "NorthHillmanAxeThrower", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanBannerBearer.class, "NorthHillmanBannerBearer", id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanChieftain.class, "NorthHillmanChieftain", id++, GOTFaction.NORTH);

		GOTEntityRegistry.register(GOTEntityIronbornMan.class, "IronbornMan", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLevyman.class, "IronbornLevyman", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLevymanArcher.class, "IronbornLevymanArcher", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornSoldier.class, "IronbornSoldier", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornSoldierArcher.class, "IronbornSoldierArcher", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBannerBearer.class, "IronbornBannerBearer", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornCaptain.class, "IronbornCaptain", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBaker.class, "IronbornBaker", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBartender.class, "IronbornBartender", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornGoldsmith.class, "IronbornGoldsmith", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBlacksmith.class, "IronbornBlacksmith", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBrewer.class, "IronbornBrewer", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornButcher.class, "IronbornButcher", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFarmer.class, "IronbornFarmer", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFarmhand.class, "IronbornFarmhand", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFishmonger.class, "IronbornFishmonger", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFlorist.class, "IronbornFlorist", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornGreengrocer.class, "IronbornGreengrocer", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLumberman.class, "IronbornLumberman", id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornMason.class, "IronbornMason", id++, GOTFaction.IRONBORN);

		GOTEntityRegistry.register(GOTEntityWesterlandsMan.class, "WesterlandsMan", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLevyman.class, "WesterlandsLevyman", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLevymanArcher.class, "WesterlandsLevymanArcher", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsSoldier.class, "WesterlandsSoldier", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsSoldierArcher.class, "WesterlandsSoldierArcher", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsGuard.class, "WesterlandsGuard", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBannerBearer.class, "WesterlandsBannerBearer", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsCaptain.class, "WesterlandsCaptain", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBaker.class, "WesterlandsBaker", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBartender.class, "WesterlandsBartender", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBlacksmith.class, "WesterlandsBlacksmith", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsGoldsmith.class, "WesterlandsGoldsmith", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBrewer.class, "WesterlandsBrewer", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsButcher.class, "WesterlandsButcher", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFarmer.class, "WesterlandsFarmer", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFarmhand.class, "WesterlandsFarmhand", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFishmonger.class, "WesterlandsFishmonger", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFlorist.class, "WesterlandsFlorist", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsGreengrocer.class, "WesterlandsGreengrocer", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLumberman.class, "WesterlandsLumberman", id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsMason.class, "WesterlandsMason", id++, GOTFaction.WESTERLANDS);

		GOTEntityRegistry.register(GOTEntityRiverlandsMan.class, "RiverlandsMan", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLevyman.class, "RiverlandsLevyman", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLevymanArcher.class, "RiverlandsLevymanArcher", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsSoldier.class, "RiverlandsSoldier", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsSoldierArcher.class, "RiverlandsSoldierArcher", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBannerBearer.class, "RiverlandsBannerBearer", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsCaptain.class, "RiverlandsCaptain", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBaker.class, "RiverlandsBaker", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBartender.class, "RiverlandsBartender", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBlacksmith.class, "RiverlandsBlacksmith", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsGoldsmith.class, "RiverlandsGoldsmith", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBrewer.class, "RiverlandsBrewer", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsButcher.class, "RiverlandsButcher", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFarmer.class, "RiverlandsFarmer", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFarmhand.class, "RiverlandsFarmhand", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFishmonger.class, "RiverlandsFishmonger", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFlorist.class, "RiverlandsFlorist", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsGreengrocer.class, "RiverlandsGreengrocer", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLumberman.class, "RiverlandsLumberman", id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsMason.class, "RiverlandsMason", id++, GOTFaction.RIVERLANDS);

		GOTEntityRegistry.register(GOTEntityHillman.class, "Hillmen", id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanWarrior.class, "HillmenWarrior", id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanArcher.class, "HillmenArcher", id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanAxeThrower.class, "HillmenAxeThrower", id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBerserker.class, "HillmenBerserker", id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBannerBearer.class, "HillmenBannerBearer", id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanWarlord.class, "HillmenWarlord", id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBartender.class, "HillmenBartender", id++, GOTFaction.HILL_TRIBES);

		GOTEntityRegistry.register(GOTEntityArrynMan.class, "ArrynMan", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLevyman.class, "ArrynLevyman", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLevymanArcher.class, "ArrynLevymanArcher", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynSoldier.class, "ArrynSoldier", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynSoldierArcher.class, "ArrynSoldierArcher", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynGuard.class, "ArrynGuard", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBannerBearer.class, "ArrynBannerBearer", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynCaptain.class, "ArrynCaptain", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBaker.class, "ArrynBaker", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBartender.class, "ArrynBartender", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBlacksmith.class, "ArrynBlacksmith", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynGoldsmith.class, "ArrynGoldsmith", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBrewer.class, "ArrynBrewer", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynButcher.class, "ArrynButcher", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFarmer.class, "ArrynFarmer", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFarmhand.class, "ArrynFarmhand", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFishmonger.class, "ArrynFishmonger", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFlorist.class, "ArrynFlorist", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynGreengrocer.class, "ArrynGreengrocer", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLumberman.class, "ArrynLumberman", id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynMason.class, "ArrynMason", id++, GOTFaction.ARRYN);

		GOTEntityRegistry.register(GOTEntityDragonstoneMan.class, "DragonstoneMan", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLevyman.class, "DragonstoneLevyman", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLevymanArcher.class, "DragonstoneLevymanArcher", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneSoldier.class, "DragonstoneSoldier", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneSoldierArcher.class, "DragonstoneSoldierArcher", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBannerBearer.class, "DragonstoneBannerBearer", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneCaptain.class, "DragonstoneCaptain", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBaker.class, "DragonstoneBaker", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBartender.class, "DragonstoneBartender", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBlacksmith.class, "DragonstoneBlacksmith", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneGoldsmith.class, "DragonstoneGoldsmith", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBrewer.class, "DragonstoneBrewer", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneButcher.class, "DragonstoneButcher", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFarmer.class, "DragonstoneFarmer", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFarmhand.class, "DragonstoneFarmhand", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFishmonger.class, "DragonstoneFishmonger", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFlorist.class, "DragonstoneFlorist", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneGreengrocer.class, "DragonstoneGreengrocer", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLumberman.class, "DragonstoneLumberman", id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneMason.class, "DragonstoneMason", id++, GOTFaction.DRAGONSTONE);

		GOTEntityRegistry.register(GOTEntityCrownlandsMan.class, "CrownlandsMan", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLevyman.class, "CrownlandsLevyman", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLevymanArcher.class, "CrownlandsLevymanArcher", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsGuard.class, "CrownlandsGuard", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBannerBearer.class, "CrownlandsBannerBearer", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityKingsguard.class, "Kingsguard", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsCaptain.class, "CrownlandsCaptain", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBaker.class, "CrownlandsBaker", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBartender.class, "CrownlandsBartender", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBlacksmith.class, "CrownlandsBlacksmith", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsGoldsmith.class, "CrownlandsGoldsmith", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBrewer.class, "CrownlandsBrewer", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsButcher.class, "CrownlandsButcher", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFarmer.class, "CrownlandsFarmer", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFarmhand.class, "CrownlandsFarmhand", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFishmonger.class, "CrownlandsFishmonger", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFlorist.class, "CrownlandsFlorist", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsGreengrocer.class, "CrownlandsGreengrocer", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLumberman.class, "CrownlandsLumberman", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsMason.class, "CrownlandsMason", id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsAlchemist.class, "CrownlandsAlchemist", id++, GOTFaction.CROWNLANDS);

		GOTEntityRegistry.register(GOTEntityStormlandsMan.class, "StormlandsMan", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLevyman.class, "StormlandsLevyman", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLevymanArcher.class, "StormlandsLevymanArcher", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsSoldier.class, "StormlandsSoldier", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsSoldierArcher.class, "StormlandsSoldierArcher", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBannerBearer.class, "StormlandsBannerBearer", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsCaptain.class, "StormlandsCaptain", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBaker.class, "StormlandsBaker", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBartender.class, "StormlandsBartender", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBlacksmith.class, "StormlandsBlacksmith", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsGoldsmith.class, "StormlandsGoldsmith", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBrewer.class, "StormlandsBrewer", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsButcher.class, "StormlandsButcher", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFarmer.class, "StormlandsFarmer", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFarmhand.class, "StormlandsFarmhand", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFishmonger.class, "StormlandsFishmonger", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFlorist.class, "StormlandsFlorist", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsGreengrocer.class, "StormlandsGreengrocer", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLumberman.class, "StormlandsLumberman", id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsMason.class, "StormlandsMason", id++, GOTFaction.STORMLANDS);

		GOTEntityRegistry.register(GOTEntityReachMan.class, "ReachMan", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLevyman.class, "ReachLevyman", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLevymanArcher.class, "ReachLevymanArcher", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachSoldier.class, "ReachSoldier", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachSoldierArcher.class, "ReachSoldierArcher", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachGuard.class, "ReachGuard", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBannerBearer.class, "ReachBannerBearer", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachCaptain.class, "ReachCaptain", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBaker.class, "ReachBaker", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBartender.class, "ReachBartender", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBlacksmith.class, "ReachBlacksmith", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachGoldsmith.class, "ReachGoldsmith", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBrewer.class, "ReachBrewer", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachButcher.class, "ReachButcher", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFarmer.class, "ReachFarmer", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFarmhand.class, "ReachFarmhand", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFishmonger.class, "ReachFishmonger", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFlorist.class, "ReachFlorist", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachGreengrocer.class, "ReachGreengrocer", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLumberman.class, "ReachLumberman", id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachMason.class, "ReachMason", id++, GOTFaction.REACH);

		GOTEntityRegistry.register(GOTEntityDorneMan.class, "DorneMan", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLevyman.class, "DorneLevyman", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLevymanArcher.class, "DorneLevymanArcher", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneSoldier.class, "DorneSoldier", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneSoldierArcher.class, "DorneSoldierArcher", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBannerBearer.class, "DorneBannerBearer", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneCaptain.class, "DorneCaptain", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBaker.class, "DorneBaker", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBartender.class, "DorneBartender", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBlacksmith.class, "DorneBlacksmith", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneGoldsmith.class, "DorneGoldsmith", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBrewer.class, "DorneBrewer", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneButcher.class, "DorneButcher", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFarmer.class, "DorneFarmer", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFarmhand.class, "DorneFarmhand", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFishmonger.class, "DorneFishmonger", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFlorist.class, "DorneFlorist", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneGreengrocer.class, "DorneGreengrocer", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLumberman.class, "DorneLumberman", id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneMason.class, "DorneMason", id++, GOTFaction.DORNE);

		GOTEntityRegistry.register(GOTEntityBraavosMan.class, "BraavosMan", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosLevyman.class, "BraavosLevyman", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosLevymanArcher.class, "BraavosLevymanArcher", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosSoldier.class, "BraavosSoldier", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosSoldierArcher.class, "BraavosSoldierArcher", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBannerBearer.class, "BraavosBannerBearer", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosGeneral.class, "BraavosGeneral", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBaker.class, "BraavosBaker", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBartender.class, "BraavosBartender", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBlacksmith.class, "BraavosBlacksmith", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosBrewer.class, "BraavosBrewer", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosButcher.class, "BraavosButcher", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosFarmer.class, "BraavosFarmer", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosFishmonger.class, "BraavosFishmonger", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosFlorist.class, "BraavosFlorist", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosGoldsmith.class, "BraavosGoldsmith", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosLumberman.class, "BraavosLumberman", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosMason.class, "BraavosMason", id++, GOTFaction.BRAAVOS);
		GOTEntityRegistry.register(GOTEntityBraavosMiner.class, "BraavosMiner", id++, GOTFaction.BRAAVOS);

		GOTEntityRegistry.register(GOTEntityVolantisMan.class, "VolantisMan", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisLevyman.class, "VolantisLevyman", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisLevymanArcher.class, "VolantisLevymanArcher", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSoldier.class, "VolantisSoldier", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSoldierArcher.class, "VolantisSoldierArcher", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBannerBearer.class, "VolantisBannerBearer", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisGeneral.class, "VolantisGeneral", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSlave.class, "VolantisSlave", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisSlaver.class, "VolantisSlaver", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBaker.class, "VolantisBaker", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBartender.class, "VolantisBartender", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBlacksmith.class, "VolantisBlacksmith", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisBrewer.class, "VolantisBrewer", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisButcher.class, "VolantisButcher", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisFishmonger.class, "VolantisFishmonger", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisFlorist.class, "VolantisFlorist", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisGoldsmith.class, "VolantisGoldsmith", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisLumberman.class, "VolantisLumberman", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisMason.class, "VolantisMason", id++, GOTFaction.VOLANTIS);
		GOTEntityRegistry.register(GOTEntityVolantisMiner.class, "VolantisMiner", id++, GOTFaction.VOLANTIS);

		GOTEntityRegistry.register(GOTEntityPentosMan.class, "PentosMan", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosLevyman.class, "PentosLevyman", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosLevymanArcher.class, "PentosLevymanArcher", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosGuard.class, "PentosGuard", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBannerBearer.class, "PentosBannerBearer", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosGuardCaptain.class, "PentosGuardCaptain", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBaker.class, "PentosBaker", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBartender.class, "PentosBartender", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBlacksmith.class, "PentosBlacksmith", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosBrewer.class, "PentosBrewer", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosButcher.class, "PentosButcher", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosFarmer.class, "PentosFarmer", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosFishmonger.class, "PentosFishmonger", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosFlorist.class, "PentosFlorist", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosGoldsmith.class, "PentosGoldsmith", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosLumberman.class, "PentosLumberman", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosMason.class, "PentosMason", id++, GOTFaction.PENTOS);
		GOTEntityRegistry.register(GOTEntityPentosMiner.class, "PentosMiner", id++, GOTFaction.PENTOS);

		GOTEntityRegistry.register(GOTEntityNorvosMan.class, "NorvosMan", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosLevyman.class, "NorvosLevyman", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosLevymanArcher.class, "NorvosLevymanArcher", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosGuard.class, "NorvosGuard", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBannerBearer.class, "NorvosBannerBearer", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosGuardCaptain.class, "NorvosGuardCaptain", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBaker.class, "NorvosBaker", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBartender.class, "NorvosBartender", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBlacksmith.class, "NorvosBlacksmith", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosBrewer.class, "NorvosBrewer", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosButcher.class, "NorvosButcher", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosFarmer.class, "NorvosFarmer", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosFishmonger.class, "NorvosFishmonger", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosFlorist.class, "NorvosFlorist", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosGoldsmith.class, "NorvosGoldsmith", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosLumberman.class, "NorvosLumberman", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosMason.class, "NorvosMason", id++, GOTFaction.NORVOS);
		GOTEntityRegistry.register(GOTEntityNorvosMiner.class, "NorvosMiner", id++, GOTFaction.NORVOS);

		GOTEntityRegistry.register(GOTEntityLorathMan.class, "LorathMan", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathLevyman.class, "LorathLevyman", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathLevymanArcher.class, "LorathLevymanArcher", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathSoldier.class, "LorathSoldier", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathSoldierArcher.class, "LorathSoldierArcher", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBannerBearer.class, "LorathBannerBearer", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathGeneral.class, "LorathGeneral", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBaker.class, "LorathBaker", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBartender.class, "LorathBartender", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBlacksmith.class, "LorathBlacksmith", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathBrewer.class, "LorathBrewer", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathButcher.class, "LorathButcher", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathFarmer.class, "LorathFarmer", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathFishmonger.class, "LorathFishmonger", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathFlorist.class, "LorathFlorist", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathGoldsmith.class, "LorathGoldsmith", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathLumberman.class, "LorathLumberman", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathMason.class, "LorathMason", id++, GOTFaction.LORATH);
		GOTEntityRegistry.register(GOTEntityLorathMiner.class, "LorathMiner", id++, GOTFaction.LORATH);

		GOTEntityRegistry.register(GOTEntityQohorMan.class, "QohorMan", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorLevyman.class, "QohorLevyman", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorLevymanArcher.class, "QohorLevymanArcher", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorGuard.class, "QohorGuard", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorUnsullied.class, "QohorUnsullied", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBannerBearer.class, "QohorBannerBearer", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorGuardCaptain.class, "QohorGuardCaptain", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBaker.class, "QohorBaker", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBartender.class, "QohorBartender", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBlacksmith.class, "QohorBlacksmith", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorBrewer.class, "QohorBrewer", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorButcher.class, "QohorButcher", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorFarmer.class, "QohorFarmer", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorFishmonger.class, "QohorFishmonger", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorFlorist.class, "QohorFlorist", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorGoldsmith.class, "QohorGoldsmith", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorLumberman.class, "QohorLumberman", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorMason.class, "QohorMason", id++, GOTFaction.QOHOR);
		GOTEntityRegistry.register(GOTEntityQohorMiner.class, "QohorMiner", id++, GOTFaction.QOHOR);

		GOTEntityRegistry.register(GOTEntityLysMan.class, "LysMan", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysLevyman.class, "LysLevyman", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysLevymanArcher.class, "LysLevymanArcher", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSoldier.class, "LysSoldier", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSoldierArcher.class, "LysSoldierArcher", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBannerBearer.class, "LysBannerBearer", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysGeneral.class, "LysGeneral", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSlave.class, "LysSlave", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysSlaver.class, "LysSlaver", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBaker.class, "LysBaker", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBartender.class, "LysBartender", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBlacksmith.class, "LysBlacksmith", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysBrewer.class, "LysBrewer", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysButcher.class, "LysButcher", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysFishmonger.class, "LysFishmonger", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysFlorist.class, "LysFlorist", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysGoldsmith.class, "LysGoldsmith", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysLumberman.class, "LysLumberman", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysMason.class, "LysMason", id++, GOTFaction.LYS);
		GOTEntityRegistry.register(GOTEntityLysMiner.class, "LysMiner", id++, GOTFaction.LYS);

		GOTEntityRegistry.register(GOTEntityMyrMan.class, "MyrMan", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrLevyman.class, "MyrLevyman", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrLevymanArcher.class, "MyrLevymanArcher", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSoldier.class, "MyrSoldier", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSoldierArcher.class, "MyrSoldierArcher", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBannerBearer.class, "MyrBannerBearer", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrGeneral.class, "MyrGeneral", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSlave.class, "MyrSlave", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrSlaver.class, "MyrSlaver", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBaker.class, "MyrBaker", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBartender.class, "MyrBartender", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBlacksmith.class, "MyrBlacksmith", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrBrewer.class, "MyrBrewer", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrButcher.class, "MyrButcher", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrFishmonger.class, "MyrFishmonger", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrFlorist.class, "MyrFlorist", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrGoldsmith.class, "MyrGoldsmith", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrLumberman.class, "MyrLumberman", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrMason.class, "MyrMason", id++, GOTFaction.MYR);
		GOTEntityRegistry.register(GOTEntityMyrMiner.class, "MyrMiner", id++, GOTFaction.MYR);

		GOTEntityRegistry.register(GOTEntityGoldenWarrior.class, "GoldenWarrior", id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenSpearman.class, "GoldenSpearman", id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenBannerBearer.class, "GoldenBannerBearer", id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenCaptain.class, "GoldenCaptain", id++, 0xffd700);

		GOTEntityRegistry.register(GOTEntityTyroshMan.class, "TyroshMan", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshLevyman.class, "TyroshLevyman", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshLevymanArcher.class, "TyroshLevymanArcher", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSoldier.class, "TyroshSoldier", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSoldierArcher.class, "TyroshSoldierArcher", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBannerBearer.class, "TyroshBannerBearer", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshGeneral.class, "TyroshGeneral", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSlave.class, "TyroshSlave", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshSlaver.class, "TyroshSlaver", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBaker.class, "TyroshBaker", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBartender.class, "TyroshBartender", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBlacksmith.class, "TyroshBlacksmith", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshBrewer.class, "TyroshBrewer", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshButcher.class, "TyroshButcher", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshFishmonger.class, "TyroshFishmonger", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshFlorist.class, "TyroshFlorist", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshGoldsmith.class, "TyroshGoldsmith", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshLumberman.class, "TyroshLumberman", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshMason.class, "TyroshMason", id++, GOTFaction.TYROSH);
		GOTEntityRegistry.register(GOTEntityTyroshMiner.class, "TyroshMiner", id++, GOTFaction.TYROSH);

		GOTEntityRegistry.register(GOTEntityGhiscarMan.class, "GhiscarMan", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarLevyman.class, "GhiscarLevyman", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarLevymanArcher.class, "GhiscarLevymanArcher", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarUnsullied.class, "GhiscarUnsullied", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarCorsair.class, "GhiscarCorsair", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarCorsairArcher.class, "GhiscarCorsairArcher", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarGuard.class, "GhiscarGuard", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarGladiator.class, "GhiscarGladiator", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarHarpy.class, "GhiscarHarpy", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBannerBearer.class, "GhiscarBannerBearer", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarSlave.class, "GhiscarSlave", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarSlaver.class, "GhiscarSlaver", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarAdmiral.class, "GhiscarAdmiral", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBaker.class, "GhiscarBaker", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBartender.class, "GhiscarBartender", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBlacksmith.class, "GhiscarBlacksmith", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarBrewer.class, "GhiscarBrewer", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarButcher.class, "GhiscarButcher", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarFishmonger.class, "GhiscarFishmonger", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarFlorist.class, "GhiscarFlorist", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarGoldsmith.class, "GhiscarGoldsmith", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarLumberman.class, "GhiscarLumberman", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarMason.class, "GhiscarMason", id++, GOTFaction.GHISCAR);
		GOTEntityRegistry.register(GOTEntityGhiscarMiner.class, "GhiscarMiner", id++, GOTFaction.GHISCAR);

		GOTEntityRegistry.register(GOTEntityQarthMan.class, "QarthMan", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthLevyman.class, "QarthLevyman", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthLevymanArcher.class, "QarthLevymanArcher", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthGuard.class, "QarthGuard", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBannerBearer.class, "QarthBannerBearer", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthWarlock.class, "QarthWarlock", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthGuardCaptain.class, "QarthGuardCaptain", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBaker.class, "QarthBaker", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBartender.class, "QarthBartender", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBlacksmith.class, "QarthBlacksmith", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthBrewer.class, "QarthBrewer", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthButcher.class, "QarthButcher", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthFarmer.class, "QarthFarmer", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthFishmonger.class, "QarthFishmonger", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthFlorist.class, "QarthFlorist", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthGoldsmith.class, "QarthGoldsmith", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthLumberman.class, "QarthLumberman", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthMason.class, "QarthMason", id++, GOTFaction.QARTH);
		GOTEntityRegistry.register(GOTEntityQarthMiner.class, "QarthMiner", id++, GOTFaction.QARTH);

		GOTEntityRegistry.register(GOTEntityLhazarMan.class, "LhazarMan", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarWarrior.class, "LhazarWarrior", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarArcher.class, "LhazarArcher", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBannerBearer.class, "LhazarBannerBearer", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarWarlord.class, "LhazarWarlord", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBlacksmith.class, "LhazarBlacksmith", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarMason.class, "LhazarMason", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarButcher.class, "LhazarButcher", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBrewer.class, "LhazarBrewer", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarFishmonger.class, "LhazarFishmonger", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBaker.class, "LhazarBaker", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarMiner.class, "LhazarMiner", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarGoldsmith.class, "LhazarGoldsmith", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarLumberman.class, "LhazarLumberman", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarHunter.class, "LhazarHunter", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarBartender.class, "LhazarBartender", id++, GOTFaction.LHAZAR);
		GOTEntityRegistry.register(GOTEntityLhazarFarmer.class, "LhazarFarmer", id++, GOTFaction.LHAZAR);

		GOTEntityRegistry.register(GOTEntityDothraki.class, "DothrakiMan", id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.register(GOTEntityDothrakiArcher.class, "DothrakiArcher", id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.register(GOTEntityDothrakiKhal.class, "DothrakiKhal", id++, GOTFaction.DOTHRAKI);
		GOTEntityRegistry.register(GOTEntityDothrakiKhalin.class, "DothrakiKhalin", id++, GOTFaction.DOTHRAKI);

		GOTEntityRegistry.register(GOTEntityIbbenMan.class, "IbbenMan", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenWarrior.class, "IbbenWarrior", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenArcher.class, "IbbenArcher", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenAxeThrower.class, "IbbenAxeThrower", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenMarshal.class, "IbbenCaptain", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBlacksmith.class, "IbbenBlacksmith", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenMeadhost.class, "IbbenMeadhost", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBannerBearer.class, "IbbenBannerBearer", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenFarmhand.class, "IbbenFarmhand", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenFarmer.class, "IbbenFarmer", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenLumberman.class, "IbbenLumberman", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBuilder.class, "IbbenBuilder", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBrewer.class, "IbbenBrewer", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenButcher.class, "IbbenButcher", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenFishmonger.class, "IbbenFishmonger", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenBaker.class, "IbbenBaker", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenOrcharder.class, "IbbenOrcharder", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIbbenStablemaster.class, "IbbenStablemaster", id++, GOTFaction.IBBEN);
		GOTEntityRegistry.register(GOTEntityIfekevron.class, "Ifekevron", id++, GOTFaction.IBBEN);

		GOTEntityRegistry.register(GOTEntityJogos.class, "JogosMan", id++, GOTFaction.JOGOS);
		GOTEntityRegistry.register(GOTEntityJogosArcher.class, "JogosArcher", id++, GOTFaction.JOGOS);
		GOTEntityRegistry.register(GOTEntityJogosChief.class, "JogosChief", id++, GOTFaction.JOGOS);
		GOTEntityRegistry.register(GOTEntityJogosShaman.class, "JogosShaman", id++, GOTFaction.JOGOS);

		GOTEntityRegistry.register(GOTEntityMossovyMan.class, "MossovyMan", id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyWitcher.class, "MossovyWitcher", id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyBlacksmith.class, "MossovyBlacksmith", id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyFarmer.class, "MossovyFarmer", id++, GOTFaction.MOSSOVY);
		GOTEntityRegistry.register(GOTEntityMossovyBartender.class, "MossovyBartender", id++, GOTFaction.MOSSOVY);

		GOTEntityRegistry.register(GOTEntityYiTiMan.class, "YiTiMan", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiLevyman.class, "YiTiLevyman", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiLevymanCrossbower.class, "YiTiLevymanCrossbower", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiSoldier.class, "YiTiSoldier", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiSoldierCrossbower.class, "YiTiSoldierCrossbower", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFrontier.class, "YiTiFrontier", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFrontierCrossbower.class, "YiTiFrontierCrossbower", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiSamurai.class, "YiTiSamurai", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBombardier.class, "YiTiBombardier", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBannerBearer.class, "YiTiBannerBearer", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFireThrower.class, "YiTiFirePriest", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiShogune.class, "YiTiShogun", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFarmhand.class, "YiTiFarmhand", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBlacksmith.class, "YiTiBlacksmith", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiLumberman.class, "YiTiLumberman", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiMason.class, "YiTiMason", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiButcher.class, "YiTiButcher", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBrewer.class, "YiTiBrewer", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFishmonger.class, "YiTiFishmonger", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBaker.class, "YiTiBaker", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiHunter.class, "YiTiHunter", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiFarmer.class, "YiTiFarmer", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiGoldsmith.class, "YiTiGoldsmith", id++, GOTFaction.YI_TI);
		GOTEntityRegistry.register(GOTEntityYiTiBartender.class, "YiTiBartender", id++, GOTFaction.YI_TI);

		GOTEntityRegistry.register(GOTEntityAsshaiMan.class, "AsshaiMan", id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiGuard.class, "AsshaiGuard", id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiBannerBearer.class, "AsshaiBannerBearer", id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiShadowbinder.class, "AsshaiShadowbinder", id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiSpherebinder.class, "AsshaiSpherebinder", id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiAlchemist.class, "AsshaiAlchemist", id++, GOTFaction.ASSHAI);
		GOTEntityRegistry.register(GOTEntityAsshaiCaptain.class, "AsshaiCaptain", id++, GOTFaction.ASSHAI);

		GOTEntityRegistry.register(GOTEntitySothoryosMan.class, "SothoryosMan", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosWarrior.class, "SothoryosWarrior", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosBannerBearer.class, "SothoryosBannerBearer", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosChieftain.class, "SothoryosChieftain", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosBlowgunner.class, "SothoryosBlowgunner", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosShaman.class, "SothoryosShaman", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosFarmer.class, "SothoryosFarmer", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosFarmhand.class, "SothoryosFarmhand", id++, GOTFaction.SOTHORYOS);
		GOTEntityRegistry.register(GOTEntitySothoryosSmith.class, "SothoryosSmith", id++, GOTFaction.SOTHORYOS);

		GOTEntityRegistry.register(GOTEntitySummerMan.class, "SummerMan", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerWarrior.class, "SummerWarrior", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerArcher.class, "SummerArcher", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBannerBearer.class, "SummerBannerBearer", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerWarlord.class, "SummerWarlord", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBlacksmith.class, "SummerBlacksmith", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBartender.class, "SummerBartender", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerLumberman.class, "SummerLumberman", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerMason.class, "SummerMason", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerButcher.class, "SummerButcher", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBrewer.class, "SummerBrewer", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerFishmonger.class, "SummerFishmonger", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerBaker.class, "SummerBaker", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerHunter.class, "SummerHunter", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerMiner.class, "SummerMiner", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerFarmhand.class, "SummerFarmhand", id++, GOTFaction.SUMMER_ISLANDS);
		GOTEntityRegistry.register(GOTEntitySummerFarmer.class, "SummerFarmer", id++, GOTFaction.SUMMER_ISLANDS);

		GOTEntityRegistry.register(GOTEntityUlthosSpider.class, "GiantSpider", id++, GOTFaction.ULTHOS);

		GOTEntityRegistry.register(GOTEntityAddamMarbrand.class, "AddamMarbrand", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAemonTargaryen.class, "AemonTargaryen", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAeronGreyjoy.class, "AeronGreyjoy", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAlliserThorne.class, "AlliserThorne", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAmoryLorch.class, "AmoryLorch", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAndersYronwood.class, "AndersYronwood", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAndrikTheUnsmilling.class, "AndrikTheUnsmilling", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAnyaWaynwood.class, "AnyaWaynwood", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityArdrianCeltigar.class, "ArdrianCeltigar", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAreoHotah.class, "AreoHotah", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityArianneMartell.class, "ArianneMartell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAryaStark.class, "AryaStark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAsshaiArchmag.class, "AsshaiArchmag", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityAuraneWaters.class, "AuraneWaters", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBaelorBlacktyde.class, "BaelorBlacktyde", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBalonGreyjoy.class, "BalonGreyjoy", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBarbreyDustin.class, "BarbreyDustin", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBarristanSelmy.class, "BarristanSelmy", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBenedarBelmore.class, "BenedarBelmore", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBenjenStark.class, "BenjenStark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBericDayne.class, "BericDayne", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBericDondarrion.LifeStage1.class, "BericDondarrion1", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBericDondarrion.LifeStage2.class, "BericDondarrion2", id++);
		GOTEntityRegistry.register(GOTEntityBericDondarrion.LifeStage3.class, "BericDondarrion3", id++);
		GOTEntityRegistry.register(GOTEntityBericDondarrion.LifeStage4.class, "BericDondarrion4", id++);
		GOTEntityRegistry.register(GOTEntityBericDondarrion.LifeStage5.class, "BericDondarrion5", id++);
		GOTEntityRegistry.register(GOTEntityBericDondarrion.LifeStage6.class, "BericDondarrion6", id++);
		GOTEntityRegistry.register(GOTEntityBlackWalderFrey.class, "BlackWalderFrey", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBranStark.class, "BranStark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBrienneTarth.class, "BrienneTarth", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBronn.class, "Bronn", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBryndenTully.class, "BryndenTully", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityBuGai.class, "BuGai", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityCatelynStark.class, "CatelynStark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityCerseiLannister.class, "CerseiLannister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityClementPiper.class, "ClementPiper", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityCleyCerwyn.class, "CleyCerwyn", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityCotterPyke.class, "CotterPyke", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityCraster.class, "Craster", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDaarioNaharis.class, "DaarioNaharis", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDaenerysTargaryen.class, "DaenerysTargaryen", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDagmer.class, "Dagmer", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDavenLannister.class, "DavenLannister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDavosSeaworth.class, "DavosSeaworth", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDenysMallister.class, "DenysMallister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDoranMartell.class, "DoranMartell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityDunstanDrumm.class, "DunstanDrumm", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityEbrose.class, "Ebrose", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityEdd.class, "Edd", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityEdmureTully.class, "EdmureTully", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityEldonEstermont.class, "EldonEstermont", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityEllaryaSand.class, "EllaryaSand", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityErikIronmaker.class, "ErikIronmaker", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityEuronGreyjoy.class, "EuronGreyjoy", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityForleyPrester.class, "ForleyPrester", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityFranklynFowler.class, "FranklynFowler", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGarlanTyrell.class, "GarlanTyrell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGendryBaratheon.class, "GendryBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGeroldDayne.class, "GeroldDayne", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGeroldGrafton.class, "GeroldGrafton", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGilwoodHunter.class, "GilwoodHunter", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGoroldGoodbrother.class, "GoroldGoodbrother", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGregorClegane.Alive.class, "GregorClegane", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGregorClegane.Dead.class, "GregorCleganeWight", id++);
		GOTEntityRegistry.register(GOTEntityGreyWorm.class, "GreyWorm", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGulianSwann.class, "GulianSwann", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityGylbertFarwynd.class, "GylbertFarwynd", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHarmenUller.class, "HarmenUller", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHarmune.class, "Harmune", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHarrasHarlaw.class, "HarrasHarlaw", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHarroldHardyng.class, "HarroldHardyng", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHarryStrickland.class, "HarryStrickland", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHarysSwyft.class, "HarysSwyft", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHelmanTallhart.class, "HelmanTallhart", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHighSepton.class, "HighSepton", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHizdahrZoLoraq.class, "HizdahrZoLoraq", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHodor.class, "Hodor", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHortonRedfort.class, "HortonRedfort", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHosterTully.class, "HosterTully", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHotPie.class, "HotPie", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityHowlandReed.class, "HowlandReed", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityIllyrioMopatis.class, "IllyrioMopatis", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityIlynPayne.class, "IlynPayne", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJaimeLannister.class, "JaimeLannister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJanosSlynt.class, "JanosSlynt", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJaqenHghar.class, "JaqenHghar", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJasonMallister.class, "JasonMallister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJeorMormont.class, "JeorMormont", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJoffreyBaratheon.class, "JoffreyBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJohnUmber.class, "JohnUmber", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJonConnington.class, "JonConnington", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJonSnow.Stage1.class, "JonSnow", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJonSnow.Stage2.class, "JonSnow2", id++);
		GOTEntityRegistry.register(GOTEntityJonosBracken.class, "JonosBracken", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityJorahMormont.class, "JorahMormont", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityKevanLannister.class, "KevanLannister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityKitraJuvain.class, "KitraJuvain", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityKraznysMoNakloz.class, "KraznysMoNakloz", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLancelLannister.Normal.class, "LancelLannister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLancelLannister.Religious.class, "LancelLannisterR", id++);
		GOTEntityRegistry.register(GOTEntityLeoLefford.class, "LeoLefford", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLeytonHightower.class, "LeytonHightower", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLorasTyrell.class, "LorasTyrell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLotharFrey.class, "LotharFrey", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLuwin.class, "Luwin", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLyleCrakehall.class, "LyleCrakehall", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLynCorbray.class, "LynCorbray", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityLysaArryn.class, "LysaArryn", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMaceTyrell.class, "MaceTyrell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMaegeMormont.class, "MaegeMormont", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityManceRayder.class, "ManceRayder", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityManfreyMartell.class, "ManfreyMartell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMargaeryTyrell.class, "MargaeryTyrell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMaronVolmark.class, "MaronVolmark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMathisRowan.class, "MathisRowan", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMatthosSeaworth.class, "MatthosSeaworth", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMelisandra.class, "Melisandra", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMellario.class, "Mellario", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMerynTrant.class, "MerynTrant", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMissandei.class, "Missandei", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMonfordVelaryon.class, "MonfordVelaryon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMoqorro.class, "Moqorro", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMullin.class, "Mullin", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityMyrcellaBaratheon.class, "MyrcellaBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityNightKing.class, "NightKing", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityOberynMartell.class, "OberynMartell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityOlennaTyrell.class, "OlennaTyrell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityOrtonMerryweather.class, "OrtonMerryweather", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityOsha.class, "Osha", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityPaxterRedwyne.class, "PaxterRedwyne", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityPetyrBaelish.class, "PetyrBaelish", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityPodrickPayne.class, "PodrickPayne", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityPolliver.class, "Polliver", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityPycelle.class, "Pycelle", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityQuennRoxton.class, "QuennRoxton", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityQuentenBanefort.class, "QuentenBanefort", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityQuentynMartell.class, "QuentynMartell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityQuentynQorgyle.class, "QuentynQorgyle", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityQyburn.class, "Qyburn", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRamsayBolton.class, "RamsayBolton", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRandyllTarly.class, "RandyllTarly", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRazdalMoEraz.class, "RazdalMoEraz", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRenlyBaratheon.class, "RenlyBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRickardKarstark.class, "RickardKarstark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRickonStark.class, "RickonStark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRobbStark.class, "RobbStark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRobinArryn.class, "RobinArryn", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRodrikCassel.class, "RodrikCassel", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRodrikHarlaw.class, "RodrikHarlaw", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRodrikRyswell.class, "RodrikRyswell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityRooseBolton.class, "RooseBolton", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySalladhorSaan.class, "SalladhorSaan", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySamwellTarly.class, "SamwellTarly", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySandorClegane.class, "SandorClegane", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySansaStark.class, "SansaStark", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySebastonFarman.class, "SebastonFarman", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySelwynTarth.class, "SelwynTarth", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySelyseBaratheon.class, "SelyseBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityShae.class, "Shae", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityShireenBaratheon.class, "ShireenBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityStannisBaratheon.class, "StannisBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntitySymondTempleton.class, "SymondTempleton", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTheonGreyjoy.Normal.class, "TheonGreyjoy", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTheonGreyjoy.Tormented.class, "TheonGreyjoyV", id++);
		GOTEntityRegistry.register(GOTEntityThoros.class, "Thoros", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityThreeEyedRaven.class, "ThreeEyedRaven", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTobhoMott.class, "TobhoMott", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTommenBaratheon.class, "TommenBaratheon", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTormund.class, "Tormund", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTrystaneMartell.class, "TrystaneMartell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTychoNestoris.class, "TychoNestoris", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTyrionLannister.class, "TyrionLannister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTytosBlackwood.class, "TytosBlackwood", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTytosBrax.class, "TytosBrax", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityTywinLannister.class, "TywinLannister", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityVargoHoat.class, "VargoHoat", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityVarys.class, "Varys", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityVictarionGreyjoy.class, "VictarionGreyjoy", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityWalderFrey.class, "WalderFrey", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityWillasTyrell.class, "WillasTyrell", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityWilliamMooton.class, "WilliamMooton", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityWymanManderly.class, "WymanManderly", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityXaroXhoanDaxos.class, "XaroXhoanDaxos", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityYaraGreyjoy.class, "YaraGreyjoy", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityYgritte.class, "Ygritte", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityYohnRoyce.class, "YohnRoyce", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityYoungGriff.class, "YoungGriff", id++, 9605778);
		GOTEntityRegistry.register(GOTEntityYoren.class, "Yoren", id++, 9605778);

		GOTEntityRegistry.register(GOTEntityPortal.class, "Portal", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntitySmokeRing.class, "SmokeRing", id++, 64, 10, true);
		GOTEntityRegistry.register(GOTEntityBomb.class, "Bomb", id++, 160, 10, true);
		GOTEntityRegistry.register(GOTEntitySpear.class, "Spear", id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.register(GOTEntityPlate.class, "Plate", id++, 64, 3, true);
		GOTEntityRegistry.register(GOTEntityThrowingAxe.class, "ThrowingAxe", id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.register(GOTEntityCrossbowBolt.class, "CrossbowBolt", id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.register(GOTEntityPebble.class, "Pebble", id++, 64, 3, true);
		GOTEntityRegistry.register(GOTEntityMysteryWeb.class, "MysteryWeb", id++, 64, 10, true);
		GOTEntityRegistry.register(GOTEntityTraderRespawn.class, "TraderRespawn", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntityThrownRock.class, "ThrownRock", id++, 64, 10, true);
		GOTEntityRegistry.register(GOTEntityBarrel.class, "Barrel", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntityInvasionSpawner.class, "InvasionSpawner", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntityThrownTermite.class, "ThrownTermite", id++, 64, 10, true);
		GOTEntityRegistry.register(GOTEntityConker.class, "Conker", id++, 64, 3, true);
		GOTEntityRegistry.register(GOTEntityFishHook.class, "GOTFishHook", id++, 64, 5, true);
		GOTEntityRegistry.register(GOTEntityDart.class, "Dart", id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.register(GOTEntityNPCRespawner.class, "NPCRespawner", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntityFallingTreasure.class, "FallingTreasure", id++, 160, 20, true);
		GOTEntityRegistry.register(GOTEntityFallingFireJar.class, "FallingFireJar", id++, 160, 20, true);
		GOTEntityRegistry.register(GOTEntityFirePot.class, "ThrownFirePot", id++, 64, 3, true);
		GOTEntityRegistry.register(GOTEntityArrowPoisoned.class, "ArrowPoison", id++, 64, 20, false);
		GOTEntityRegistry.register(GOTEntityArrowFire.class, "ArrowFire", id++, 64, 20, false);
		GOTEntityRegistry.register(GOTEntityLionRug.class, "LionRug", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntityBearRug.class, "BearRug", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntityGiraffeRug.class, "GiraffeRug", id++, 80, 3, true);
		GOTEntityRegistry.register(GOTEntityBanner.class, "Banner", id++, 160, 3, true);
		GOTEntityRegistry.register(GOTEntityBannerWall.class, "WallBanner", id++, 160, Integer.MAX_VALUE, false);
		GOTEntityRegistry.register(GOTEntityLingeringPotion.class, "LingeringPotion", id++, 64, 10, true);
		GOTEntityRegistry.register(GOTEntityLingeringEffect.class, "LingeringEffect", id++, 64, 1, true);
		GOTEntityRegistry.register(GOTEntityCargocart.class, "Cargocart", id++, 80, 20, false);
		GOTEntityRegistry.register(GOTEntityPlowcart.class, "Plowcart", id++, 80, 20, false);
		GOTEntityRegistry.register(GOTEntityGrapplingArrow.class, "GrapplingArrow", id++, 900, 1, true);
		GOTEntityRegistry.register(GOTEntityMotorGrapplingArrow.class, "MotorGrapplingArrow", id++, 900, 1, true);

		GOTEntityRegistry.register(GOTEntityHummel009.class, "Hummel009", id++);
	}
}