package got.client.render;

import java.util.*;

import got.client.effect.GOTEntityAlignmentBonus;
import got.client.render.animal.*;
import got.client.render.npc.*;
import got.client.render.other.*;
import got.common.database.GOTRegistry;
import got.common.entity.animal.*;
import got.common.entity.dragon.GOTEntityDragon;
import got.common.entity.essos.*;
import got.common.entity.essos.asshai.*;
import got.common.entity.essos.braavos.GOTEntityBraavosMan;
import got.common.entity.essos.dothraki.GOTEntityDothraki;
import got.common.entity.essos.ghiscar.*;
import got.common.entity.essos.gold.GOTEntityGoldenMan;
import got.common.entity.essos.ibben.*;
import got.common.entity.essos.jogos.GOTEntityJogos;
import got.common.entity.essos.legendary.GOTEntityMissandei;
import got.common.entity.essos.legendary.captain.*;
import got.common.entity.essos.legendary.quest.*;
import got.common.entity.essos.legendary.trader.*;
import got.common.entity.essos.legendary.warrior.*;
import got.common.entity.essos.lhazar.GOTEntityLhazarMan;
import got.common.entity.essos.lorath.GOTEntityLorathMan;
import got.common.entity.essos.lys.*;
import got.common.entity.essos.mossovy.*;
import got.common.entity.essos.myr.*;
import got.common.entity.essos.norvos.GOTEntityNorvosMan;
import got.common.entity.essos.pentos.GOTEntityPentosMan;
import got.common.entity.essos.qarth.*;
import got.common.entity.essos.qohor.*;
import got.common.entity.essos.tyrosh.*;
import got.common.entity.essos.volantis.*;
import got.common.entity.essos.yiti.GOTEntityYiTiMan;
import got.common.entity.other.*;
import got.common.entity.sothoryos.sothoryos.*;
import got.common.entity.sothoryos.summer.GOTEntitySummerMan;
import got.common.entity.westeros.*;
import got.common.entity.westeros.arryn.GOTEntityArrynMan;
import got.common.entity.westeros.crownlands.*;
import got.common.entity.westeros.dorne.GOTEntityDorneMan;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneMan;
import got.common.entity.westeros.gift.GOTEntityGiftMan;
import got.common.entity.westeros.hillmen.*;
import got.common.entity.westeros.ice.*;
import got.common.entity.westeros.ironborn.*;
import got.common.entity.westeros.legendary.GOTEntityCrasterWife;
import got.common.entity.westeros.legendary.captain.*;
import got.common.entity.westeros.legendary.deco.*;
import got.common.entity.westeros.legendary.quest.*;
import got.common.entity.westeros.legendary.reborn.*;
import got.common.entity.westeros.legendary.trader.*;
import got.common.entity.westeros.legendary.warrior.*;
import got.common.entity.westeros.north.GOTEntityNorthMan;
import got.common.entity.westeros.north.hillmen.*;
import got.common.entity.westeros.reach.GOTEntityReachMan;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsMan;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsMan;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsMan;
import got.common.entity.westeros.wildling.*;
import got.common.entity.westeros.wildling.thenn.*;
import net.minecraft.client.renderer.entity.*;
import net.minecraft.entity.projectile.EntityPotion;
import net.minecraft.init.Items;

public class GOTRender {
	private static Map<Class, Render> renders = new HashMap<>();

	public static Map<Class, Render> getRenders() {
		return renders;
	}

	public static void onInit() {
		getRenders().put(GOTEntityHillman.class, new GOTRenderFactionNPCLayered("westeros/wild"));
		getRenders().put(GOTEntityIbbenMan.class, new GOTRenderFactionNPCLayered("essos/ibben"));
		getRenders().put(GOTEntityNorthHillman.class, new GOTRenderFactionNPCLayered("westeros/wild"));
		getRenders().put(GOTEntityArrynMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		getRenders().put(GOTEntityAsshaiMan.class, new GOTRenderFactionNPC("essos/asshai"));
		getRenders().put(GOTEntityBraavosMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityCrasterWife.class, new GOTRenderFactionNPC("westeros/wild"));
		getRenders().put(GOTEntityCrownlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		getRenders().put(GOTEntityDorneMan.class, new GOTRenderFactionNPC("westeros/dorne"));
		getRenders().put(GOTEntityDothraki.class, new GOTRenderFactionNPC("essos/nomad"));
		getRenders().put(GOTEntityDragonstoneMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		getRenders().put(GOTEntityGhiscarMan.class, new GOTRenderFactionNPC("essos/ghiscar"));
		getRenders().put(GOTEntityGhiscarSlave.class, new GOTRenderFactionNPC("essos/slave"));
		getRenders().put(GOTEntityGiftMan.class, new GOTRenderFactionNPC("westeros/gift"));
		getRenders().put(GOTEntityGoldenMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityHillmanWarrior.class, new GOTRenderFactionNPC("westeros/wild"));
		getRenders().put(GOTEntityIbbenWarrior.class, new GOTRenderFactionNPC("essos/ibben"));
		getRenders().put(GOTEntityIronbornMan.class, new GOTRenderFactionNPC("westeros/ironborn"));
		getRenders().put(GOTEntityJogos.class, new GOTRenderFactionNPC("essos/jogos"));
		getRenders().put(GOTEntityLhazarMan.class, new GOTRenderFactionNPC("essos/nomad"));
		getRenders().put(GOTEntityLorathMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityLysMan.class, new GOTRenderFactionNPC("essos/violet"));
		getRenders().put(GOTEntityLysSlave.class, new GOTRenderFactionNPC("essos/slave"));
		getRenders().put(GOTEntityMyrMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityMyrSlave.class, new GOTRenderFactionNPC("essos/slave"));
		getRenders().put(GOTEntityNorthMan.class, new GOTRenderFactionNPC("westeros/north"));
		getRenders().put(GOTEntityNorthHillmanWarrior.class, new GOTRenderFactionNPC("westeros/wild"));
		getRenders().put(GOTEntityNorvosMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityPentosMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityQarthMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityQohorMan.class, new GOTRenderFactionNPC("essos/free"));
		getRenders().put(GOTEntityReachMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		getRenders().put(GOTEntityRiverlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		getRenders().put(GOTEntitySothoryosMan.class, new GOTRenderFactionNPC("sothoryos/sothoryos"));
		getRenders().put(GOTEntityStormlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		getRenders().put(GOTEntitySummerMan.class, new GOTRenderFactionNPC("sothoryos/summer"));
		getRenders().put(GOTEntityThenn.class, new GOTRenderFactionNPC("westeros/thenn"));
		getRenders().put(GOTEntityTyroshMan.class, new GOTRenderFactionNPC("essos/colored"));
		getRenders().put(GOTEntityTyroshSlave.class, new GOTRenderFactionNPC("essos/slave"));
		getRenders().put(GOTEntityVolantisMan.class, new GOTRenderFactionNPC("essos/violet"));
		getRenders().put(GOTEntityVolantisSlave.class, new GOTRenderFactionNPC("essos/slave"));
		getRenders().put(GOTEntityWesterlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		getRenders().put(GOTEntityWight.class, new GOTRenderFactionNPC("westeros/ice/wight"));
		getRenders().put(GOTEntityWildling.class, new GOTRenderFactionNPC("westeros/wild"));
		getRenders().put(GOTEntityYiTiMan.class, new GOTRenderFactionNPC("essos/yiti"));
		getRenders().put(GOTEntityMossovyMan.class, new GOTRenderFactionNPC("essos/mossovy"));
		getRenders().put(GOTEntitySepton.class, new GOTRenderFactionNPCLayered("westeros/westeros", "septon"));
		getRenders().put(GOTEntityRedPriest.class, new GOTRenderFactionNPCLayered("essos/asshai", "priest"));
		getRenders().put(GOTEntityIronbornPriest.class, new GOTRenderFactionNPCLayered("westeros/ironborn", "priest"));
		getRenders().put(GOTEntityIfekevron.class, new GOTRenderFactionNPCLayered("essos/ifekevron"));
		getRenders().put(GOTEntityMercenary.class, new GOTRenderFactionNPCLayered("westeros/westeros", "mercenary"));
		getRenders().put(GOTEntitySothoryosShaman.class, new GOTRenderFactionNPCLayered("sothoryos/sothoryos", "shaman"));
		getRenders().put(GOTEntityAddamMarbrand.class, new GOTRenderLegendaryNPC("addam_marbrand"));
		getRenders().put(GOTEntityAemonTargaryen.class, new GOTRenderLegendaryNPC("aemon"));
		getRenders().put(GOTEntityAeronGreyjoy.class, new GOTRenderLegendaryNPC("aeron_greyjoy"));
		getRenders().put(GOTEntityAmoryLorch.class, new GOTRenderLegendaryNPC("amory_lorch"));
		getRenders().put(GOTEntityAndersYronwood.class, new GOTRenderLegendaryNPC("anders_yronwood"));
		getRenders().put(GOTEntityAndrikTheUnsmilling.class, new GOTRenderLegendaryNPC("andrik_the_unsmilling"));
		getRenders().put(GOTEntityAnyaWaynwood.class, new GOTRenderLegendaryNPC("anya_waynwood"));
		getRenders().put(GOTEntityArdrianCeltigar.class, new GOTRenderLegendaryNPC("ardrian_celtigar"));
		getRenders().put(GOTEntityAreoHotah.class, new GOTRenderLegendaryNPC("areo_hotah", 1.2f));
		getRenders().put(GOTEntityArianneMartell.class, new GOTRenderLegendaryNPC("arianne_martell"));
		getRenders().put(GOTEntityAryaStark.class, new GOTRenderLegendaryNPC("arya_stark", 0.75f));
		getRenders().put(GOTEntityAsshaiArchmag.class, new GOTRenderLegendaryNPC("archmag"));
		getRenders().put(GOTEntityAuraneWaters.class, new GOTRenderLegendaryNPC("aurane_waters"));
		getRenders().put(GOTEntityBaelorBlacktyde.class, new GOTRenderLegendaryNPC("baelor_blacktyde"));
		getRenders().put(GOTEntityBarbreyDustin.class, new GOTRenderLegendaryNPC("barbrey_dustin"));
		getRenders().put(GOTEntityBarristanSelmy.class, new GOTRenderLegendaryNPC("barristan_selmy"));
		getRenders().put(GOTEntityBericDayne.class, new GOTRenderLegendaryNPC("beric_dayne"));
		getRenders().put(GOTEntityBlackWalderFrey.class, new GOTRenderLegendaryNPC("black_walder_frey"));
		getRenders().put(GOTEntityBranStark.class, new GOTRenderLegendaryNPC("bran_stark", 0.75f));
		getRenders().put(GOTEntityBronn.class, new GOTRenderLegendaryNPC("bronn"));
		getRenders().put(GOTEntityCatelynStark.class, new GOTRenderLegendaryNPC("catelyn_stark"));
		getRenders().put(GOTEntityCerseiLannister.class, new GOTRenderLegendaryNPC("cersei_lannister"));
		getRenders().put(GOTEntityClementPiper.class, new GOTRenderLegendaryNPC("clement_piper"));
		getRenders().put(GOTEntityCleyCerwyn.class, new GOTRenderLegendaryNPC("cley_cerwyn"));
		getRenders().put(GOTEntityDaarioNaharis.class, new GOTRenderLegendaryNPC("daario_naharis"));
		getRenders().put(GOTEntityDaenerysTargaryen.class, new GOTRenderLegendaryNPC("daenerys_targaryen"));
		getRenders().put(GOTEntityDagmer.class, new GOTRenderLegendaryNPC("dagmer"));
		getRenders().put(GOTEntityDavenLannister.class, new GOTRenderLegendaryNPC("daven_lannister"));
		getRenders().put(GOTEntityDoranMartell.class, new GOTRenderLegendaryNPC("doran_martell"));
		getRenders().put(GOTEntityDunstanDrumm.class, new GOTRenderLegendaryNPC("dunstan_drumm"));
		getRenders().put(GOTEntityEbrose.class, new GOTRenderLegendaryNPC("ebrose"));
		getRenders().put(GOTEntityEldonEstermont.class, new GOTRenderLegendaryNPC("eldon_estermont"));
		getRenders().put(GOTEntityEllaryaSand.class, new GOTRenderLegendaryNPC("ellarya_sand"));
		getRenders().put(GOTEntityErikIronmaker.class, new GOTRenderLegendaryNPC("erik_ironmaker"));
		getRenders().put(GOTEntityForleyPrester.class, new GOTRenderLegendaryNPC("forley_prester"));
		getRenders().put(GOTEntityFranklynFowler.class, new GOTRenderLegendaryNPC("franklyn_fowler"));
		getRenders().put(GOTEntityGarlanTyrell.class, new GOTRenderLegendaryNPC("garlan_tyrell"));
		getRenders().put(GOTEntityGendryBaratheon.class, new GOTRenderLegendaryNPC("gendry_baratheon"));
		getRenders().put(GOTEntityGeroldDayne.class, new GOTRenderLegendaryNPC("gerold_dayne"));
		getRenders().put(GOTEntityGeroldGrafton.class, new GOTRenderLegendaryNPC("gerold_grafton"));
		getRenders().put(GOTEntityGilwoodHunter.class, new GOTRenderLegendaryNPC("gilwood_hunter"));
		getRenders().put(GOTEntityGoroldGoodbrother.class, new GOTRenderLegendaryNPC("gorold_goodbrother"));
		getRenders().put(GOTEntityGreyWorm.class, new GOTRenderLegendaryNPC("grey_worm"));
		getRenders().put(GOTEntityGulianSwann.class, new GOTRenderLegendaryNPC("gulian_swann"));
		getRenders().put(GOTEntityGylbertFarwynd.class, new GOTRenderLegendaryNPC("gylbert_farwynd"));
		getRenders().put(GOTEntityHarmenUller.class, new GOTRenderLegendaryNPC("harmen_uller"));
		getRenders().put(GOTEntityHarmune.class, new GOTRenderLegendaryNPC("harmune"));
		getRenders().put(GOTEntityHarrasHarlaw.class, new GOTRenderLegendaryNPC("harras_harlaw"));
		getRenders().put(GOTEntityHarroldHardyng.class, new GOTRenderLegendaryNPC("harrold_hardyng"));
		getRenders().put(GOTEntityHarysSwyft.class, new GOTRenderLegendaryNPC("harys_swyft"));
		getRenders().put(GOTEntityHelmanTallhart.class, new GOTRenderLegendaryNPC("helman_tallhart"));
		getRenders().put(GOTEntityHizdahrZoLoraq.class, new GOTRenderLegendaryNPC("hizdahr_zo_loraq"));
		getRenders().put(GOTEntityHodor.class, new GOTRenderLegendaryNPC("hodor", 1.3f));
		getRenders().put(GOTEntityHortonRedfort.class, new GOTRenderLegendaryNPC("horton_redfort"));
		getRenders().put(GOTEntityHosterTully.class, new GOTRenderLegendaryNPC("hoster_tully"));
		getRenders().put(GOTEntityHummel009.class, new GOTRenderLegendaryNPC("hummel009"));
		getRenders().put(GOTEntityIlynPayne.class, new GOTRenderLegendaryNPC("ilyn_payne"));
		getRenders().put(GOTEntityJanosSlynt.class, new GOTRenderLegendaryNPC("janos_slynt"));
		getRenders().put(GOTEntityJaqenHghar.class, new GOTRenderLegendaryNPC("jaqen_hghar"));
		getRenders().put(GOTEntityJasonMallister.class, new GOTRenderLegendaryNPC("jason_mallister"));
		getRenders().put(GOTEntityJonConnington.class, new GOTRenderLegendaryNPC("jon_connington"));
		getRenders().put(GOTEntityJonosBracken.class, new GOTRenderLegendaryNPC("jonos_bracken"));
		getRenders().put(GOTEntityJorahMormont.class, new GOTRenderLegendaryNPC("jorah_mormont"));
		getRenders().put(GOTEntityKevanLannister.class, new GOTRenderLegendaryNPC("kevan_lannister"));
		getRenders().put(GOTEntityTugarKhan.class, new GOTRenderLegendaryNPC("tugar_khan", 1.3f));
		getRenders().put(GOTEntityLeoLefford.class, new GOTRenderLegendaryNPC("leo_lefford"));
		getRenders().put(GOTEntityLeytonHightower.class, new GOTRenderLegendaryNPC("leyton_hightower"));
		getRenders().put(GOTEntityLorasTyrell.class, new GOTRenderLegendaryNPC("loras_tyrell"));
		getRenders().put(GOTEntityLotharFrey.class, new GOTRenderLegendaryNPC("lothar_frey"));
		getRenders().put(GOTEntityLuwin.class, new GOTRenderLegendaryNPC("luwin"));
		getRenders().put(GOTEntityLyleCrakehall.class, new GOTRenderLegendaryNPC("lyle_crakehall"));
		getRenders().put(GOTEntityLynCorbray.class, new GOTRenderLegendaryNPC("lyn_corbray"));
		getRenders().put(GOTEntityLysaArryn.class, new GOTRenderLegendaryNPC("lysa_arryn"));
		getRenders().put(GOTEntityManfreyMartell.class, new GOTRenderLegendaryNPC("manfrey_martell"));
		getRenders().put(GOTEntityMargaeryTyrell.class, new GOTRenderLegendaryNPC("margaery_tyrell"));
		getRenders().put(GOTEntityMaronVolmark.class, new GOTRenderLegendaryNPC("maron_volmark"));
		getRenders().put(GOTEntityMathisRowan.class, new GOTRenderLegendaryNPC("mathis_rowan"));
		getRenders().put(GOTEntityMelisandra.class, new GOTRenderLegendaryNPC("melisandra"));
		getRenders().put(GOTEntityMellario.class, new GOTRenderLegendaryNPC("mellario"));
		getRenders().put(GOTEntityMerynTrant.class, new GOTRenderLegendaryNPC("meryn_trant"));
		getRenders().put(GOTEntityMissandei.class, new GOTRenderLegendaryNPC("missandei"));
		getRenders().put(GOTEntityMonfordVelaryon.class, new GOTRenderLegendaryNPC("monford_velaryon"));
		getRenders().put(GOTEntityMoribaldChester.class, new GOTRenderLegendaryNPC("moribald_chester"));
		getRenders().put(GOTEntityMullin.class, new GOTRenderLegendaryNPC("mullin"));
		getRenders().put(GOTEntityMyrcellaBaratheon.class, new GOTRenderLegendaryNPC("myrcella_baratheon", 0.9f));
		getRenders().put(GOTEntityNightKing.class, new GOTRenderLegendaryNPC("night_king", 1.1f));
		getRenders().put(GOTEntityOberynMartell.class, new GOTRenderLegendaryNPC("oberyn_martell"));
		getRenders().put(GOTEntityOlennaTyrell.class, new GOTRenderLegendaryNPC("olenna_tyrell"));
		getRenders().put(GOTEntityOrtonMerryweather.class, new GOTRenderLegendaryNPC("orton_merryweather"));
		getRenders().put(GOTEntityPaxterRedwyne.class, new GOTRenderLegendaryNPC("paxter_redwyne"));
		getRenders().put(GOTEntityPetyrBaelish.class, new GOTRenderLegendaryNPC("petyr_baelish"));
		getRenders().put(GOTEntityPodrickPayne.class, new GOTRenderLegendaryNPC("podrick_payne"));
		getRenders().put(GOTEntityPolliver.class, new GOTRenderLegendaryNPC("polliver"));
		getRenders().put(GOTEntityPycelle.class, new GOTRenderLegendaryNPC("pycelle"));
		getRenders().put(GOTEntityQuennRoxton.class, new GOTRenderLegendaryNPC("quenn_roxton"));
		getRenders().put(GOTEntityQuentenBanefort.class, new GOTRenderLegendaryNPC("quenten_banefort"));
		getRenders().put(GOTEntityQuentynMartell.class, new GOTRenderLegendaryNPC("quentyn_martell"));
		getRenders().put(GOTEntityQuentynQorgyle.class, new GOTRenderLegendaryNPC("quentyn_qorgyle"));
		getRenders().put(GOTEntityQyburn.class, new GOTRenderLegendaryNPC("qyburn"));
		getRenders().put(GOTEntityRamsayBolton.class, new GOTRenderLegendaryNPC("ramsay_bolton"));
		getRenders().put(GOTEntityRazdalMoEraz.class, new GOTRenderLegendaryNPC("razdal_mo_eraz"));
		getRenders().put(GOTEntityRenlyBaratheon.class, new GOTRenderLegendaryNPC("renly_baratheon"));
		getRenders().put(GOTEntityRickonStark.class, new GOTRenderLegendaryNPC("rickon_stark", 0.65f));
		getRenders().put(GOTEntityRobinArryn.class, new GOTRenderLegendaryNPC("robin_arryn", 0.75f));
		getRenders().put(GOTEntityRodrikCassel.class, new GOTRenderLegendaryNPC("rodrik_cassel"));
		getRenders().put(GOTEntityRodrikHarlaw.class, new GOTRenderLegendaryNPC("rodrik_harlaw"));
		getRenders().put(GOTEntityRodrikRyswell.class, new GOTRenderLegendaryNPC("rodrik_ryswell"));
		getRenders().put(GOTEntitySalladhorSaan.class, new GOTRenderLegendaryNPC("salladhor_saan"));
		getRenders().put(GOTEntitySansaStark.class, new GOTRenderLegendaryNPC("sansa_stark"));
		getRenders().put(GOTEntitySebastonFarman.class, new GOTRenderLegendaryNPC("sebaston_farman"));
		getRenders().put(GOTEntitySelwynTarth.class, new GOTRenderLegendaryNPC("selwyn_tarth"));
		getRenders().put(GOTEntitySelyseBaratheon.class, new GOTRenderLegendaryNPC("selyse_baratheon"));
		getRenders().put(GOTEntityShae.class, new GOTRenderLegendaryNPC("shae"));
		getRenders().put(GOTEntityShireenBaratheon.class, new GOTRenderLegendaryNPC("shireen_baratheon", 0.75f));
		getRenders().put(GOTEntityStannisBaratheon.class, new GOTRenderLegendaryNPC("stannis_baratheon"));
		getRenders().put(GOTEntitySymondTempleton.class, new GOTRenderLegendaryNPC("symond_templeton"));
		getRenders().put(GOTEntityThreeEyedRaven.class, new GOTRenderLegendaryNPC("three_eyed_raven"));
		getRenders().put(GOTEntityTobhoMott.class, new GOTRenderLegendaryNPC("tobho_mott"));
		getRenders().put(GOTEntityTommenBaratheon.class, new GOTRenderLegendaryNPC("tommen_baratheon", 0.75f));
		getRenders().put(GOTEntityTrystaneMartell.class, new GOTRenderLegendaryNPC("trystane_martell", 0.9f));
		getRenders().put(GOTEntityTychoNestoris.class, new GOTRenderLegendaryNPC("tycho_nestoris"));
		getRenders().put(GOTEntityTytosBlackwood.class, new GOTRenderLegendaryNPC("tytos_blackwood"));
		getRenders().put(GOTEntityTytosBrax.class, new GOTRenderLegendaryNPC("tytos_brax"));
		getRenders().put(GOTEntityTywinLannister.class, new GOTRenderLegendaryNPC("tywin_lannister"));
		getRenders().put(GOTEntityVargoHoat.class, new GOTRenderLegendaryNPC("vargo_hoat"));
		getRenders().put(GOTEntityVarys.class, new GOTRenderLegendaryNPC("varys"));
		getRenders().put(GOTEntityWillasTyrell.class, new GOTRenderLegendaryNPC("willas_tyrell"));
		getRenders().put(GOTEntityWilliamMooton.class, new GOTRenderLegendaryNPC("william_mooton"));
		getRenders().put(GOTEntityYgritte.class, new GOTRenderLegendaryNPC("ygritte"));
		getRenders().put(GOTEntityYohnRoyce.class, new GOTRenderLegendaryNPC("yohn_royce"));
		getRenders().put(GOTEntityYoren.class, new GOTRenderLegendaryNPC("yoren"));
		getRenders().put(GOTEntityYoungGriff.class, new GOTRenderLegendaryNPC("young_griff", 0.9f));
		getRenders().put(GOTEntityAlliserThorne.class, new GOTRenderLegendaryNPCLayered("alliser_thorne"));
		getRenders().put(GOTEntityBalonGreyjoy.class, new GOTRenderLegendaryNPCLayered("balon_greyjoy"));
		getRenders().put(GOTEntityBenedarBelmore.class, new GOTRenderLegendaryNPCLayered("benedar_belmore"));
		getRenders().put(GOTEntityBenjenStark.class, new GOTRenderLegendaryNPCLayered("benjen_stark"));
		getRenders().put(GOTEntityBericDondarrion.class, new GOTRenderLegendaryNPCLayered("beric_dondarrion"));
		getRenders().put(GOTEntityBrienneTarth.class, new GOTRenderLegendaryNPCLayered("brienne_tarth", 1.2f));
		getRenders().put(GOTEntityBryndenTully.class, new GOTRenderLegendaryNPCLayered("brynden_tully"));
		getRenders().put(GOTEntityBuGai.class, new GOTRenderLegendaryNPCLayered("bu_gai"));
		getRenders().put(GOTEntityCotterPyke.class, new GOTRenderLegendaryNPCLayered("cotter_pyke"));
		getRenders().put(GOTEntityCraster.class, new GOTRenderLegendaryNPCLayered("craster"));
		getRenders().put(GOTEntityDavosSeaworth.class, new GOTRenderLegendaryNPCLayered("davos_seaworth"));
		getRenders().put(GOTEntityDenysMallister.class, new GOTRenderLegendaryNPCLayered("denys_mallister"));
		getRenders().put(GOTEntityEdd.class, new GOTRenderLegendaryNPCLayered("edd"));
		getRenders().put(GOTEntityEdmureTully.class, new GOTRenderLegendaryNPCLayered("edmure_tully"));
		getRenders().put(GOTEntityEuronGreyjoy.class, new GOTRenderLegendaryNPCLayered("euron_greyjoy"));
		getRenders().put(GOTEntityHarryStrickland.class, new GOTRenderLegendaryNPCLayered("harry_strickland"));
		getRenders().put(GOTEntityHighSepton.class, new GOTRenderLegendaryNPCLayered("high_septon"));
		getRenders().put(GOTEntityHotPie.class, new GOTRenderLegendaryNPCLayered("hot_pie", 0.9f));
		getRenders().put(GOTEntityHowlandReed.class, new GOTRenderLegendaryNPCLayered("howland_reed"));
		getRenders().put(GOTEntityIllyrioMopatis.class, new GOTRenderLegendaryNPCLayered("illyrio_mopatis"));
		getRenders().put(GOTEntityJaimeLannister.class, new GOTRenderLegendaryNPCLayered("jaime_lannister"));
		getRenders().put(GOTEntityJeorMormont.class, new GOTRenderLegendaryNPCLayered("jeor_mormont"));
		getRenders().put(GOTEntityJoffreyBaratheon.class, new GOTRenderLegendaryNPCLayered("joffrey_baratheon", 0.9f));
		getRenders().put(GOTEntityJohnUmber.class, new GOTRenderLegendaryNPCLayered("john_umber", 1.2f));
		getRenders().put(GOTEntityJonSnow.Stage1.class, new GOTRenderLegendaryNPCLayered("jon_snow"));
		getRenders().put(GOTEntityJonSnow.Stage2.class, new GOTRenderLegendaryNPCLayered("jon_snow_north"));
		getRenders().put(GOTEntityKraznysMoNakloz.class, new GOTRenderLegendaryNPCLayered("kraznys_mo_nakloz"));
		getRenders().put(GOTEntityMaceTyrell.class, new GOTRenderLegendaryNPCLayered("mace_tyrell"));
		getRenders().put(GOTEntityMaegeMormont.class, new GOTRenderLegendaryNPCLayered("maege_mormont"));
		getRenders().put(GOTEntityManceRayder.class, new GOTRenderLegendaryNPCLayered("mance_rayder"));
		getRenders().put(GOTEntityMatthosSeaworth.class, new GOTRenderLegendaryNPCLayered("matthos_seaworth"));
		getRenders().put(GOTEntityMoqorro.class, new GOTRenderLegendaryNPCLayered("moqorro"));
		getRenders().put(GOTEntityOsha.class, new GOTRenderLegendaryNPCLayered("osha"));
		getRenders().put(GOTEntityRandyllTarly.class, new GOTRenderLegendaryNPCLayered("randyll_tarly"));
		getRenders().put(GOTEntityRickardKarstark.class, new GOTRenderLegendaryNPCLayered("rickard_karstark"));
		getRenders().put(GOTEntityRobbStark.class, new GOTRenderLegendaryNPCLayered("robb_stark"));
		getRenders().put(GOTEntityRooseBolton.class, new GOTRenderLegendaryNPCLayered("roose_bolton"));
		getRenders().put(GOTEntitySamwellTarly.class, new GOTRenderLegendaryNPCLayered("samwell_tarly"));
		getRenders().put(GOTEntitySandorClegane.class, new GOTRenderLegendaryNPCLayered("sandor_clegane", 1.2f));
		getRenders().put(GOTEntityThoros.class, new GOTRenderLegendaryNPCLayered("thoros"));
		getRenders().put(GOTEntityTormund.class, new GOTRenderLegendaryNPCLayered("tormund"));
		getRenders().put(GOTEntityVictarionGreyjoy.class, new GOTRenderLegendaryNPCLayered("victarion_greyjoy", true));
		getRenders().put(GOTEntityWalderFrey.class, new GOTRenderLegendaryNPCLayered("walder_frey"));
		getRenders().put(GOTEntityWymanManderly.class, new GOTRenderLegendaryNPCLayered("wyman_manderly"));
		getRenders().put(GOTEntityXaroXhoanDaxos.class, new GOTRenderLegendaryNPCLayered("xaro_xhoan_daxos"));
		getRenders().put(GOTEntityYaraGreyjoy.class, new GOTRenderLegendaryNPCLayered("yara_greyjoy"));
		getRenders().put(GOTEntityThief.class, new GOTRenderFactionNPCMonofolder("westeros/unreliable"));
		getRenders().put(GOTEntityThiefEssos.class, new GOTRenderFactionNPCMonofolder("essos/unreliable"));
		getRenders().put(GOTEntityBandit.class, new GOTRenderFactionNPCMonofolder("westeros/unreliable"));
		getRenders().put(GOTEntityBanditEssos.class, new GOTRenderFactionNPCMonofolder("essos/unreliable"));
		getRenders().put(GOTEntityScrapTrader.class, new GOTRenderFactionNPCMonofolder("westeros/unreliable"));
		getRenders().put(GOTEntityScrapTraderEssos.class, new GOTRenderFactionNPCMonofolder("essos/unreliable"));
		getRenders().put(GOTEntityGhiscarUnsullied.class, new GOTRenderFactionNPCMonofolder("essos/unsullied"));
		getRenders().put(GOTEntityMaester.class, new GOTRenderFactionNPCMonofolder("westeros/maester"));
		getRenders().put(GOTEntityQohorUnsullied.class, new GOTRenderFactionNPCMonofolder("essos/unsullied"));
		getRenders().put(GOTEntityStoneman.class, new GOTRenderFactionNPCMonofolder("essos/stone"));
		getRenders().put(GOTEntityThennBerserker.class, new GOTRenderFactionNPCMonofolder("westeros/thenn/male", 1.1f));
		getRenders().put(GOTEntityProstitute.class, new GOTRenderProstitute());
		getRenders().put(GOTEntityAsshaiAlchemist.class, new GOTRenderFactionNPCMonotexture("essos/alchemist"));
		getRenders().put(GOTEntityAsshaiShadowbinder.class, new GOTRenderFactionNPCMonotexture("essos/alchemist"));
		getRenders().put(GOTEntityCrownlandsAlchemist.class, new GOTRenderFactionNPCMonotexture("westeros/alchemist"));
		getRenders().put(GOTEntityQarthWarlock.class, new GOTRenderFactionNPCMonotexture("essos/pree"));
		getRenders().put(GOTEntityWhiteWalker.class, new GOTRenderFactionNPCMonotexture("westeros/ice/walker"));
		getRenders().put(EntityPotion.class, new RenderSnowball(Items.potionitem, 16384));
		getRenders().put(GOTEntityAlignmentBonus.class, new GOTRenderAlignmentBonus());
		getRenders().put(GOTEntityArrowPoisoned.class, new GOTRenderArrowPoisoned());
		getRenders().put(GOTEntityArrowFire.class, new GOTRenderArrowFire());
		getRenders().put(GOTEntityBison.class, new GOTRenderBison());
		getRenders().put(GOTEntityBanner.class, new GOTRenderBanner());
		getRenders().put(GOTEntityBannerWall.class, new GOTRenderBannerWall());
		getRenders().put(GOTEntityBarrel.class, new GOTRenderBarrel());
		getRenders().put(GOTEntityBarrowWight.class, new GOTRenderBarrowWight());
		getRenders().put(GOTEntityBear.class, new GOTRenderBear());
		getRenders().put(GOTEntityBearRug.class, new GOTRenderBearRug());
		getRenders().put(GOTEntityBird.class, new GOTRenderBird());
		getRenders().put(GOTEntityBomb.class, new GOTRenderBomb());
		getRenders().put(GOTEntityButterfly.class, new GOTRenderButterfly());
		getRenders().put(GOTEntityCamel.class, new GOTRenderCamel());
		getRenders().put(GOTEntityCargocart.class, new GOTRenderCargocart());
		getRenders().put(GOTEntityConker.class, new RenderSnowball(GOTRegistry.chestnut));
		getRenders().put(GOTEntityCrocodile.class, new GOTRenderCrocodile());
		getRenders().put(GOTEntityCrossbowBolt.class, new GOTRenderCrossbowBolt());
		getRenders().put(GOTEntityDart.class, new GOTRenderDart());
		getRenders().put(GOTEntityDeer.class, new GOTRenderDeer());
		getRenders().put(GOTEntityDikDik.class, new GOTRenderDikDik());
		getRenders().put(GOTEntityDirewolf.class, new GOTRenderDirewolf());
		getRenders().put(GOTEntityDragon.class, new GOTRenderDragon());
		getRenders().put(GOTEntityElephant.class, new GOTRenderElephant());
		getRenders().put(GOTEntityFallingFireJar.class, new GOTRenderFallingFireJar());
		getRenders().put(GOTEntityFallingTreasure.class, new GOTRenderFallingCoinPile());
		getRenders().put(GOTEntityFirePot.class, new RenderSnowball(GOTRegistry.firePot));
		getRenders().put(GOTEntityFish.class, new GOTRenderFish());
		getRenders().put(GOTEntityFlamingo.class, new GOTRenderFlamingo());
		getRenders().put(GOTEntityGemsbok.class, new GOTRenderGemsbok());
		getRenders().put(GOTEntityGiant.class, new GOTRenderGiant("giant"));
		getRenders().put(GOTEntityGiraffe.class, new GOTRenderGiraffe());
		getRenders().put(GOTEntityGiraffeRug.class, new GOTRenderGiraffeRug());
		getRenders().put(GOTEntityGregorClegane.Alive.class, new GOTRenderGregorClegane.Alive());
		getRenders().put(GOTEntityGregorClegane.Dead.class, new GOTRenderGregorClegane.Dead());
		getRenders().put(GOTEntityHorse.class, new GOTRenderHorse());
		getRenders().put(GOTEntityIceSpider.class, new GOTRenderIceSpider());
		getRenders().put(GOTEntityInvasionSpawner.class, new GOTRenderInvasionSpawner());
		getRenders().put(GOTEntityWhiteBison.class, new GOTRenderWhiteBison());
		getRenders().put(GOTEntityLancelLannister.Normal.class, new GOTRenderLancelLannister.Normal());
		getRenders().put(GOTEntityLancelLannister.Religious.class, new GOTRenderLancelLannister.Religious());
		getRenders().put(GOTEntityLingeringEffect.class, new GOTRenderLingeringEffect());
		getRenders().put(GOTEntityLingeringPotion.class, new GOTRenderLingeringPotion());
		getRenders().put(GOTEntityLionBase.class, new GOTRenderLion());
		getRenders().put(GOTEntityLionRug.class, new GOTRenderLionRug());
		getRenders().put(GOTEntityMammoth.class, new GOTRenderMammoth());
		getRenders().put(GOTEntityManticore.class, new GOTRenderManticore());
		getRenders().put(GOTEntityMidges.class, new GOTRenderMidges());
		getRenders().put(GOTEntityMossovyWerewolf.class, new GOTRenderMossovyWerewolf());
		getRenders().put(GOTEntityMysteryWeb.class, new RenderSnowball(GOTRegistry.mysteryWeb));
		getRenders().put(GOTEntityNPCRespawner.class, new GOTRenderNPCRespawner());
		getRenders().put(GOTEntityPebble.class, new RenderSnowball(GOTRegistry.pebble));
		getRenders().put(GOTEntityPlate.class, new GOTRenderPlate());
		getRenders().put(GOTEntityPlowcart.class, new GOTRenderPlowcart());
		getRenders().put(GOTEntityPortal.class, new GOTRenderPortal());
		getRenders().put(GOTEntityRabbit.class, new GOTRenderRabbit());
		getRenders().put(GOTEntityRedScorpion.class, new GOTRenderRedScorpion());
		getRenders().put(GOTEntityRhino.class, new GOTRenderRhino());
		getRenders().put(GOTEntityScorpionBig.class, new GOTRenderScorpion());
		getRenders().put(GOTEntitySmokeRing.class, new GOTRenderSmokeRing());
		getRenders().put(GOTEntitySnowBear.class, new GOTRenderSnowBear());
		getRenders().put(GOTEntitySpear.class, new GOTRenderSpear());
		getRenders().put(GOTEntitySwan.class, new GOTRenderSwan());
		getRenders().put(GOTEntityTermite.class, new GOTRenderTermite());
		getRenders().put(GOTEntityTheonGreyjoy.Normal.class, new GOTRenderTheonGreyjoy.Normal());
		getRenders().put(GOTEntityTheonGreyjoy.Tormented.class, new GOTRenderTheonGreyjoy.Tormented());
		getRenders().put(GOTEntityThrowingAxe.class, new GOTRenderThrowingAxe());
		getRenders().put(GOTEntityThrownRock.class, new GOTRenderThrownRock());
		getRenders().put(GOTEntityThrownTermite.class, new RenderSnowball(GOTRegistry.termite));
		getRenders().put(GOTEntityTraderRespawn.class, new GOTRenderTraderRespawn());
		getRenders().put(GOTEntityTyrionLannister.class, new GOTRenderTyrionLannister());
		getRenders().put(GOTEntityUlthosSpider.class, new GOTRenderGiantSpider());
		getRenders().put(GOTEntityShadowcat.class, new GOTRenderShadowcat());
		getRenders().put(GOTEntityWalrus.class, new GOTRenderWalrus());
		getRenders().put(GOTEntityWhiteOryx.class, new GOTRenderWhiteOryx());
		getRenders().put(GOTEntityWightGiant.class, new GOTRenderGiant("ice"));
		getRenders().put(GOTEntityBoar.class, new GOTRenderBoar());
		getRenders().put(GOTEntityWoolyRhino.class, new GOTRenderWoolyRhino());
		getRenders().put(GOTEntityWyvern.class, new GOTRenderWyvern());
		getRenders().put(GOTEntityZebra.class, new GOTRenderZebra());
	}

	public static void setRenders(Map<Class, Render> renders) {
		GOTRender.renders = renders;
	}
}
