package got.common.database;

import com.google.common.base.CaseFormat;
import cpw.mods.fml.common.registry.GameRegistry;
import got.common.block.GOTItemBlockWeaponRack;
import got.common.block.GOTItemPlantableBlock;
import got.common.block.brick.*;
import got.common.block.leaves.*;
import got.common.block.other.*;
import got.common.block.pillar.GOTBlockPillar1;
import got.common.block.pillar.GOTBlockPillar2;
import got.common.block.planks.*;
import got.common.block.sapling.*;
import got.common.block.slab.*;
import got.common.block.table.*;
import got.common.block.torch.GOTBlockAsshaiTorch;
import got.common.block.torch.GOTBlockDoubleTorch;
import got.common.block.torch.GOTBlockUlthosTorch;
import got.common.block.wall.*;
import got.common.block.wbeam.*;
import got.common.block.wood.*;
import got.common.block.wslab.*;
import got.common.item.other.*;
import got.common.item.weapon.GOTItemBomb;
import got.common.tileentity.GOTTileEntitySignCarved;
import got.common.tileentity.GOTTileEntitySignCarvedValyrian;
import got.common.util.GOTEnumDyeColor;
import net.minecraft.block.Block;
import net.minecraft.block.BlockPressurePlate;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemLeaves;

import java.util.EnumMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class GOTBlocks {
	public static final Set<Block> CONTENT = new HashSet<>();

	public static Map<GOTEnumDyeColor, GOTBlockConcretePowder> concretePowder = new EnumMap<>(GOTEnumDyeColor.class);
	public static Map<GOTEnumDyeColor, GOTBlockConcrete> concrete = new EnumMap<>(GOTEnumDyeColor.class);

	public static Block aleHornBlock;
	public static Block aleHornGoldBlock;
	public static Block alloyForge;
	public static Block appleCrumble;
	public static Block aridGrass;
	public static Block armorStand;
	public static Block asshaiBars;
	public static Block asshaiDirt;
	public static Block asshaiFlower;
	public static Block asshaiGrass;
	public static Block asshaiMoss;
	public static Block asshaiThorn;
	public static Block asshaiTorch;
	public static Block bananaBlock;
	public static Block bananaCake;
	public static Block bank;
	public static Block barrel;
	public static Block barrier;
	public static Block basaltGravel;
	public static Block beacon;
	public static Block berryBush;
	public static Block berryPie;
	public static Block birdCage;
	public static Block birdCageWood;
	public static Block blackroot;
	public static Block blockGem;
	public static Block blockMetal1;
	public static Block blockMetal2;
	public static Block bluebell;
	public static Block bomb;
	public static Block boneBlock;
	public static Block bookshelfStorage;
	public static Block brick1;
	public static Block brick2;
	public static Block brick3;
	public static Block brick4;
	public static Block brick5;
	public static Block brick6;
	public static Block brickIce;
	public static Block bronzeBars;
	public static Block butterflyJar;
	public static Block buttonAndesite;
	public static Block buttonBasalt;
	public static Block buttonChalk;
	public static Block buttonDiorite;
	public static Block buttonGranite;
	public static Block buttonLabradorite;
	public static Block buttonRhyolite;
	public static Block ceramicMugBlock;
	public static Block ceramicPlateBlock;
	public static Block chain;
	public static Block chandelier;
	public static Block cherryPie;
	public static Block chestBasket;
	public static Block chestEssos;
	public static Block chestStone;
	public static Block clayTile;
	public static Block clayTileDyed;
	public static Block clover;
	public static Block cobblebrick;
	public static Block commandTable;
	public static Block coralReef;
	public static Block cornStalk;
	public static Block cucumberCrop;
	public static Block cucumberPlant;
	public static Block dateBlock;
	public static Block daub;
	public static Block deadMarshPlant;
	public static Block dirtPath;
	public static Block doorAcacia;
	public static Block doorAlmond;
	public static Block doorApple;
	public static Block doorAramant;
	public static Block doorAspen;
	public static Block doorBanana;
	public static Block doorBaobab;
	public static Block doorBeech;
	public static Block doorBirch;
	public static Block doorCatalpa;
	public static Block doorCedar;
	public static Block doorCharred;
	public static Block doorCherry;
	public static Block doorChestnut;
	public static Block doorCypress;
	public static Block doorDarkOak;
	public static Block doorDatePalm;
	public static Block doorDragon;
	public static Block doorFir;
	public static Block doorFotinia;
	public static Block doorGreenOak;
	public static Block doorHolly;
	public static Block doorIbbinia;
	public static Block doorJungle;
	public static Block doorKanuka;
	public static Block doorLarch;
	public static Block doorLemon;
	public static Block doorLime;
	public static Block doorMahogany;
	public static Block doorMango;
	public static Block doorMangrove;
	public static Block doorMaple;
	public static Block doorOlive;
	public static Block doorOrange;
	public static Block doorPalm;
	public static Block doorPear;
	public static Block doorPine;
	public static Block doorPlum;
	public static Block doorPomegranate;
	public static Block doorRedwood;
	public static Block doorRotten;
	public static Block doorSpruce;
	public static Block doorUlthos;
	public static Block doorWeirwood;
	public static Block doorWillow;
	public static Block doubleFlower;
	public static Block driedReeds;
	public static Block essosFlower;
	public static Block fallenLeaves1;
	public static Block fallenLeaves2;
	public static Block fallenLeaves3;
	public static Block fallenLeaves4;
	public static Block fence2;
	public static Block fence3;
	public static Block fence;
	public static Block fenceGateAcacia;
	public static Block fenceGateAlmond;
	public static Block fenceGateApple;
	public static Block fenceGateAramant;
	public static Block fenceGateAspen;
	public static Block fenceGateBanana;
	public static Block fenceGateBaobab;
	public static Block fenceGateBeech;
	public static Block fenceGateBirch;
	public static Block fenceGateCatalpa;
	public static Block fenceGateCedar;
	public static Block fenceGateCharred;
	public static Block fenceGateCherry;
	public static Block fenceGateChestnut;
	public static Block fenceGateCypress;
	public static Block fenceGateDarkOak;
	public static Block fenceGateDatePalm;
	public static Block fenceGateDragon;
	public static Block fenceGateFir;
	public static Block fenceGateFotinia;
	public static Block fenceGateGreenOak;
	public static Block fenceGateHolly;
	public static Block fenceGateIbbinia;
	public static Block fenceGateJungle;
	public static Block fenceGateKanuka;
	public static Block fenceGateLarch;
	public static Block fenceGateLemon;
	public static Block fenceGateLime;
	public static Block fenceGateMahogany;
	public static Block fenceGateMango;
	public static Block fenceGateMangrove;
	public static Block fenceGateMaple;
	public static Block fenceGateOlive;
	public static Block fenceGateOrange;
	public static Block fenceGatePalm;
	public static Block fenceGatePear;
	public static Block fenceGatePine;
	public static Block fenceGatePlum;
	public static Block fenceGatePomegranate;
	public static Block fenceGateRedwood;
	public static Block fenceGateRotten;
	public static Block fenceGateSpruce;
	public static Block fenceGateUlthos;
	public static Block fenceGateWeirwood;
	public static Block fenceGateWillow;
	public static Block fenceRotten;
	public static Block flaxCrop;
	public static Block flaxPlant;
	public static Block flowerPot;
	public static Block fruitLeaves;
	public static Block fruitSapling;
	public static Block fruitWood;
	public static Block furBed;
	public static Block fuse;
	public static Block gateBronzeBars;
	public static Block gateEssos;
	public static Block gateGold;
	public static Block gateIbben;
	public static Block gateIronBars;
	public static Block gateSilver;
	public static Block gateSothoryos;
	public static Block gateValyrian;
	public static Block gateWesteros;
	public static Block gateWooden;
	public static Block gateWoodenCross;
	public static Block gateYiTi;
	public static Block glass;
	public static Block glassBottleBlock;
	public static Block glassPane;
	public static Block gobletCopperBlock;
	public static Block gobletGoldBlock;
	public static Block gobletSilverBlock;
	public static Block gobletWoodBlock;
	public static Block goldBars;
	public static Block grapevine;
	public static Block grapevineRed;
	public static Block grapevineWhite;
	public static Block hearth;
	public static Block kebabBlock;
	public static Block kebabStand;
	public static Block kebabStandSand;
	public static Block kelp;
	public static Block leaves1;
	public static Block leaves2;
	public static Block leaves3;
	public static Block leaves4;
	public static Block leaves5;
	public static Block leaves6;
	public static Block leaves7;
	public static Block leaves8;
	public static Block leaves9;
	public static Block leavesSnowy;
	public static Block leekCrop;
	public static Block lemonCake;
	public static Block lettuceCrop;
	public static Block lionBed;
	public static Block marigold;
	public static Block marshLights;
	public static Block marzipanBlock;
	public static Block millstone;
	public static Block mirkVines;
	public static Block mobSpawner;
	public static Block mud;
	public static Block mudFarmland;
	public static Block mudGrass;
	public static Block mugBlock;
	public static Block obsidianGravel;
	public static Block oreCobalt;
	public static Block oreCopper;
	public static Block oreGem;
	public static Block oreGlowstone;
	public static Block oreSalt;
	public static Block oreSaltpeter;
	public static Block oreSilver;
	public static Block oreSulfur;
	public static Block oreTin;
	public static Block oreValyrian;
	public static Block oven;
	public static Block pastry;
	public static Block pillar1;
	public static Block pillar2;
	public static Block pipeweedCrop;
	public static Block pipeweedPlant;
	public static Block planks1;
	public static Block planks2;
	public static Block planks3;
	public static Block planksRotten;
	public static Block plantain;
	public static Block plateBlock;
	public static Block pressurePlateAndesite;
	public static Block pressurePlateBasalt;
	public static Block pressurePlateChalk;
	public static Block pressurePlateDiorite;
	public static Block pressurePlateGranite;
	public static Block pressurePlateLabradorite;
	public static Block pressurePlateRhyolite;
	public static Block quagmire;
	public static Block quicksand;
	public static Block redBrick;
	public static Block redClay;
	public static Block redSandstone;
	public static Block reedBars;
	public static Block reeds;
	public static Block ricePlant;
	public static Block rock;
	public static Block rope;
	public static Block rottenLog;
	public static Block rottenSlabDouble;
	public static Block rottenSlabSingle;
	public static Block sapling1;
	public static Block sapling2;
	public static Block sapling3;
	public static Block sapling4;
	public static Block sapling5;
	public static Block sapling6;
	public static Block sapling7;
	public static Block sapling8;
	public static Block sapling9;
	public static Block sarbacaneTrap;
	public static Block sarbacaneTrapGold;
	public static Block sarbacaneTrapObsidian;
	public static Block scorchedSlabDouble;
	public static Block scorchedSlabSingle;
	public static Block scorchedStone;
	public static Block scorchedWall;
	public static Block signCarved;
	public static Block signCarvedGlowing;
	public static Block silverBars;
	public static Block skullCupBlock;
	public static Block slabBoneDouble;
	public static Block slabBoneSingle;
	public static Block slabClayTileDouble;
	public static Block slabClayTileDyedDouble1;
	public static Block slabClayTileDyedDouble2;
	public static Block slabClayTileDyedSingle1;
	public static Block slabClayTileDyedSingle2;
	public static Block slabClayTileSingle;
	public static Block slabDouble10;
	public static Block slabDouble11;
	public static Block slabDouble12;
	public static Block slabDouble1;
	public static Block slabDouble2;
	public static Block slabDouble3;
	public static Block slabDouble4;
	public static Block slabDouble5;
	public static Block slabDouble6;
	public static Block slabDouble7;
	public static Block slabDouble8;
	public static Block slabDouble9;
	public static Block slabDoubleDirt;
	public static Block slabDoubleGravel;
	public static Block slabDoubleSand;
	public static Block slabDoubleThatch;
	public static Block slabDoubleV;
	public static Block slabSingle10;
	public static Block slabSingle11;
	public static Block slabSingle12;
	public static Block slabSingle1;
	public static Block slabSingle2;
	public static Block slabSingle3;
	public static Block slabSingle4;
	public static Block slabSingle5;
	public static Block slabSingle6;
	public static Block slabSingle7;
	public static Block slabSingle8;
	public static Block slabSingle9;
	public static Block slabSingleDirt;
	public static Block slabSingleGravel;
	public static Block slabSingleSand;
	public static Block slabSingleThatch;
	public static Block slabSingleV;
	public static Block smoothStone;
	public static Block smoothStoneV;
	public static Block sothoryosDoubleTorch;
	public static Block spawnerChest;
	public static Block spawnerChestAncientEssos;
	public static Block spawnerChestStone;
	public static Block stainedGlass;
	public static Block stainedGlassPane;
	public static Block stairsAlmond;
	public static Block stairsAndesite;
	public static Block stairsAndesiteBrick;
	public static Block stairsAndesiteBrickCracked;
	public static Block stairsAndesiteBrickMossy;
	public static Block stairsApple;
	public static Block stairsAramant;
	public static Block stairsAspen;
	public static Block stairsBanana;
	public static Block stairsBaobab;
	public static Block stairsBasalt;
	public static Block stairsBasaltBrick;
	public static Block stairsBasaltBrickCracked;
	public static Block stairsBasaltWesterosBrick;
	public static Block stairsBeech;
	public static Block stairsBone;
	public static Block stairsBrickCracked;
	public static Block stairsBrickMossy;
	public static Block stairsCatalpa;
	public static Block stairsCedar;
	public static Block stairsChalk;
	public static Block stairsChalkBrick;
	public static Block stairsCharred;
	public static Block stairsCherry;
	public static Block stairsChestnut;
	public static Block stairsClayTile;
	public static Block stairsClayTileDyedBlack;
	public static Block stairsClayTileDyedBlue;
	public static Block stairsClayTileDyedBrown;
	public static Block stairsClayTileDyedCyan;
	public static Block stairsClayTileDyedGray;
	public static Block stairsClayTileDyedGreen;
	public static Block stairsClayTileDyedLightBlue;
	public static Block stairsClayTileDyedLightGray;
	public static Block stairsClayTileDyedLime;
	public static Block stairsClayTileDyedMagenta;
	public static Block stairsClayTileDyedOrange;
	public static Block stairsClayTileDyedPink;
	public static Block stairsClayTileDyedPurple;
	public static Block stairsClayTileDyedRed;
	public static Block stairsClayTileDyedWhite;
	public static Block stairsClayTileDyedYellow;
	public static Block stairsCobblestoneMossy;
	public static Block stairsCypress;
	public static Block stairsDatePalm;
	public static Block stairsDiorite;
	public static Block stairsDioriteBrick;
	public static Block stairsDragon;
	public static Block stairsFir;
	public static Block stairsFotinia;
	public static Block stairsGranite;
	public static Block stairsGraniteBrick;
	public static Block stairsGreenOak;
	public static Block stairsHolly;
	public static Block stairsIbbinia;
	public static Block stairsKanuka;
	public static Block stairsLabradorite;
	public static Block stairsLabradoriteBrick;
	public static Block stairsLabradoriteBrickCracked;
	public static Block stairsLabradoriteBrickMossy;
	public static Block stairsLarch;
	public static Block stairsLemon;
	public static Block stairsLhazarBrick;
	public static Block stairsLime;
	public static Block stairsMahogany;
	public static Block stairsMango;
	public static Block stairsMangrove;
	public static Block stairsMaple;
	public static Block stairsMudBrick;
	public static Block stairsOlive;
	public static Block stairsOrange;
	public static Block stairsPalm;
	public static Block stairsPear;
	public static Block stairsPine;
	public static Block stairsPlum;
	public static Block stairsPomegranate;
	public static Block stairsRedSandstone;
	public static Block stairsRedwood;
	public static Block stairsReed;
	public static Block stairsRhyolite;
	public static Block stairsRhyoliteBrick;
	public static Block stairsRotten;
	public static Block stairsSandstoneBrick;
	public static Block stairsSandstoneBrickCracked;
	public static Block stairsSandstoneBrickRed;
	public static Block stairsSandstoneBrickRedCracked;
	public static Block stairsScorchedStone;
	public static Block stairsSothoryosBrick;
	public static Block stairsSothoryosBrickCracked;
	public static Block stairsSothoryosBrickGold;
	public static Block stairsSothoryosBrickMossy;
	public static Block stairsSothoryosBrickObsidian;
	public static Block stairsStone;
	public static Block stairsStoneBrickCracked;
	public static Block stairsStoneBrickMossy;
	public static Block stairsThatch;
	public static Block stairsUlthos;
	public static Block stairsWeirwood;
	public static Block stairsWhiteSandstone;
	public static Block stairsWillow;
	public static Block stairsYiTiBrick;
	public static Block stairsYiTiBrickCracked;
	public static Block stairsYiTiBrickFlowers;
	public static Block stairsYiTiBrickMossy;
	public static Block stairsYiTiBrickRed;
	public static Block stalactite;
	public static Block stalactiteIce;
	public static Block stalactiteObsidian;
	public static Block strawBed;
	public static Block tableArryn;
	public static Block tableAsshai;
	public static Block tableBraavos;
	public static Block tableCrownlands;
	public static Block tableDorne;
	public static Block tableDothraki;
	public static Block tableDragonstone;
	public static Block tableGhiscar;
	public static Block tableGift;
	public static Block tableHillTribes;
	public static Block tableIbben;
	public static Block tableIronborn;
	public static Block tableJogos;
	public static Block tableLhazar;
	public static Block tableLorath;
	public static Block tableLys;
	public static Block tableMossovy;
	public static Block tableMyr;
	public static Block tableNorth;
	public static Block tableNorvos;
	public static Block tablePentos;
	public static Block tableQarth;
	public static Block tableQohor;
	public static Block tableReach;
	public static Block tableRiverlands;
	public static Block tableSothoryos;
	public static Block tableStormlands;
	public static Block tableSummer;
	public static Block tableTyrosh;
	public static Block tableVolantis;
	public static Block tableWesterlands;
	public static Block tableWildling;
	public static Block tableYiTi;
	public static Block tallGrass;
	public static Block termiteMound;
	public static Block thatch;
	public static Block thatchFloor;
	public static Block trapdoorAcacia;
	public static Block trapdoorAlmond;
	public static Block trapdoorApple;
	public static Block trapdoorAramant;
	public static Block trapdoorAspen;
	public static Block trapdoorBanana;
	public static Block trapdoorBaobab;
	public static Block trapdoorBeech;
	public static Block trapdoorBirch;
	public static Block trapdoorCatalpa;
	public static Block trapdoorCedar;
	public static Block trapdoorCharred;
	public static Block trapdoorCherry;
	public static Block trapdoorChestnut;
	public static Block trapdoorCypress;
	public static Block trapdoorDarkOak;
	public static Block trapdoorDatePalm;
	public static Block trapdoorDragon;
	public static Block trapdoorFir;
	public static Block trapdoorFotinia;
	public static Block trapdoorGreenOak;
	public static Block trapdoorHolly;
	public static Block trapdoorIbbinia;
	public static Block trapdoorJungle;
	public static Block trapdoorKanuka;
	public static Block trapdoorLarch;
	public static Block trapdoorLemon;
	public static Block trapdoorLime;
	public static Block trapdoorMahogany;
	public static Block trapdoorMango;
	public static Block trapdoorMangrove;
	public static Block trapdoorMaple;
	public static Block trapdoorOlive;
	public static Block trapdoorOrange;
	public static Block trapdoorPalm;
	public static Block trapdoorPear;
	public static Block trapdoorPine;
	public static Block trapdoorPlum;
	public static Block trapdoorPomegranate;
	public static Block trapdoorRedwood;
	public static Block trapdoorRotten;
	public static Block trapdoorSpruce;
	public static Block trapdoorUlthos;
	public static Block trapdoorWeirwood;
	public static Block trapdoorWillow;
	public static Block treasureCopper;
	public static Block treasureGold;
	public static Block treasureSilver;
	public static Block turnipCrop;
	public static Block ulthosBars;
	public static Block ulthosTorch;
	public static Block unsmeltery;
	public static Block valyrianBars;
	public static Block wallBone;
	public static Block wallClayTile;
	public static Block wallClayTileDyed;
	public static Block wallStone1;
	public static Block wallStone2;
	public static Block wallStone3;
	public static Block wallStone4;
	public static Block wallStoneV;
	public static Block wasteBlock;
	public static Block weaponRack;
	public static Block whiteSand;
	public static Block whiteSandstone;
	public static Block wildFire;
	public static Block wildFireJar;
	public static Block willowVines;
	public static Block wineGlassBlock;
	public static Block wood1;
	public static Block wood2;
	public static Block wood3;
	public static Block wood4;
	public static Block wood5;
	public static Block wood6;
	public static Block wood7;
	public static Block wood8;
	public static Block wood9;
	public static Block woodBeam1;
	public static Block woodBeam2;
	public static Block woodBeam3;
	public static Block woodBeam4;
	public static Block woodBeam5;
	public static Block woodBeam6;
	public static Block woodBeam7;
	public static Block woodBeam8;
	public static Block woodBeam9;
	public static Block woodBeamFruit;
	public static Block woodBeamRotten;
	public static Block woodBeamS;
	public static Block woodBeamV1;
	public static Block woodBeamV2;
	public static Block woodPlateBlock;
	public static Block woodSlabDouble1;
	public static Block woodSlabDouble2;
	public static Block woodSlabDouble3;
	public static Block woodSlabDouble4;
	public static Block woodSlabDouble5;
	public static Block woodSlabSingle1;
	public static Block woodSlabSingle2;
	public static Block woodSlabSingle3;
	public static Block woodSlabSingle4;
	public static Block woodSlabSingle5;
	public static Block yamCrop;
	public static Block yitiFlower;

	public static void assignBlocks() {
		planks1 = new GOTBlockPlanks1();
		planks2 = new GOTBlockPlanks2();
		planks3 = new GOTBlockPlanks3();
		planksRotten = new GOTBlockPlanksRotten();
		thatch = new GOTBlockThatch();
		whiteSandstone = new GOTBlockSandstone();

		aleHornBlock = new GOTBlockAleHorn();
		aleHornGoldBlock = new GOTBlockAleHorn();
		alloyForge = new GOTBlockAlloyForge();
		appleCrumble = new GOTBlockPlaceableFood();
		aridGrass = new GOTBlockGrass().setSandy();
		armorStand = new GOTBlockArmorStand();
		asshaiBars = new GOTBlockBars();
		asshaiDirt = new GOTBlockAsshaiDirt();
		asshaiFlower = new GOTBlockAsshaiFlower();
		asshaiGrass = new GOTBlockAsshaiGrass();
		asshaiMoss = new GOTBlockAsshaiMoss();
		asshaiThorn = new GOTBlockAsshaiThorn();
		asshaiTorch = new GOTBlockAsshaiTorch().setHardness(0.0f).setStepSound(Block.soundTypeWood).setLightLevel(0.875f);
		bananaBlock = new GOTBlockBanana().setHardness(0.0f).setResistance(1.0f).setStepSound(Block.soundTypeWood);
		bananaCake = new GOTBlockPlaceableFood();
		bank = new GOTBlockIronBank();
		barrel = new GOTBlockBarrel();
		barrier = new GOTBlockBarrier();
		basaltGravel = new GOTBlockGravel();
		beacon = new GOTBlockBeacon();
		berryBush = new GOTBlockBerryBush();
		berryPie = new GOTBlockPlaceableFood();
		birdCage = new GOTBlockBirdCage();
		birdCageWood = new GOTBlockBirdCageWood();
		blackroot = new GOTBlockBlackroot();
		blockGem = new GOTBlockGemStorage();
		blockMetal1 = new GOTBlockMetal();
		blockMetal2 = new GOTBlockMetal2();
		bluebell = new GOTBlockFlower();
		bomb = new GOTBlockBomb();
		boneBlock = new GOTBlockBone();
		bookshelfStorage = new GOTBlockBookshelfStorage();
		brick1 = new GOTBlockBrick1();
		brick2 = new GOTBlockBrick2();
		brick3 = new GOTBlockBrick3();
		brick4 = new GOTBlockBrick4();
		brick5 = new GOTBlockBrick5();
		brick6 = new GOTBlockBrick6();
		brickIce = new GOTBlockBrickIce();
		bronzeBars = new GOTBlockBars();
		butterflyJar = new GOTBlockButterflyJar();
		buttonAndesite = new GOTBlockButton(false, "got:rock_andesite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonBasalt = new GOTBlockButton(false, "got:rock_basalt").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonChalk = new GOTBlockButton(false, "got:rock_chalk").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonDiorite = new GOTBlockButton(false, "got:rock_diorite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonGranite = new GOTBlockButton(false, "got:rock_granite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonLabradorite = new GOTBlockButton(false, "got:rock_labradorite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonRhyolite = new GOTBlockButton(false, "got:rock_rhyolite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		ceramicMugBlock = new GOTBlockClayMug();
		ceramicPlateBlock = new GOTBlockPlate().setStepSound(GOTBlockPlate.soundTypePlate);
		chain = new GOTBlockChain();
		chandelier = new GOTBlockChandelier();
		cherryPie = new GOTBlockPlaceableFood();
		chestBasket = new GOTBlockChest(Material.cloth, thatch, 1, "basket").setHardness(0.5f).setStepSound(Block.soundTypeCloth);
		chestEssos = new GOTBlockChest(Material.rock, brick1, 15, "essos").setHardness(3.0f).setStepSound(Block.soundTypeStone);
		chestStone = new GOTBlockChest(Material.rock, Blocks.cobblestone, 0, "stone").setHardness(3.0f).setStepSound(Block.soundTypeStone);
		clayTile = new GOTBlockClayTile();
		clayTileDyed = new GOTBlockClayTileDyed();
		clover = new GOTBlockClover();
		cobblebrick = new GOTBlockCobblebrick();
		commandTable = new GOTBlockCommandTable();
		coralReef = new GOTBlockCoralReef();
		cornStalk = new GOTBlockCorn();
		cucumberCrop = new GOTBlockCucumberCrop();
		cucumberPlant = new GOTBlockFlower().setFlowerBounds(0.2f, 0.0f, 0.2f, 0.8f, 0.8f, 0.8f);
		dateBlock = new GOTBlockDate().setHardness(0.0f).setResistance(1.0f).setStepSound(Block.soundTypeWood);
		daub = new GOTBlockDaub();
		deadMarshPlant = new GOTBlockDeadPlant();
		dirtPath = new GOTBlockDirtPath();
		doorAcacia = new GOTBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorAlmond = new GOTBlockDoor();
		doorApple = new GOTBlockDoor();
		doorAramant = new GOTBlockDoor();
		doorAspen = new GOTBlockDoor();
		doorBanana = new GOTBlockDoor();
		doorBaobab = new GOTBlockDoor();
		doorBeech = new GOTBlockDoor();
		doorBirch = new GOTBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorCatalpa = new GOTBlockDoor();
		doorCedar = new GOTBlockDoor();
		doorCharred = new GOTBlockDoor();
		doorCherry = new GOTBlockDoor();
		doorChestnut = new GOTBlockDoor();
		doorCypress = new GOTBlockDoor();
		doorDarkOak = new GOTBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorDatePalm = new GOTBlockDoor();
		doorDragon = new GOTBlockDoor();
		doorFir = new GOTBlockDoor();
		doorFotinia = new GOTBlockDoor();
		doorGreenOak = new GOTBlockDoor();
		doorHolly = new GOTBlockDoor();
		doorIbbinia = new GOTBlockDoor();
		doorJungle = new GOTBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorKanuka = new GOTBlockDoor();
		doorLarch = new GOTBlockDoor();
		doorLemon = new GOTBlockDoor();
		doorLime = new GOTBlockDoor();
		doorMahogany = new GOTBlockDoor();
		doorMango = new GOTBlockDoor();
		doorMangrove = new GOTBlockDoor();
		doorMaple = new GOTBlockDoor();
		doorOlive = new GOTBlockDoor();
		doorOrange = new GOTBlockDoor();
		doorPalm = new GOTBlockDoor();
		doorPear = new GOTBlockDoor();
		doorPine = new GOTBlockDoor();
		doorPlum = new GOTBlockDoor();
		doorPomegranate = new GOTBlockDoor();
		doorRedwood = new GOTBlockDoor();
		doorRotten = new GOTBlockDoor();
		doorSpruce = new GOTBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorUlthos = new GOTBlockDoor();
		doorWeirwood = new GOTBlockDoor();
		doorWillow = new GOTBlockDoor();
		doubleFlower = new GOTBlockDoubleFlower();
		driedReeds = new GOTBlockReedDry();
		essosFlower = new GOTBlockEssosFlower();
		fallenLeaves1 = new GOTBlockFallenLeaves();
		fallenLeaves2 = new GOTBlockFallenLeaves();
		fallenLeaves3 = new GOTBlockFallenLeaves();
		fallenLeaves4 = new GOTBlockFallenLeaves();
		fence = new GOTBlockFence(planks1);
		fence2 = new GOTBlockFence(planks2);
		fence3 = new GOTBlockFence(planks3);
		fenceGateAcacia = new GOTBlockFenceGate(Blocks.planks, 4).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateAlmond = new GOTBlockFenceGate(planks2, 15);
		fenceGateApple = new GOTBlockFenceGate(planks1, 4);
		fenceGateAramant = new GOTBlockFenceGate(planks1, 8);
		fenceGateAspen = new GOTBlockFenceGate(planks2, 12);
		fenceGateBanana = new GOTBlockFenceGate(planks1, 11);
		fenceGateBaobab = new GOTBlockFenceGate(planks2, 1);
		fenceGateBeech = new GOTBlockFenceGate(planks1, 9);
		fenceGateBirch = new GOTBlockFenceGate(Blocks.planks, 2).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateCatalpa = new GOTBlockFenceGate(planks1, 1);
		fenceGateCedar = new GOTBlockFenceGate(planks2, 2);
		fenceGateCharred = new GOTBlockFenceGate(planks1, 3);
		fenceGateCherry = new GOTBlockFenceGate(planks1, 6);
		fenceGateChestnut = new GOTBlockFenceGate(planks2, 0);
		fenceGateCypress = new GOTBlockFenceGate(planks2, 10);
		fenceGateDarkOak = new GOTBlockFenceGate(Blocks.planks, 5).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateDatePalm = new GOTBlockFenceGate(planks1, 14);
		fenceGateDragon = new GOTBlockFenceGate(planks3, 4);
		fenceGateFir = new GOTBlockFenceGate(planks2, 3);
		fenceGateFotinia = new GOTBlockFenceGate(planks2, 14);
		fenceGateGreenOak = new GOTBlockFenceGate(planks2, 13);
		fenceGateHolly = new GOTBlockFenceGate(planks1, 10);
		fenceGateIbbinia = new GOTBlockFenceGate(planks1, 0);
		fenceGateJungle = new GOTBlockFenceGate(Blocks.planks, 3).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateKanuka = new GOTBlockFenceGate(planks3, 5);
		fenceGateLarch = new GOTBlockFenceGate(planks1, 13);
		fenceGateLemon = new GOTBlockFenceGate(planks2, 5);
		fenceGateLime = new GOTBlockFenceGate(planks2, 7);
		fenceGateMahogany = new GOTBlockFenceGate(planks2, 8);
		fenceGateMango = new GOTBlockFenceGate(planks1, 7);
		fenceGateMangrove = new GOTBlockFenceGate(planks1, 15);
		fenceGateMaple = new GOTBlockFenceGate(planks1, 12);
		fenceGateOlive = new GOTBlockFenceGate(planks2, 11);
		fenceGateOrange = new GOTBlockFenceGate(planks2, 6);
		fenceGatePalm = new GOTBlockFenceGate(planks3, 3);
		fenceGatePear = new GOTBlockFenceGate(planks1, 5);
		fenceGatePine = new GOTBlockFenceGate(planks2, 4);
		fenceGatePlum = new GOTBlockFenceGate(planks3, 0);
		fenceGatePomegranate = new GOTBlockFenceGate(planks3, 2);
		fenceGateRedwood = new GOTBlockFenceGate(planks3, 1);
		fenceGateRotten = new GOTBlockFenceGate(planksRotten, 0);
		fenceGateSpruce = new GOTBlockFenceGate(Blocks.planks, 1).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateUlthos = new GOTBlockFenceGate(planks1, 2);
		fenceGateWeirwood = new GOTBlockFenceGate(planks3, 6);
		fenceGateWillow = new GOTBlockFenceGate(planks2, 9);
		fenceRotten = new GOTBlockFence(planksRotten);
		flaxCrop = new GOTBlockFlaxCrop();
		flaxPlant = new GOTBlockFlower().setFlowerBounds(0.2f, 0.0f, 0.2f, 0.8f, 0.8f, 0.8f);
		flowerPot = new GOTBlockFlowerPot().setHardness(0.0f).setStepSound(Block.soundTypeStone);
		fruitLeaves = new GOTBlockLeavesFruit();
		fruitSapling = new GOTBlockSaplingFruit();
		fruitWood = new GOTBlockFruitWood();
		furBed = new GOTBlockBed(Blocks.planks, 0);
		fuse = new GOTBlockDoubleTorch();
		gateBronzeBars = GOTBlockGate.createMetal(false);
		gateEssos = GOTBlockGate.createWooden(true);
		gateGold = GOTBlockGate.createMetal(true);
		gateIbben = GOTBlockGate.createWooden(true);
		gateIronBars = GOTBlockGate.createMetal(false);
		gateSilver = GOTBlockGate.createMetal(true);
		gateSothoryos = GOTBlockGate.createWooden(true);
		gateValyrian = GOTBlockGate.createMetal(true);
		gateWesteros = GOTBlockGate.createWooden(true);
		gateWooden = GOTBlockGate.createWooden(true);
		gateWoodenCross = GOTBlockGate.createWooden(false);
		gateYiTi = GOTBlockGate.createWooden(true);
		glass = new GOTBlockGlass();
		glassBottleBlock = new GOTBlockGlassBottle();
		glassPane = new GOTBlockGlassPane();
		gobletCopperBlock = new GOTBlockGoblet.Copper();
		gobletGoldBlock = new GOTBlockGoblet.Gold();
		gobletSilverBlock = new GOTBlockGoblet.Silver();
		gobletWoodBlock = new GOTBlockGoblet.Wood();
		goldBars = new GOTBlockBars();
		grapevine = new GOTBlockGrapevine(false);
		grapevineRed = new GOTBlockGrapevineRed();
		grapevineWhite = new GOTBlockGrapevineWhite();
		hearth = new GOTBlockHearth().setHardness(1.0f).setResistance(8.0f).setStepSound(Block.soundTypeStone);
		kebabBlock = new GOTBlockKebab();
		kebabStand = new GOTBlockKebabStand("");
		kebabStandSand = new GOTBlockKebabStand("sand");
		kelp = new GOTBlockKelp();
		leaves1 = new GOTBlockLeaves1();
		leaves2 = new GOTBlockLeaves2();
		leaves3 = new GOTBlockLeaves3();
		leaves4 = new GOTBlockLeaves4();
		leaves5 = new GOTBlockLeaves5();
		leaves6 = new GOTBlockLeaves6();
		leaves7 = new GOTBlockLeaves7();
		leaves8 = new GOTBlockLeaves8();
		leaves9 = new GOTBlockLeaves9();
		leavesSnowy = new GOTBlockBone().setCreativeTab(null);
		leekCrop = new GOTBlockLeekCrop();
		lemonCake = new GOTBlockPlaceableFood();
		lettuceCrop = new GOTBlockLettuceCrop();
		lionBed = new GOTBlockBed(Blocks.planks, 0);
		marigold = new GOTBlockFlower();
		marshLights = new GOTBlockMarshLights();
		marzipanBlock = new GOTBlockPlaceableFood(0.4375f, 0.375f).setFoodStats(3, 0.3f).setCreativeTab(GOTCreativeTabs.tabFood);
		millstone = new GOTBlockMillstone();
		mirkVines = new GOTBlockVine();
		mud = new GOTBlockMud();
		mudFarmland = new GOTBlockMudFarmland();
		mudGrass = new GOTBlockMudGrass();
		mugBlock = new GOTBlockMug();
		obsidianGravel = new GOTBlockObsidianGravel();
		oreCobalt = new GOTBlockOre();
		oreCopper = new GOTBlockOre();
		oreGem = new GOTBlockOreGem();
		oreGlowstone = new GOTBlockOre().setLightLevel(0.75f);
		oreSalt = new GOTBlockOre();
		oreSaltpeter = new GOTBlockOre();
		oreSilver = new GOTBlockOre();
		oreSulfur = new GOTBlockOre();
		oreTin = new GOTBlockOre();
		oreValyrian = new GOTBlockOre().setHardness(4.0f).setResistance(10.0f);
		oven = new GOTBlockOven();
		pastry = new GOTBlockPlaceableFood(0.3125f, 0.375f);
		pillar1 = new GOTBlockPillar1();
		pillar2 = new GOTBlockPillar2();
		pipeweedCrop = new GOTBlockPipeweedCrop();
		pipeweedPlant = new GOTBlockPipeweedPlant();
		plantain = new GOTBlockPlantain();
		plateBlock = new GOTBlockPlate().setStepSound(GOTBlockPlate.soundTypePlate);
		pressurePlateAndesite = new GOTBlockPressurePlate("got:rock_andesite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateBasalt = new GOTBlockPressurePlate("got:rock_basalt", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateChalk = new GOTBlockPressurePlate("got:rock_chalk", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateDiorite = new GOTBlockPressurePlate("got:rock_diorite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateGranite = new GOTBlockPressurePlate("got:rock_granite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateLabradorite = new GOTBlockPressurePlate("got:rock_labradorite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateRhyolite = new GOTBlockPressurePlate("got:rock_rhyolite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		quagmire = new GOTBlockQuagmire().setHardness(1.0f).setStepSound(Block.soundTypeGravel);
		quicksand = new GOTBlockQuicksand().setHardness(0.5f).setStepSound(Block.soundTypeSand);
		redBrick = new GOTBlockBrickRed();
		redClay = new GOTBlockRedClay();
		redSandstone = new GOTBlockSandstone();
		reedBars = new GOTBlockReedBars();
		reeds = new GOTBlockReed();
		ricePlant = new GOTBlockRice().setHardness(0.0f).setStepSound(Block.soundTypeGrass).setResistance(0.0f).setBlockName("rice").setBlockTextureName("complexcrops:rice/rice");
		rock = new GOTBlockRock();
		rope = new GOTBlockRope(false);
		rottenLog = new GOTBlockWoodRotten();
		rottenSlabDouble = new GOTBlockSlabRotten(true).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		rottenSlabSingle = new GOTBlockSlabRotten(false).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		sapling1 = new GOTBlockSapling1();
		sapling2 = new GOTBlockSapling2();
		sapling3 = new GOTBlockSapling3();
		sapling4 = new GOTBlockSapling4();
		sapling5 = new GOTBlockSapling5();
		sapling6 = new GOTBlockSapling6();
		sapling7 = new GOTBlockSapling7();
		sapling8 = new GOTBlockSapling8();
		sapling9 = new GOTBlockSapling9();
		sarbacaneTrap = new GOTBlockSarbacaneTrap(brick4, 0);
		sarbacaneTrapGold = new GOTBlockSarbacaneTrap(brick4, 3);
		sarbacaneTrapObsidian = new GOTBlockSarbacaneTrap(brick4, 4);
		scorchedSlabDouble = new GOTBlockScorchedSlab(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		scorchedSlabSingle = new GOTBlockScorchedSlab(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		scorchedStone = new GOTBlockScorchedStone();
		scorchedWall = new GOTBlockScorchedWall();
		signCarved = new GOTBlockSignCarved(GOTTileEntitySignCarved.class);
		signCarvedGlowing = new GOTBlockSignCarved(GOTTileEntitySignCarvedValyrian.class);
		silverBars = new GOTBlockBars();
		skullCupBlock = new GOTBlockSkullCup();
		slabBoneDouble = new GOTBlockSlabBone(true);
		slabBoneSingle = new GOTBlockSlabBone(false);
		slabClayTileDouble = new GOTBlockSlabClayTile(true);
		slabClayTileDyedDouble1 = new GOTBlockSlabClayTileDyed(true);
		slabClayTileDyedDouble2 = new GOTBlockSlabClayTileDyed2(true);
		slabClayTileDyedSingle1 = new GOTBlockSlabClayTileDyed(false);
		slabClayTileDyedSingle2 = new GOTBlockSlabClayTileDyed2(false);
		slabClayTileSingle = new GOTBlockSlabClayTile(false);
		slabDouble1 = new GOTBlockSlab1(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble10 = new GOTBlockSlab10(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble11 = new GOTBlockSlab11(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble12 = new GOTBlockSlab12(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble2 = new GOTBlockSlab2(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble3 = new GOTBlockSlab3(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble4 = new GOTBlockSlab4(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble5 = new GOTBlockSlab5(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble6 = new GOTBlockSlab6(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble7 = new GOTBlockSlab7(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble8 = new GOTBlockSlab8(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble9 = new GOTBlockSlab9(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDoubleDirt = new GOTBlockSlabDirt(true);
		slabDoubleGravel = new GOTBlockSlabGravel(true);
		slabDoubleSand = new GOTBlockSlabSand(true);
		slabDoubleThatch = new GOTBlockSlabThatch(true);
		slabDoubleV = new GOTBlockSlabV(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle1 = new GOTBlockSlab1(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle10 = new GOTBlockSlab10(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle11 = new GOTBlockSlab11(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle12 = new GOTBlockSlab12(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle2 = new GOTBlockSlab2(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle3 = new GOTBlockSlab3(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle4 = new GOTBlockSlab4(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle5 = new GOTBlockSlab5(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle6 = new GOTBlockSlab6(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle7 = new GOTBlockSlab7(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle8 = new GOTBlockSlab8(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle9 = new GOTBlockSlab9(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingleDirt = new GOTBlockSlabDirt(false);
		slabSingleGravel = new GOTBlockSlabGravel(false);
		slabSingleSand = new GOTBlockSlabSand(false);
		slabSingleThatch = new GOTBlockSlabThatch(false);
		slabSingleV = new GOTBlockSlabV(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		smoothStone = new GOTBlockSmoothStone();
		smoothStoneV = new GOTBlockSmoothStoneV();
		sothoryosDoubleTorch = new GOTBlockDoubleTorch();
		spawnerChest = new GOTBlockSpawnerChest(Blocks.chest);
		spawnerChestAncientEssos = new GOTBlockSpawnerChest(chestEssos);
		spawnerChestStone = new GOTBlockSpawnerChest(chestStone);
		stainedGlass = new GOTBlockStainedGlass();
		stainedGlassPane = new GOTBlockStainedGlassPane();
		stairsAlmond = new GOTBlockStairs(planks2, 15);
		stairsAndesite = new GOTBlockStairs(rock, 1);
		stairsAndesiteBrick = new GOTBlockStairs(brick1, 1);
		stairsAndesiteBrickCracked = new GOTBlockStairs(brick1, 3);
		stairsAndesiteBrickMossy = new GOTBlockStairs(brick1, 2);
		stairsApple = new GOTBlockStairs(planks1, 4);
		stairsAramant = new GOTBlockStairs(planks1, 8);
		stairsAspen = new GOTBlockStairs(planks2, 12);
		stairsBanana = new GOTBlockStairs(planks1, 11);
		stairsBaobab = new GOTBlockStairs(planks2, 1);
		stairsBasalt = new GOTBlockStairs(rock, 0);
		stairsBasaltBrick = new GOTBlockStairs(brick1, 0);
		stairsBasaltBrickCracked = new GOTBlockStairs(brick1, 7);
		stairsBasaltWesterosBrick = new GOTBlockStairs(brick2, 11);
		stairsBeech = new GOTBlockStairs(planks1, 9);
		stairsBone = new GOTBlockStairs(boneBlock, 0);
		stairsBrickCracked = new GOTBlockStairs(redBrick, 1).setCreativeTab(CreativeTabs.tabBlock);
		stairsBrickMossy = new GOTBlockStairs(redBrick, 0).setCreativeTab(CreativeTabs.tabBlock);
		stairsCatalpa = new GOTBlockStairs(planks1, 1);
		stairsCedar = new GOTBlockStairs(planks2, 2);
		stairsChalk = new GOTBlockStairs(rock, 5);
		stairsChalkBrick = new GOTBlockStairs(brick4, 15);
		stairsCharred = new GOTBlockStairs(planks1, 3);
		stairsCherry = new GOTBlockStairs(planks1, 6);
		stairsChestnut = new GOTBlockStairs(planks2, 0);
		stairsClayTile = new GOTBlockStairs(clayTile, 0);
		stairsClayTileDyedBlack = new GOTBlockStairs(clayTileDyed, 15);
		stairsClayTileDyedBlue = new GOTBlockStairs(clayTileDyed, 11);
		stairsClayTileDyedBrown = new GOTBlockStairs(clayTileDyed, 12);
		stairsClayTileDyedCyan = new GOTBlockStairs(clayTileDyed, 9);
		stairsClayTileDyedGray = new GOTBlockStairs(clayTileDyed, 7);
		stairsClayTileDyedGreen = new GOTBlockStairs(clayTileDyed, 13);
		stairsClayTileDyedLightBlue = new GOTBlockStairs(clayTileDyed, 3);
		stairsClayTileDyedLightGray = new GOTBlockStairs(clayTileDyed, 8);
		stairsClayTileDyedLime = new GOTBlockStairs(clayTileDyed, 5);
		stairsClayTileDyedMagenta = new GOTBlockStairs(clayTileDyed, 2);
		stairsClayTileDyedOrange = new GOTBlockStairs(clayTileDyed, 1);
		stairsClayTileDyedPink = new GOTBlockStairs(clayTileDyed, 6);
		stairsClayTileDyedPurple = new GOTBlockStairs(clayTileDyed, 10);
		stairsClayTileDyedRed = new GOTBlockStairs(clayTileDyed, 14);
		stairsClayTileDyedWhite = new GOTBlockStairs(clayTileDyed, 0);
		stairsClayTileDyedYellow = new GOTBlockStairs(clayTileDyed, 4);
		stairsCobblestoneMossy = new GOTBlockStairs(Blocks.mossy_cobblestone, 0).setCreativeTab(CreativeTabs.tabBlock);
		stairsCypress = new GOTBlockStairs(planks2, 10);
		stairsDatePalm = new GOTBlockStairs(planks1, 14);
		stairsDiorite = new GOTBlockStairs(rock, 3);
		stairsDioriteBrick = new GOTBlockStairs(brick1, 14);
		stairsDragon = new GOTBlockStairs(planks3, 4);
		stairsFir = new GOTBlockStairs(planks2, 3);
		stairsFotinia = new GOTBlockStairs(planks2, 14);
		stairsGranite = new GOTBlockStairs(rock, 4);
		stairsGraniteBrick = new GOTBlockStairs(brick2, 2);
		stairsGreenOak = new GOTBlockStairs(planks2, 13);
		stairsHolly = new GOTBlockStairs(planks1, 10);
		stairsIbbinia = new GOTBlockStairs(planks1, 0);
		stairsKanuka = new GOTBlockStairs(planks3, 5);
		stairsLabradorite = new GOTBlockStairs(rock, 6);
		stairsLabradoriteBrick = new GOTBlockStairs(brick6, 4);
		stairsLabradoriteBrickCracked = new GOTBlockStairs(brick6, 6);
		stairsLabradoriteBrickMossy = new GOTBlockStairs(brick6, 7);
		stairsLarch = new GOTBlockStairs(planks1, 13);
		stairsLemon = new GOTBlockStairs(planks2, 5);
		stairsLhazarBrick = new GOTBlockStairs(brick3, 10);
		stairsLime = new GOTBlockStairs(planks2, 7);
		stairsMahogany = new GOTBlockStairs(planks2, 8);
		stairsMango = new GOTBlockStairs(planks1, 7);
		stairsMangrove = new GOTBlockStairs(planks1, 15);
		stairsMaple = new GOTBlockStairs(planks1, 12);
		stairsMudBrick = new GOTBlockStairs(brick5, 0);
		stairsOlive = new GOTBlockStairs(planks2, 11);
		stairsOrange = new GOTBlockStairs(planks2, 6);
		stairsPalm = new GOTBlockStairs(planks3, 3);
		stairsPear = new GOTBlockStairs(planks1, 5);
		stairsPine = new GOTBlockStairs(planks2, 4);
		stairsPlum = new GOTBlockStairs(planks3, 0);
		stairsPomegranate = new GOTBlockStairs(planks3, 2);
		stairsRedSandstone = new GOTBlockStairs(redSandstone, 0);
		stairsRedwood = new GOTBlockStairs(planks3, 1);
		stairsReed = new GOTBlockStairs(thatch, 1);
		stairsRhyolite = new GOTBlockStairs(rock, 2);
		stairsRhyoliteBrick = new GOTBlockStairs(brick1, 4);
		stairsRotten = new GOTBlockStairs(planksRotten, 1);
		stairsSandstoneBrick = new GOTBlockStairs(brick1, 15);
		stairsSandstoneBrickCracked = new GOTBlockStairs(brick3, 11);
		stairsSandstoneBrickRed = new GOTBlockStairs(brick3, 13);
		stairsSandstoneBrickRedCracked = new GOTBlockStairs(brick3, 14);
		stairsScorchedStone = new GOTBlockStairs(scorchedStone, 0);
		stairsSothoryosBrick = new GOTBlockStairs(brick4, 0);
		stairsSothoryosBrickCracked = new GOTBlockStairs(brick4, 2);
		stairsSothoryosBrickGold = new GOTBlockStairs(brick4, 3);
		stairsSothoryosBrickMossy = new GOTBlockStairs(brick4, 1);
		stairsSothoryosBrickObsidian = new GOTBlockStairs(brick4, 4);
		stairsStone = new GOTBlockStairs(Blocks.stone, 0).setCreativeTab(CreativeTabs.tabBlock);
		stairsStoneBrickCracked = new GOTBlockStairs(Blocks.stonebrick, 2).setCreativeTab(CreativeTabs.tabBlock);
		stairsStoneBrickMossy = new GOTBlockStairs(Blocks.stonebrick, 1).setCreativeTab(CreativeTabs.tabBlock);
		stairsThatch = new GOTBlockStairs(thatch, 0);
		stairsUlthos = new GOTBlockStairs(planks1, 2);
		stairsWeirwood = new GOTBlockStairs(planks3, 6);
		stairsWhiteSandstone = new GOTBlockStairs(whiteSandstone, 0);
		stairsWillow = new GOTBlockStairs(planks2, 9);
		stairsYiTiBrick = new GOTBlockStairs(brick5, 11);
		stairsYiTiBrickCracked = new GOTBlockStairs(brick5, 14);
		stairsYiTiBrickFlowers = new GOTBlockStairs(brick5, 15);
		stairsYiTiBrickMossy = new GOTBlockStairs(brick5, 13);
		stairsYiTiBrickRed = new GOTBlockStairs(brick6, 1);
		stalactite = new GOTBlockStalactite(Blocks.stone, 0);
		stalactiteIce = new GOTBlockStalactite(Blocks.packed_ice, 0);
		stalactiteObsidian = new GOTBlockStalactite(Blocks.obsidian, 0);
		strawBed = new GOTBlockBed(Blocks.planks, 0);
		tableArryn = new GOTBlockTableArryn();
		tableAsshai = new GOTBlockTableAsshai();
		tableBraavos = new GOTBlockTableBraavos();
		tableCrownlands = new GOTBlockTableCrownlands();
		tableDorne = new GOTBlockTableDorne();
		tableDothraki = new GOTBlockTableDothraki();
		tableDragonstone = new GOTBlockTableDragonstone();
		tableGhiscar = new GOTBlockTableGhiscar();
		tableGift = new GOTBlockTableGift();
		tableHillTribes = new GOTBlockTableHillTribes();
		tableIbben = new GOTBlockTableIbben();
		tableIronborn = new GOTBlockTableIronborn();
		tableJogos = new GOTBlockTableJogos();
		tableLhazar = new GOTBlockTableLhazar();
		tableLorath = new GOTBlockTableLorath();
		tableLys = new GOTBlockTableLys();
		tableMossovy = new GOTBlockTableMossovy();
		tableMyr = new GOTBlockTableMyr();
		tableNorth = new GOTBlockTableNorth();
		tableNorvos = new GOTBlockTableNorvos();
		tablePentos = new GOTBlockTablePentos();
		tableQarth = new GOTBlockTableQarth();
		tableQohor = new GOTBlockTableQohor();
		tableReach = new GOTBlockTableReach();
		tableRiverlands = new GOTBlockTableRiverlands();
		tableSothoryos = new GOTBlockTableSothoryos();
		tableStormlands = new GOTBlockTableStormlands();
		tableSummer = new GOTBlockTableSummer();
		tableTyrosh = new GOTBlockTableTyrosh();
		tableVolantis = new GOTBlockTableVolantis();
		tableWesterlands = new GOTBlockTableWesterlands();
		tableWildling = new GOTBlockTableWildling();
		tableYiTi = new GOTBlockTableYiTi();
		tallGrass = new GOTBlockTallGrass();
		termiteMound = new GOTBlockTermite();
		thatchFloor = new GOTBlockThatchFloor();
		trapdoorAcacia = new GOTBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorAlmond = new GOTBlockTrapdoor();
		trapdoorApple = new GOTBlockTrapdoor();
		trapdoorAramant = new GOTBlockTrapdoor();
		trapdoorAspen = new GOTBlockTrapdoor();
		trapdoorBanana = new GOTBlockTrapdoor();
		trapdoorBaobab = new GOTBlockTrapdoor();
		trapdoorBeech = new GOTBlockTrapdoor();
		trapdoorBirch = new GOTBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorCatalpa = new GOTBlockTrapdoor();
		trapdoorCedar = new GOTBlockTrapdoor();
		trapdoorCharred = new GOTBlockTrapdoor();
		trapdoorCherry = new GOTBlockTrapdoor();
		trapdoorChestnut = new GOTBlockTrapdoor();
		trapdoorCypress = new GOTBlockTrapdoor();
		trapdoorDarkOak = new GOTBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorDatePalm = new GOTBlockTrapdoor();
		trapdoorDragon = new GOTBlockTrapdoor();
		trapdoorFir = new GOTBlockTrapdoor();
		trapdoorFotinia = new GOTBlockTrapdoor();
		trapdoorGreenOak = new GOTBlockTrapdoor();
		trapdoorHolly = new GOTBlockTrapdoor();
		trapdoorIbbinia = new GOTBlockTrapdoor();
		trapdoorJungle = new GOTBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorKanuka = new GOTBlockTrapdoor();
		trapdoorLarch = new GOTBlockTrapdoor();
		trapdoorLemon = new GOTBlockTrapdoor();
		trapdoorLime = new GOTBlockTrapdoor();
		trapdoorMahogany = new GOTBlockTrapdoor();
		trapdoorMango = new GOTBlockTrapdoor();
		trapdoorMangrove = new GOTBlockTrapdoor();
		trapdoorMaple = new GOTBlockTrapdoor();
		trapdoorOlive = new GOTBlockTrapdoor();
		trapdoorOrange = new GOTBlockTrapdoor();
		trapdoorPalm = new GOTBlockTrapdoor();
		trapdoorPear = new GOTBlockTrapdoor();
		trapdoorPine = new GOTBlockTrapdoor();
		trapdoorPlum = new GOTBlockTrapdoor();
		trapdoorPomegranate = new GOTBlockTrapdoor();
		trapdoorRedwood = new GOTBlockTrapdoor();
		trapdoorRotten = new GOTBlockTrapdoor();
		trapdoorSpruce = new GOTBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorUlthos = new GOTBlockTrapdoor();
		trapdoorWeirwood = new GOTBlockTrapdoor();
		trapdoorWillow = new GOTBlockTrapdoor();
		treasureCopper = new GOTBlockTreasurePile();
		treasureGold = new GOTBlockTreasurePile();
		treasureSilver = new GOTBlockTreasurePile();
		turnipCrop = new GOTBlockTurnipCrop();
		ulthosBars = new GOTBlockWoodBars();
		ulthosTorch = new GOTBlockUlthosTorch().setHardness(0.0f).setStepSound(Block.soundTypeWood).setLightLevel(0.9375f);
		unsmeltery = new GOTBlockUnsmeltery();
		valyrianBars = new GOTBlockBars();
		wallBone = new GOTBlockWallBone();
		wallClayTile = new GOTBlockWallClayTile();
		wallClayTileDyed = new GOTBlockWallClayTileDyed();
		wallStone1 = new GOTBlockWall1();
		wallStone2 = new GOTBlockWall2();
		wallStone3 = new GOTBlockWall3();
		wallStone4 = new GOTBlockWall4();
		wallStoneV = new GOTBlockWallV();
		wasteBlock = new GOTBlockWaste();
		weaponRack = new GOTBlockWeaponRack();
		whiteSand = new GOTBlockSand();
		wildFire = new GOTBlockWildFire();
		wildFireJar = new GOTBlockWildFireJar();
		willowVines = new GOTBlockVine();
		wineGlassBlock = new GOTBlockWineGlass();
		wood1 = new GOTBlockWood1();
		wood2 = new GOTBlockWood2();
		wood3 = new GOTBlockWood3();
		wood4 = new GOTBlockWood4();
		wood5 = new GOTBlockWood5();
		wood6 = new GOTBlockWood6();
		wood7 = new GOTBlockWood7();
		wood8 = new GOTBlockWood8();
		wood9 = new GOTBlockWood9();
		woodBeam1 = new GOTBlockWoodBeam1();
		woodBeam2 = new GOTBlockWoodBeam2();
		woodBeam3 = new GOTBlockWoodBeam3();
		woodBeam4 = new GOTBlockWoodBeam4();
		woodBeam5 = new GOTBlockWoodBeam5();
		woodBeam6 = new GOTBlockWoodBeam6();
		woodBeam7 = new GOTBlockWoodBeam7();
		woodBeam8 = new GOTBlockWoodBeam8();
		woodBeam9 = new GOTBlockWoodBeam9();
		woodBeamFruit = new GOTBlockWoodBeamFruit();
		woodBeamRotten = new GOTBlockWoodBeamRotten();
		woodBeamS = new GOTBlockWoodBeamS();
		woodBeamV1 = new GOTBlockWoodBeamV1();
		woodBeamV2 = new GOTBlockWoodBeamV2();
		woodPlateBlock = new GOTBlockPlate().setStepSound(Block.soundTypeWood);
		woodSlabDouble1 = new GOTBlockWoodSlab1(true);
		woodSlabDouble2 = new GOTBlockWoodSlab2(true).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		woodSlabDouble3 = new GOTBlockWoodSlab3(true);
		woodSlabDouble4 = new GOTBlockWoodSlab4(true);
		woodSlabDouble5 = new GOTBlockWoodSlab5(true);
		woodSlabSingle1 = new GOTBlockWoodSlab1(false);
		woodSlabSingle2 = new GOTBlockWoodSlab2(false).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		woodSlabSingle3 = new GOTBlockWoodSlab3(false);
		woodSlabSingle4 = new GOTBlockWoodSlab4(false);
		woodSlabSingle5 = new GOTBlockWoodSlab5(false);
		yamCrop = new GOTBlockYamCrop();
		yitiFlower = new GOTBlockYiTiFlower();
	}

	public static void onInit() {
		GOTBlockSlabBase.registerSlabs(slabSingle1, slabDouble1);
		GOTBlockSlabBase.registerSlabs(slabSingle2, slabDouble2);
		GOTBlockSlabBase.registerSlabs(slabSingle3, slabDouble3);
		GOTBlockSlabBase.registerSlabs(slabSingle4, slabDouble4);
		GOTBlockSlabBase.registerSlabs(slabSingle5, slabDouble5);
		GOTBlockSlabBase.registerSlabs(slabSingle6, slabDouble6);
		GOTBlockSlabBase.registerSlabs(slabSingle7, slabDouble7);
		GOTBlockSlabBase.registerSlabs(slabSingle8, slabDouble8);
		GOTBlockSlabBase.registerSlabs(slabSingle9, slabDouble9);
		GOTBlockSlabBase.registerSlabs(slabSingle10, slabDouble10);
		GOTBlockSlabBase.registerSlabs(slabSingle11, slabDouble11);
		GOTBlockSlabBase.registerSlabs(slabSingle12, slabDouble12);
		GOTBlockSlabBase.registerSlabs(slabSingleV, slabDoubleV);
		GOTBlockSlabBase.registerSlabs(scorchedSlabSingle, scorchedSlabDouble);
		GOTBlockSlabBase.registerSlabs(slabClayTileSingle, slabClayTileDouble);
		GOTBlockSlabBase.registerSlabs(slabClayTileDyedSingle1, slabClayTileDyedDouble1);
		GOTBlockSlabBase.registerSlabs(slabClayTileDyedSingle2, slabClayTileDyedDouble2);
		GOTBlockSlabBase.registerSlabs(woodSlabSingle1, woodSlabDouble1);
		GOTBlockSlabBase.registerSlabs(woodSlabSingle2, woodSlabDouble2);
		GOTBlockSlabBase.registerSlabs(woodSlabSingle3, woodSlabDouble3);
		GOTBlockSlabBase.registerSlabs(woodSlabSingle4, woodSlabDouble4);
		GOTBlockSlabBase.registerSlabs(woodSlabSingle5, woodSlabDouble5);
		GOTBlockSlabBase.registerSlabs(rottenSlabSingle, rottenSlabDouble);
		GOTBlockSlabBase.registerSlabs(slabSingleThatch, slabDoubleThatch);
		GOTBlockSlabBase.registerSlabs(slabSingleDirt, slabDoubleDirt);
		GOTBlockSlabBase.registerSlabs(slabSingleSand, slabDoubleSand);
		GOTBlockSlabBase.registerSlabs(slabSingleGravel, slabDoubleGravel);
		GOTBlockSlabBase.registerSlabs(slabBoneSingle, slabBoneDouble);
		GOTBlockFallenLeaves.assignLeaves(fallenLeaves1, Blocks.leaves, Blocks.leaves2);
		GOTBlockFallenLeaves.assignLeaves(fallenLeaves2, leaves1, fruitLeaves, leaves2, leaves3);
		GOTBlockFallenLeaves.assignLeaves(fallenLeaves3, leaves4, leaves5, leaves6, leaves7);
		GOTBlockFallenLeaves.assignLeaves(fallenLeaves4, leaves8, leaves9);

		for (Block block : CONTENT) {
			if (block instanceof GOTBlockWoodBase) {
				Blocks.fire.setFireInfo(block, 5, 5);
			}
			if (block instanceof GOTBlockPlanksBase || block instanceof GOTBlockFence || block instanceof GOTBlockWoodBars || block instanceof GOTBlockWoodBeam || (block instanceof GOTBlockSlabBase || block instanceof GOTBlockStairs) && block.getMaterial() == Material.wood) {
				Blocks.fire.setFireInfo(block, 5, 20);
			}
			if (block instanceof GOTBlockVine) {
				Blocks.fire.setFireInfo(block, 15, 100);
			}
			if (block instanceof GOTBlockLeavesBase || block instanceof GOTBlockFallenLeaves || block instanceof GOTBlockBerryBush) {
				Blocks.fire.setFireInfo(block, 30, 60);
			}
			if (block instanceof GOTBlockDaub) {
				Blocks.fire.setFireInfo(block, 40, 40);
			}
			if (block instanceof GOTBlockThatch || block instanceof GOTBlockThatchFloor || block instanceof GOTBlockReedBars || (block instanceof GOTBlockSlabBase || block instanceof GOTBlockStairs) && block.getMaterial() == Material.grass) {
				Blocks.fire.setFireInfo(block, 60, 20);
			}
			if (block instanceof GOTBlockThatch || block instanceof GOTBlockThatchFloor || block instanceof GOTBlockReedBars || block instanceof GOTBlockGrass || block instanceof GOTBlockAsshaiGrass || block instanceof GOTBlockAsshaiMoss || block instanceof GOTBlockFlower || block instanceof GOTBlockDoubleFlower) {
				Blocks.fire.setFireInfo(block, 60, 100);
			}
		}

		Blocks.dragon_egg.setCreativeTab(GOTCreativeTabs.tabStory);
		Blocks.fire.setFireInfo(Blocks.acacia_stairs, 5, 20);
		Blocks.fire.setFireInfo(Blocks.dark_oak_stairs, 5, 20);
		String pickaxe = "pickaxe";
		String shovel = "shovel";
		oreCopper.setHarvestLevel(pickaxe, 1);
		oreTin.setHarvestLevel(pickaxe, 1);
		oreSilver.setHarvestLevel(pickaxe, 2);
		oreCobalt.setHarvestLevel(pickaxe, 2);
		oreValyrian.setHarvestLevel(pickaxe, 2);
		blockMetal1.setHarvestLevel(pickaxe, 1, 0);
		blockMetal1.setHarvestLevel(pickaxe, 1, 1);
		blockMetal1.setHarvestLevel(pickaxe, 1, 2);
		blockMetal1.setHarvestLevel(pickaxe, 2, 3);
		blockMetal1.setHarvestLevel(pickaxe, 2, 4);
		oreGlowstone.setHarvestLevel(pickaxe, 1);
		quagmire.setHarvestLevel(shovel, 0);
		quicksand.setHarvestLevel(shovel, 0);
		blockMetal2.setHarvestLevel(pickaxe, 1, 4);
		asshaiDirt.setHarvestLevel(shovel, 0);
		basaltGravel.setHarvestLevel(shovel, 0);
		obsidianGravel.setHarvestLevel(shovel, 0);
		mud.setHarvestLevel(shovel, 0);
		mudGrass.setHarvestLevel(shovel, 0);
		mudFarmland.setHarvestLevel(shovel, 0);
		dirtPath.setHarvestLevel(shovel, 0);
		slabSingleDirt.setHarvestLevel(shovel, 0);
		slabDoubleDirt.setHarvestLevel(shovel, 0);
		slabSingleSand.setHarvestLevel(shovel, 0);
		slabDoubleSand.setHarvestLevel(shovel, 0);
		slabSingleGravel.setHarvestLevel(shovel, 0);
		slabDoubleGravel.setHarvestLevel(shovel, 0);
		whiteSand.setHarvestLevel(shovel, 0);
		stalactiteObsidian.setHarvestLevel(pickaxe, 3);
		oreGem.setHarvestLevel(pickaxe, 2);
		blockGem.setHarvestLevel(pickaxe, 2);
		blockGem.setHarvestLevel(pickaxe, 0, 8);
		redClay.setHarvestLevel(shovel, 0);
	}

	public static void preInit() {
		GOTBlockReplacement.replaceVanillaBlock(Blocks.leaves, new GOTBlockLeavesVanilla1(), ItemLeaves.class);
		GOTBlockReplacement.replaceVanillaBlock(Blocks.leaves2, new GOTBlockLeavesVanilla2(), ItemLeaves.class);
		GOTBlockReplacement.replaceVanillaBlock(Blocks.fence, new GOTBlockFenceVanilla(), GOTItemFenceVanilla.class);
		GOTBlockReplacement.replaceVanillaBlock(Blocks.cake, new GOTBlockPlaceableFood().setBlockTextureName("cake"), null);
		assignBlocks();
		registerBlocks();
	}

	public static void registerBlock(Block block, String codename) {
		registerBlock(block, codename, ItemBlock.class);
	}

	public static void registerBlock(Block block, String codename, Class<? extends ItemBlock> itemClass) {
		String lowerUnderscoreName = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, codename);
		block.setBlockName("got:" + lowerUnderscoreName);
		block.setBlockTextureName("got:" + lowerUnderscoreName);
		GameRegistry.registerBlock(block, itemClass, "tile." + lowerUnderscoreName);
		CONTENT.add(block);
	}

	public static void registerBlocks() {
		registerBlock(rock, "rock", GOTItemBlockMetadata.class);
		registerBlock(oreCopper, "oreCopper");
		registerBlock(oreTin, "oreTin");
		registerBlock(oreSilver, "oreSilver");
		registerBlock(oreCobalt, "oreCobalt");
		registerBlock(oreValyrian, "oreValyrian");
		registerBlock(beacon, "beacon");
		registerBlock(wood1, "wood1", GOTItemBlockMetadata.class);
		registerBlock(leaves1, "leaves1", GOTItemLeaves.class);
		registerBlock(planks1, "planks1", GOTItemBlockMetadata.class);
		registerBlock(sapling1, "sapling1", GOTItemBlockMetadata.class);
		registerBlock(woodSlabSingle1, "woodSlabSingle1", GOTBlockSlabBase.SlabItems.WoodSlab1Single.class);
		registerBlock(woodSlabDouble1, "woodSlabDouble1", GOTBlockSlabBase.SlabItems.WoodSlab1Double.class);
		registerBlock(stairsIbbinia, "stairsIbbinia");
		registerBlock(brick1, "brick1", GOTItemBlockMetadata.class);
		registerBlock(appleCrumble, "appleCrumble");
		registerBlock(oven, "oven");
		registerBlock(blockMetal1, "blockMetal1", GOTItemBlockMetadata.class);
		registerBlock(chandelier, "chandelier", GOTItemBlockMetadata.class);
		registerBlock(pipeweedPlant, "pipeweedPlant");
		registerBlock(pipeweedCrop, "pipeweed");
		registerBlock(slabSingle1, "slabSingle1", GOTBlockSlabBase.SlabItems.Slab1Single.class);
		registerBlock(slabDouble1, "slabDouble1", GOTBlockSlabBase.SlabItems.Slab1Double.class);
		registerBlock(stairsBasaltBrick, "stairsBasaltBrick");
		registerBlock(stairsAndesiteBrick, "stairsAndesiteBrick");
		registerBlock(wallStone1, "wallStone1", GOTItemBlockMetadata.class);
		registerBlock(barrel, "barrel", GOTItemBarrel.class);
		registerBlock(lettuceCrop, "lettuce");
		registerBlock(bomb, "bomb", GOTItemBomb.class);
		registerBlock(fuse, "fuse");
		registerBlock(stairsCatalpa, "stairsCatalpa");
		registerBlock(plateBlock, "plate");
		registerBlock(asshaiBars, "asshaiBars");
		registerBlock(stairsAndesiteBrickMossy, "stairsAndesiteBrickMossy");
		registerBlock(stairsAndesiteBrickCracked, "stairsAndesiteBrickCracked");
		registerBlock(plantain, "plantain");
		registerBlock(stalactite, "stalactite", GOTItemBlockMetadata.class);
		registerBlock(stairsRhyoliteBrick, "stairsRhyoliteBrick");
		registerBlock(spawnerChest, "spawnerChest");
		registerBlock(pressurePlateBasalt, "pressurePlateBasalt");
		registerBlock(pressurePlateAndesite, "pressurePlateAndesite");
		registerBlock(buttonBasalt, "buttonBasalt");
		registerBlock(buttonAndesite, "buttonAndesite");
		registerBlock(flowerPot, "flowerPot");
		registerBlock(pillar1, "pillar1", GOTItemBlockMetadata.class);
		registerBlock(oreGlowstone, "oreGlowstone");
		registerBlock(fruitWood, "fruitWood", GOTItemBlockMetadata.class);
		registerBlock(fruitLeaves, "fruitLeaves", GOTItemLeaves.class);
		registerBlock(fruitSapling, "fruitSapling", GOTItemBlockMetadata.class);
		registerBlock(stairsApple, "stairsApple");
		registerBlock(stairsPear, "stairsPear");
		registerBlock(stairsCherry, "stairsCherry");
		registerBlock(bluebell, "bluebell");
		registerBlock(hearth, "hearth");
		registerBlock(cherryPie, "cherryPie");
		registerBlock(clover, "clover", GOTItemBlockMetadata.class);
		registerBlock(slabSingle2, "slabSingle2", GOTBlockSlabBase.SlabItems.Slab2Single.class);
		registerBlock(slabDouble2, "slabDouble2", GOTBlockSlabBase.SlabItems.Slab2Double.class);
		registerBlock(stairsUlthos, "stairsUlthos");
		registerBlock(tableNorth, "tableNorth");
		registerBlock(ulthosTorch, "ulthosTorch");
		registerBlock(marshLights, "marshLights");
		registerBlock(pressurePlateRhyolite, "pressurePlateRhyolite");
		registerBlock(deadMarshPlant, "deadMarshPlant");
		registerBlock(stairsCharred, "stairsCharred");
		registerBlock(armorStand, "armorStand");
		registerBlock(buttonRhyolite, "buttonRhyolite");
		registerBlock(wood2, "wood2", GOTItemBlockMetadata.class);
		registerBlock(leaves2, "leaves2", GOTItemLeaves.class);
		registerBlock(sapling2, "sapling2", GOTItemBlockMetadata.class);
		registerBlock(stairsAramant, "stairsAramant");
		registerBlock(woodSlabSingle2, "woodSlabSingle2", GOTBlockSlabBase.SlabItems.WoodSlab2Single.class);
		registerBlock(woodSlabDouble2, "woodSlabDouble2", GOTBlockSlabBase.SlabItems.WoodSlab2Double.class);
		registerBlock(mugBlock, "mug");
		registerBlock(tableHillTribes, "tableHillTribes");
		registerBlock(stairsBeech, "stairsBeech");
		registerBlock(asshaiThorn, "asshaiThorn");
		registerBlock(asshaiMoss, "asshaiMoss");
		registerBlock(stairsBasaltBrickCracked, "stairsBasaltBrickCracked");
		registerBlock(stairsHolly, "stairsHolly");
		registerBlock(pressurePlateDiorite, "pressurePlateDiorite");
		registerBlock(buttonDiorite, "buttonDiorite");
		registerBlock(slabSingle3, "slabSingle3", GOTBlockSlabBase.SlabItems.Slab3Single.class);
		registerBlock(slabDouble3, "slabDouble3", GOTBlockSlabBase.SlabItems.Slab3Double.class);
		registerBlock(stairsDioriteBrick, "stairsDioriteBrick");
		registerBlock(fence, "fence", GOTItemBlockMetadata.class);
		registerBlock(doubleFlower, "doubleFlower", GOTItemDoubleFlower.class);
		registerBlock(oreSulfur, "oreSulfur");
		registerBlock(oreSaltpeter, "oreSaltpeter");
		registerBlock(quagmire, "quagmire");
		registerBlock(quicksand, "quicksand");
		registerBlock(tableWildling, "tableWildling");
		registerBlock(brick2, "brick2", GOTItemBlockMetadata.class);
		registerBlock(wallStone2, "wallStone2", GOTItemBlockMetadata.class);
		registerBlock(stairsMango, "stairsMango");
		registerBlock(stairsBanana, "stairsBanana");
		registerBlock(bananaBlock, "banana");
		registerBlock(bananaCake, "bananaCake");
		registerBlock(lionBed, "lionBed");
		registerBlock(wood3, "wood3", GOTItemBlockMetadata.class);
		registerBlock(leaves3, "leaves3", GOTItemLeaves.class);
		registerBlock(sapling3, "sapling3", GOTItemBlockMetadata.class);
		registerBlock(stairsMaple, "stairsMaple");
		registerBlock(stairsLarch, "stairsLarch");
		registerBlock(tableSummer, "tableSummer");
		registerBlock(pressurePlateGranite, "pressurePlateGranite");
		registerBlock(buttonGranite, "buttonGranite");
		registerBlock(stairsGraniteBrick, "stairsGraniteBrick");
		registerBlock(slabSingle4, "slabSingle4", GOTBlockSlabBase.SlabItems.Slab4Single.class);
		registerBlock(slabDouble4, "slabDouble4", GOTBlockSlabBase.SlabItems.Slab4Double.class);
		registerBlock(stairsSandstoneBrick, "stairsSandstoneBrick");
		registerBlock(stairsDatePalm, "stairsDatePalm");
		registerBlock(dateBlock, "date");
		registerBlock(thatch, "thatch", GOTItemBlockMetadata.class);
		registerBlock(slabSingleThatch, "slabSingleThatch", GOTBlockSlabBase.SlabItems.ThatchSingle.class);
		registerBlock(slabDoubleThatch, "slabDoubleThatch", GOTBlockSlabBase.SlabItems.ThatchDouble.class);
		registerBlock(stairsThatch, "stairsThatch");
		registerBlock(asshaiTorch, "asshaiTorch");
		registerBlock(tableGift, "tableGift");
		registerBlock(strawBed, "strawBed");
		registerBlock(fallenLeaves1, "fallenLeaves1", GOTItemFallenLeaves.class);
		registerBlock(fallenLeaves2, "fallenLeaves2", GOTItemFallenLeaves.class);
		registerBlock(thatchFloor, "thatchFloor");
		registerBlock(pastry, "pastry");
		registerBlock(aridGrass, "aridGrass");
		registerBlock(termiteMound, "termiteMound", GOTItemBlockMetadata.class);
		registerBlock(slabSingle5, "slabSingle5", GOTBlockSlabBase.SlabItems.Slab5Single.class);
		registerBlock(slabDouble5, "slabDouble5", GOTBlockSlabBase.SlabItems.Slab5Double.class);
		registerBlock(stairsMangrove, "stairsMangrove");
		registerBlock(tallGrass, "tallGrass", GOTItemTallGrass.class);
		registerBlock(essosFlower, "essosFlower", GOTItemBlockMetadata.class);
		registerBlock(flaxPlant, "flaxPlant");
		registerBlock(flaxCrop, "flax");
		registerBlock(cucumberPlant, "cucumberPlant");
		registerBlock(cucumberCrop, "cucumber");
		registerBlock(berryBush, "berryBush", GOTItemBlockMetadata.class);
		registerBlock(planks2, "planks2", GOTItemBlockMetadata.class);
		registerBlock(fence2, "fence2", GOTItemBlockMetadata.class);
		registerBlock(woodSlabSingle3, "woodSlabSingle3", GOTBlockSlabBase.SlabItems.WoodSlab3Single.class);
		registerBlock(woodSlabDouble3, "woodSlabDouble3", GOTBlockSlabBase.SlabItems.WoodSlab3Double.class);
		registerBlock(wood4, "wood4", GOTItemBlockMetadata.class);
		registerBlock(leaves4, "leaves4", GOTItemLeaves.class);
		registerBlock(sapling4, "sapling4", GOTItemBlockMetadata.class);
		registerBlock(stairsChestnut, "stairsChestnut");
		registerBlock(stairsBaobab, "stairsBaobab");
		registerBlock(fallenLeaves3, "fallenLeaves3", GOTItemFallenLeaves.class);
		registerBlock(stairsCedar, "stairsCedar");
		registerBlock(rottenLog, "rottenLog", GOTItemBlockMetadata.class);
		registerBlock(blockMetal2, "blockMetal2", GOTItemBlockMetadata.class);
		registerBlock(asshaiGrass, "asshaiGrass");
		registerBlock(asshaiDirt, "asshaiDirt");
		registerBlock(basaltGravel, "basaltGravel");
		registerBlock(commandTable, "commandTable");
		registerBlock(butterflyJar, "butterflyJar", GOTItemAnimalJar.class);
		registerBlock(berryPie, "berryPie");
		registerBlock(stairsBasaltWesterosBrick, "stairsBasaltWesterosBrick");
		registerBlock(brick3, "brick3", GOTItemBlockMetadata.class);
		registerBlock(wallStone3, "wallStone3", GOTItemBlockMetadata.class);
		registerBlock(stairsFir, "stairsFir");
		registerBlock(wood5, "wood5", GOTItemBlockMetadata.class);
		registerBlock(leaves5, "leaves5", GOTItemLeaves.class);
		registerBlock(sapling5, "sapling5", GOTItemBlockMetadata.class);
		registerBlock(stairsPine, "stairsPine");
		registerBlock(tableLhazar, "tableLhazar");
		registerBlock(slabSingle7, "slabSingle7", GOTBlockSlabBase.SlabItems.Slab7Single.class);
		registerBlock(slabDouble7, "slabDouble7", GOTBlockSlabBase.SlabItems.Slab7Double.class);
		registerBlock(stairsLhazarBrick, "stairsLhazarBrick");
		registerBlock(stairsSandstoneBrickCracked, "stairsSandstoneBrickCracked");
		registerBlock(unsmeltery, "unsmeltery");
		registerBlock(bronzeBars, "bronzeBars");
		registerBlock(goldBars, "goldBars");
		registerBlock(silverBars, "silverBars");
		registerBlock(valyrianBars, "valyrianBars");
		registerBlock(ulthosBars, "ulthosBars");
		registerBlock(planksRotten, "planksRotten", GOTItemBlockMetadata.class);
		registerBlock(stairsRotten, "stairsRotten");
		registerBlock(rottenSlabSingle, "rottenSlabSingle", GOTBlockSlabBase.SlabItems.RottenSlabSingle.class);
		registerBlock(rottenSlabDouble, "rottenSlabDouble", GOTBlockSlabBase.SlabItems.RottenSlabDouble.class);
		registerBlock(fenceRotten, "fenceRotten", GOTItemBlockMetadata.class);
		registerBlock(scorchedStone, "scorchedStone");
		registerBlock(scorchedSlabSingle, "scorchedSlabSingle", GOTBlockSlabBase.SlabItems.ScorchedSingle.class);
		registerBlock(scorchedSlabDouble, "scorchedSlabDouble", GOTBlockSlabBase.SlabItems.ScorchedDouble.class);
		registerBlock(stairsScorchedStone, "stairsScorchedStone");
		registerBlock(scorchedWall, "scorchedWall");
		registerBlock(stairsLemon, "stairsLemon");
		registerBlock(lemonCake, "lemonCake");
		registerBlock(stairsOrange, "stairsOrange");
		registerBlock(alloyForge, "alloyForge");
		registerBlock(stairsLime, "stairsLime");
		registerBlock(tableSothoryos, "tableSothoryos");
		registerBlock(brick4, "brick4", GOTItemBlockMetadata.class);
		registerBlock(wallStone4, "wallStone4", GOTItemBlockMetadata.class);
		registerBlock(slabSingle8, "slabSingle8", GOTBlockSlabBase.SlabItems.Slab8Single.class);
		registerBlock(slabDouble8, "slabDouble8", GOTBlockSlabBase.SlabItems.Slab8Double.class);
		registerBlock(stairsSothoryosBrick, "stairsSothoryosBrick");
		registerBlock(stairsSothoryosBrickMossy, "stairsSothoryosBrickMossy");
		registerBlock(stairsSothoryosBrickCracked, "stairsSothoryosBrickCracked");
		registerBlock(stairsSothoryosBrickGold, "stairsSothoryosBrickGold");
		registerBlock(stairsSothoryosBrickObsidian, "stairsSothoryosBrickObsidian");
		registerBlock(obsidianGravel, "obsidianGravel");
		registerBlock(sarbacaneTrap, "sarbacaneTrap");
		registerBlock(wood6, "wood6", GOTItemBlockMetadata.class);
		registerBlock(leaves6, "leaves6", GOTItemLeaves.class);
		registerBlock(sapling6, "sapling6", GOTItemBlockMetadata.class);
		registerBlock(woodSlabSingle4, "woodSlabSingle4", GOTBlockSlabBase.SlabItems.WoodSlab4Single.class);
		registerBlock(woodSlabDouble4, "woodSlabDouble4", GOTBlockSlabBase.SlabItems.WoodSlab4Double.class);
		registerBlock(stairsMahogany, "stairsMahogany");
		registerBlock(mud, "mud", GOTItemBlockMetadata.class);
		registerBlock(mudGrass, "mudGrass");
		registerBlock(chestStone, "chestStone");
		registerBlock(spawnerChestStone, "spawnerChestStone");
		registerBlock(mudFarmland, "mudFarmland");
		registerBlock(stairsSandstoneBrickRed, "stairsSandstoneBrickRed");
		registerBlock(stairsSandstoneBrickRedCracked, "stairsSandstoneBrickRedCracked");
		registerBlock(redSandstone, "redSandstone");
		registerBlock(stairsRedSandstone, "stairsRedSandstone");
		registerBlock(pillar2, "pillar2", GOTItemBlockMetadata.class);
		registerBlock(reeds, "reeds", GOTItemReeds.class);
		registerBlock(stairsReed, "stairsReed");
		registerBlock(sothoryosDoubleTorch, "sothoryosDoubleTorch");
		registerBlock(woodBeamV1, "woodBeamV1", GOTItemBlockMetadata.class);
		registerBlock(reedBars, "reedBars");
		registerBlock(woodBeamV2, "woodBeamV2", GOTItemBlockMetadata.class);
		registerBlock(woodBeam1, "woodBeam1", GOTItemBlockMetadata.class);
		registerBlock(sarbacaneTrapGold, "sarbacaneTrapGold");
		registerBlock(weaponRack, "weaponRack", GOTItemBlockWeaponRack.class);
		registerBlock(cornStalk, "cornStalk", GOTItemPlantableBlock.class);
		registerBlock(wasteBlock, "wasteBlock");
		registerBlock(dirtPath, "dirtPath", GOTItemBlockMetadata.class);
		registerBlock(stairsWillow, "stairsWillow");
		registerBlock(willowVines, "willowVines", GOTItemVine.class);
		registerBlock(woodBeam2, "woodBeam2", GOTItemBlockMetadata.class);
		registerBlock(woodBeamFruit, "woodBeamFruit", GOTItemBlockMetadata.class);
		registerBlock(woodBeam3, "woodBeam3", GOTItemBlockMetadata.class);
		registerBlock(woodBeam4, "woodBeam4", GOTItemBlockMetadata.class);
		registerBlock(woodBeam5, "woodBeam5", GOTItemBlockMetadata.class);
		registerBlock(woodBeam6, "woodBeam6", GOTItemBlockMetadata.class);
		registerBlock(woodBeamRotten, "woodBeamRotten", GOTItemBlockMetadata.class);
		registerBlock(gateWooden, "gateWooden", GOTItemGate.class);
		registerBlock(gateIronBars, "gateIronBars", GOTItemGate.class);
		registerBlock(gateBronzeBars, "gateBronzeBars", GOTItemGate.class);
		registerBlock(gateWoodenCross, "gateWoodenCross", GOTItemGate.class);
		registerBlock(stairsChalkBrick, "stairsChalkBrick");
		registerBlock(slabSingle9, "slabSingle9", GOTBlockSlabBase.SlabItems.Slab9Single.class);
		registerBlock(slabDouble9, "slabDouble9", GOTBlockSlabBase.SlabItems.Slab9Double.class);
		registerBlock(gateWesteros, "gateWesteros", GOTItemGate.class);
		registerBlock(pressurePlateChalk, "pressurePlateChalk");
		registerBlock(buttonChalk, "buttonChalk");
		registerBlock(wallStoneV, "wallStoneV", GOTItemBlockMetadata.class);
		registerBlock(stairsStoneBrickMossy, "stairsStoneBrickMossy");
		registerBlock(stairsStoneBrickCracked, "stairsStoneBrickCracked");
		registerBlock(slabSingleV, "slabSingleV", GOTBlockSlabBase.SlabItems.SlabVSingle.class);
		registerBlock(slabDoubleV, "slabDoubleV", GOTBlockSlabBase.SlabItems.SlabVDouble.class);
		registerBlock(stairsStone, "stairsStone");
		registerBlock(stairsBasalt, "stairsBasalt");
		registerBlock(stairsAndesite, "stairsAndesite");
		registerBlock(stairsRhyolite, "stairsRhyolite");
		registerBlock(stairsDiorite, "stairsDiorite");
		registerBlock(stairsGranite, "stairsGranite");
		registerBlock(stairsChalk, "stairsChalk");
		registerBlock(gateEssos, "gateEssos", GOTItemGate.class);
		registerBlock(clayTile, "clayTile");
		registerBlock(clayTileDyed, "clayTileDyed", GOTItemBlockMetadata.class);
		registerBlock(slabClayTileSingle, "slabClayTileSingle", GOTBlockSlabBase.SlabItems.ClayTileSingle.class);
		registerBlock(slabClayTileDouble, "slabClayTileDouble", GOTBlockSlabBase.SlabItems.ClayTileDouble.class);
		registerBlock(slabClayTileDyedSingle1, "slabClayTileDyedSingle1", GOTBlockSlabBase.SlabItems.ClayTileDyedSingle.class);
		registerBlock(slabClayTileDyedDouble1, "slabClayTileDyedDouble1", GOTBlockSlabBase.SlabItems.ClayTileDyedDouble.class);
		registerBlock(slabClayTileDyedSingle2, "slabClayTileDyedSingle2", GOTBlockSlabBase.SlabItems.ClayTileDyed2Single.class);
		registerBlock(slabClayTileDyedDouble2, "slabClayTileDyedDouble2", GOTBlockSlabBase.SlabItems.ClayTileDyed2Double.class);
		registerBlock(stairsClayTile, "stairsClayTile");
		registerBlock(stairsClayTileDyedWhite, "stairsClayTileDyedWhite");
		registerBlock(stairsClayTileDyedOrange, "stairsClayTileDyedOrange");
		registerBlock(stairsClayTileDyedMagenta, "stairsClayTileDyedMagenta");
		registerBlock(stairsClayTileDyedLightBlue, "stairsClayTileDyedLightBlue");
		registerBlock(stairsClayTileDyedYellow, "stairsClayTileDyedYellow");
		registerBlock(stairsClayTileDyedLime, "stairsClayTileDyedLime");
		registerBlock(stairsClayTileDyedPink, "stairsClayTileDyedPink");
		registerBlock(stairsClayTileDyedGray, "stairsClayTileDyedGray");
		registerBlock(stairsClayTileDyedLightGray, "stairsClayTileDyedLightGray");
		registerBlock(stairsClayTileDyedCyan, "stairsClayTileDyedCyan");
		registerBlock(stairsClayTileDyedPurple, "stairsClayTileDyedPurple");
		registerBlock(stairsClayTileDyedBlue, "stairsClayTileDyedBlue");
		registerBlock(stairsClayTileDyedBrown, "stairsClayTileDyedBrown");
		registerBlock(stairsClayTileDyedGreen, "stairsClayTileDyedGreen");
		registerBlock(stairsClayTileDyedRed, "stairsClayTileDyedRed");
		registerBlock(stairsClayTileDyedBlack, "stairsClayTileDyedBlack");
		registerBlock(furBed, "furBed");
		registerBlock(kebabStand, "kebabStand", GOTItemKebabStand.class);
		registerBlock(kebabStandSand, "kebabStandSand", GOTItemKebabStand.class);
		registerBlock(gateSothoryos, "gateSothoryos", GOTItemGate.class);
		registerBlock(gateSilver, "gateSilver", GOTItemGate.class);
		registerBlock(gateGold, "gateGold", GOTItemGate.class);
		registerBlock(gateValyrian, "gateValyrian", GOTItemGate.class);
		registerBlock(brick5, "brick5", GOTItemBlockMetadata.class);
		registerBlock(stairsMudBrick, "stairsMudBrick");
		registerBlock(leekCrop, "leek");
		registerBlock(turnipCrop, "turnip");
		registerBlock(stairsCypress, "stairsCypress");
		registerBlock(stairsOlive, "stairsOlive");
		registerBlock(slabSingle10, "slabSingle10", GOTBlockSlabBase.SlabItems.Slab10Single.class);
		registerBlock(slabDouble10, "slabDouble10", GOTBlockSlabBase.SlabItems.Slab10Double.class);
		registerBlock(driedReeds, "driedReeds", GOTItemReeds.class);
		registerBlock(redBrick, "redBrick", GOTItemBlockMetadata.class);
		registerBlock(stairsBrickMossy, "stairsBrickMossy");
		registerBlock(stairsBrickCracked, "stairsBrickCracked");
		registerBlock(grapevine, "grapevine");
		registerBlock(grapevineRed, "grapevineRed");
		registerBlock(grapevineWhite, "grapevineWhite");
		registerBlock(wood7, "wood7", GOTItemBlockMetadata.class);
		registerBlock(leaves7, "leaves7", GOTItemLeaves.class);
		registerBlock(sapling7, "sapling7", GOTItemBlockMetadata.class);
		registerBlock(woodBeam7, "woodBeam7", GOTItemBlockMetadata.class);
		registerBlock(stairsAspen, "stairsAspen");
		registerBlock(mirkVines, "mirkVines", GOTItemVine.class);
		registerBlock(stairsGreenOak, "stairsGreenOak");
		registerBlock(stairsFotinia, "stairsFotinia");
		registerBlock(stairsAlmond, "stairsAlmond");
		registerBlock(slabSingleDirt, "slabSingleDirt", GOTBlockSlabBase.SlabItems.DirtSingle.class);
		registerBlock(slabDoubleDirt, "slabDoubleDirt", GOTBlockSlabBase.SlabItems.DirtDouble.class);
		registerBlock(slabSingleSand, "slabSingleSand", GOTBlockSlabBase.SlabItems.SandSingle.class);
		registerBlock(slabDoubleSand, "slabDoubleSand", GOTBlockSlabBase.SlabItems.SandDouble.class);
		registerBlock(slabSingleGravel, "slabSingleGravel", GOTBlockSlabBase.SlabItems.GravelSingle.class);
		registerBlock(slabDoubleGravel, "slabDoubleGravel", GOTBlockSlabBase.SlabItems.GravelDouble.class);
		registerBlock(asshaiFlower, "asshaiFlower");
		registerBlock(blackroot, "blackroot");
		registerBlock(wood8, "wood8", GOTItemBlockMetadata.class);
		registerBlock(leaves8, "leaves8", GOTItemLeaves.class);
		registerBlock(sapling8, "sapling8", GOTItemBlockMetadata.class);
		registerBlock(planks3, "planks3", GOTItemBlockMetadata.class);
		registerBlock(fence3, "fence3", GOTItemBlockMetadata.class);
		registerBlock(woodSlabSingle5, "woodSlabSingle5", GOTBlockSlabBase.SlabItems.WoodSlab5Single.class);
		registerBlock(woodSlabDouble5, "woodSlabDouble5", GOTBlockSlabBase.SlabItems.WoodSlab5Double.class);
		registerBlock(woodBeam8, "woodBeam8", GOTItemBlockMetadata.class);
		registerBlock(stairsPlum, "stairsPlum");
		registerBlock(fallenLeaves4, "fallenLeaves4", GOTItemFallenLeaves.class);
		registerBlock(slabSingle11, "slabSingle11", GOTBlockSlabBase.SlabItems.Slab11Single.class);
		registerBlock(slabDouble11, "slabDouble11", GOTBlockSlabBase.SlabItems.Slab11Double.class);
		registerBlock(whiteSand, "whiteSand");
		registerBlock(whiteSandstone, "whiteSandstone");
		registerBlock(stairsWhiteSandstone, "stairsWhiteSandstone");
		registerBlock(treasureCopper, "treasureCopper", GOTItemTreasurePile.class);
		registerBlock(treasureSilver, "treasureSilver", GOTItemTreasurePile.class);
		registerBlock(treasureGold, "treasureGold", GOTItemTreasurePile.class);
		registerBlock(chestBasket, "chestBasket");
		registerBlock(marigold, "marigold");
		registerBlock(yitiFlower, "yitiFlower", GOTItemBlockMetadata.class);
		registerBlock(stairsCobblestoneMossy, "stairsCobblestoneMossy");
		registerBlock(marzipanBlock, "marzipanBlock");
		registerBlock(wallClayTile, "wallClayTile", GOTItemBlockMetadata.class);
		registerBlock(wallClayTileDyed, "wallClayTileDyed", GOTItemBlockMetadata.class);
		registerBlock(ceramicMugBlock, "ceramicMug");
		registerBlock(gobletGoldBlock, "gobletGold");
		registerBlock(gobletSilverBlock, "gobletSilver");
		registerBlock(gobletCopperBlock, "gobletCopper");
		registerBlock(gobletWoodBlock, "gobletWood");
		registerBlock(skullCupBlock, "skullCup");
		registerBlock(wineGlassBlock, "wineGlass");
		registerBlock(glassBottleBlock, "glassBottle");
		registerBlock(aleHornBlock, "aleHorn");
		registerBlock(aleHornGoldBlock, "aleHornGold");
		registerBlock(woodBeamS, "woodBeamS", GOTItemBlockMetadata.class);
		registerBlock(birdCage, "birdCage", GOTItemAnimalJar.class);
		registerBlock(birdCageWood, "birdCageWood", GOTItemAnimalJar.class);
		registerBlock(gateIbben, "gateIbben", GOTItemGate.class);
		registerBlock(signCarved, "signCarved");
		registerBlock(signCarvedGlowing, "signCarvedGlowing");
		registerBlock(smoothStoneV, "smoothStoneV", GOTItemBlockMetadata.class);
		registerBlock(smoothStone, "smoothStone", GOTItemBlockMetadata.class);
		registerBlock(slabSingle12, "slabSingle12", GOTBlockSlabBase.SlabItems.Slab12Single.class);
		registerBlock(slabDouble12, "slabDouble12", GOTBlockSlabBase.SlabItems.Slab12Double.class);
		registerBlock(stairsYiTiBrick, "stairsYiTiBrick");
		registerBlock(stairsYiTiBrickMossy, "stairsYiTiBrickMossy");
		registerBlock(stairsYiTiBrickCracked, "stairsYiTiBrickCracked");
		registerBlock(stairsYiTiBrickFlowers, "stairsYiTiBrickFlowers");
		registerBlock(brick6, "brick6", GOTItemBlockMetadata.class);
		registerBlock(tableYiTi, "tableYiTi");
		registerBlock(stairsYiTiBrickRed, "stairsYiTiBrickRed");
		registerBlock(stairsRedwood, "stairsRedwood");
		registerBlock(wildFire, "wildFire");
		registerBlock(wildFireJar, "wildFireJar", GOTItemWildFireJar.class);
		registerBlock(daub, "daub");
		registerBlock(gateYiTi, "gateYiTi", GOTItemGate.class);
		registerBlock(yamCrop, "yam");
		registerBlock(kebabBlock, "kebabBlock");
		registerBlock(stairsPomegranate, "stairsPomegranate");
		registerBlock(oreSalt, "oreSalt");
		registerBlock(fenceGateSpruce, "fenceGateSpruce");
		registerBlock(fenceGateBirch, "fenceGateBirch");
		registerBlock(fenceGateJungle, "fenceGateJungle");
		registerBlock(fenceGateAcacia, "fenceGateAcacia");
		registerBlock(fenceGateDarkOak, "fenceGateDarkOak");
		registerBlock(fenceGateIbbinia, "fenceGateIbbinia");
		registerBlock(fenceGateCatalpa, "fenceGateCatalpa");
		registerBlock(fenceGateUlthos, "fenceGateUlthos");
		registerBlock(fenceGateCharred, "fenceGateCharred");
		registerBlock(fenceGateApple, "fenceGateApple");
		registerBlock(fenceGatePear, "fenceGatePear");
		registerBlock(fenceGateCherry, "fenceGateCherry");
		registerBlock(fenceGateMango, "fenceGateMango");
		registerBlock(fenceGateAramant, "fenceGateAramant");
		registerBlock(fenceGateBeech, "fenceGateBeech");
		registerBlock(fenceGateHolly, "fenceGateHolly");
		registerBlock(fenceGateBanana, "fenceGateBanana");
		registerBlock(fenceGateMaple, "fenceGateMaple");
		registerBlock(fenceGateLarch, "fenceGateLarch");
		registerBlock(fenceGateDatePalm, "fenceGateDatePalm");
		registerBlock(fenceGateMangrove, "fenceGateMangrove");
		registerBlock(fenceGateChestnut, "fenceGateChestnut");
		registerBlock(fenceGateBaobab, "fenceGateBaobab");
		registerBlock(fenceGateCedar, "fenceGateCedar");
		registerBlock(fenceGateFir, "fenceGateFir");
		registerBlock(fenceGatePine, "fenceGatePine");
		registerBlock(fenceGateLemon, "fenceGateLemon");
		registerBlock(fenceGateOrange, "fenceGateOrange");
		registerBlock(fenceGateLime, "fenceGateLime");
		registerBlock(fenceGateMahogany, "fenceGateMahogany");
		registerBlock(fenceGateWillow, "fenceGateWillow");
		registerBlock(fenceGateCypress, "fenceGateCypress");
		registerBlock(fenceGateOlive, "fenceGateOlive");
		registerBlock(fenceGateAspen, "fenceGateAspen");
		registerBlock(fenceGateGreenOak, "fenceGateGreenOak");
		registerBlock(fenceGateFotinia, "fenceGateFotinia");
		registerBlock(fenceGateAlmond, "fenceGateAlmond");
		registerBlock(fenceGateRotten, "fenceGateRotten");
		registerBlock(fenceGatePlum, "fenceGatePlum");
		registerBlock(fenceGateRedwood, "fenceGateRedwood");
		registerBlock(fenceGatePomegranate, "fenceGatePomegranate");
		registerBlock(stalactiteIce, "stalactiteIce", GOTItemBlockMetadata.class);
		registerBlock(stalactiteObsidian, "stalactiteObsidian", GOTItemBlockMetadata.class);
		registerBlock(millstone, "millstone");
		registerBlock(oreGem, "oreGem", GOTItemBlockMetadata.class);
		registerBlock(blockGem, "blockGem", GOTItemBlockMetadata.class);
		registerBlock(coralReef, "coralReef");
		registerBlock(bookshelfStorage, "bookshelfStorage");
		registerBlock(glass, "glass");
		registerBlock(glassPane, "glassPane");
		registerBlock(stainedGlass, "stainedGlass", GOTItemBlockMetadata.class);
		registerBlock(stainedGlassPane, "stainedGlassPane", GOTItemBlockMetadata.class);
		registerBlock(rope, "rope");
		registerBlock(sarbacaneTrapObsidian, "sarbacaneTrapObsidian");
		registerBlock(slabSingle6, "slabSingle6", GOTBlockSlabBase.SlabItems.Slab13Single.class);
		registerBlock(slabDouble6, "slabDouble6", GOTBlockSlabBase.SlabItems.Slab13Double.class);
		registerBlock(stairsPalm, "stairsPalm");
		registerBlock(fenceGatePalm, "fenceGatePalm");
		registerBlock(wood9, "wood9", GOTItemBlockMetadata.class);
		registerBlock(leaves9, "leaves9", GOTItemLeaves.class);
		registerBlock(sapling9, "sapling9", GOTItemBlockMetadata.class);
		registerBlock(woodBeam9, "woodBeam9", GOTItemBlockMetadata.class);
		registerBlock(stairsDragon, "stairsDragon");
		registerBlock(fenceGateDragon, "fenceGateDragon");
		registerBlock(woodPlateBlock, "woodPlate");
		registerBlock(ceramicPlateBlock, "ceramicPlate");
		registerBlock(doorSpruce, "doorSpruce", GOTItemDoor.class);
		registerBlock(doorBirch, "doorBirch", GOTItemDoor.class);
		registerBlock(doorJungle, "doorJungle", GOTItemDoor.class);
		registerBlock(doorAcacia, "doorAcacia", GOTItemDoor.class);
		registerBlock(doorDarkOak, "doorDarkOak", GOTItemDoor.class);
		registerBlock(doorIbbinia, "doorIbbinia", GOTItemDoor.class);
		registerBlock(doorCatalpa, "doorCatalpa", GOTItemDoor.class);
		registerBlock(doorUlthos, "doorUlthos", GOTItemDoor.class);
		registerBlock(doorCharred, "doorCharred", GOTItemDoor.class);
		registerBlock(doorApple, "doorApple", GOTItemDoor.class);
		registerBlock(doorPear, "doorPear", GOTItemDoor.class);
		registerBlock(doorCherry, "doorCherry", GOTItemDoor.class);
		registerBlock(doorMango, "doorMango", GOTItemDoor.class);
		registerBlock(doorAramant, "doorAramant", GOTItemDoor.class);
		registerBlock(doorBeech, "doorBeech", GOTItemDoor.class);
		registerBlock(doorHolly, "doorHolly", GOTItemDoor.class);
		registerBlock(doorBanana, "doorBanana", GOTItemDoor.class);
		registerBlock(doorMaple, "doorMaple", GOTItemDoor.class);
		registerBlock(doorLarch, "doorLarch", GOTItemDoor.class);
		registerBlock(doorDatePalm, "doorDatePalm", GOTItemDoor.class);
		registerBlock(doorMangrove, "doorMangrove", GOTItemDoor.class);
		registerBlock(doorChestnut, "doorChestnut", GOTItemDoor.class);
		registerBlock(doorBaobab, "doorBaobab", GOTItemDoor.class);
		registerBlock(doorCedar, "doorCedar", GOTItemDoor.class);
		registerBlock(doorFir, "doorFir", GOTItemDoor.class);
		registerBlock(doorPine, "doorPine", GOTItemDoor.class);
		registerBlock(doorLemon, "doorLemon", GOTItemDoor.class);
		registerBlock(doorOrange, "doorOrange", GOTItemDoor.class);
		registerBlock(doorLime, "doorLime", GOTItemDoor.class);
		registerBlock(doorMahogany, "doorMahogany", GOTItemDoor.class);
		registerBlock(doorWillow, "doorWillow", GOTItemDoor.class);
		registerBlock(doorCypress, "doorCypress", GOTItemDoor.class);
		registerBlock(doorOlive, "doorOlive", GOTItemDoor.class);
		registerBlock(doorAspen, "doorAspen", GOTItemDoor.class);
		registerBlock(doorGreenOak, "doorGreenOak", GOTItemDoor.class);
		registerBlock(doorFotinia, "doorFotinia", GOTItemDoor.class);
		registerBlock(doorAlmond, "doorAlmond", GOTItemDoor.class);
		registerBlock(doorPlum, "doorPlum", GOTItemDoor.class);
		registerBlock(doorRedwood, "doorRedwood", GOTItemDoor.class);
		registerBlock(doorPomegranate, "doorPomegranate", GOTItemDoor.class);
		registerBlock(doorPalm, "doorPalm", GOTItemDoor.class);
		registerBlock(doorDragon, "doorDragon", GOTItemDoor.class);
		registerBlock(doorRotten, "doorRotten", GOTItemDoor.class);
		registerBlock(doorKanuka, "doorKanuka", GOTItemDoor.class);
		registerBlock(doorWeirwood, "doorWeirwood", GOTItemDoor.class);
		registerBlock(boneBlock, "boneBlock");
		registerBlock(slabBoneSingle, "slabBoneSingle", GOTBlockSlabBase.SlabItems.BoneSingle.class);
		registerBlock(slabBoneDouble, "slabBoneDouble", GOTBlockSlabBase.SlabItems.BoneDouble.class);
		registerBlock(stairsBone, "stairsBone");
		registerBlock(wallBone, "wallBone", GOTItemBlockMetadata.class);
		registerBlock(chestEssos, "chestEssos");
		registerBlock(spawnerChestAncientEssos, "spawnerChestAncientEssos");
		registerBlock(redClay, "redClay");
		registerBlock(chain, "chain");
		registerBlock(stairsKanuka, "stairsKanuka");
		registerBlock(stairsWeirwood, "stairsWeirwood");
		registerBlock(fenceGateKanuka, "fenceGateKanuka");
		registerBlock(fenceGateWeirwood, "fenceGateWeirwood");
		registerBlock(brickIce, "brickIce");
		registerBlock(tableArryn, "tableArryn");
		registerBlock(tableRiverlands, "tableRiverlands");
		registerBlock(tableWesterlands, "tableWesterlands");
		registerBlock(tableDragonstone, "tableDragonstone");
		registerBlock(tableCrownlands, "tableCrownlands");
		registerBlock(tableStormlands, "tableStormlands");
		registerBlock(tableReach, "tableReach");
		registerBlock(tableDorne, "tableDorne");
		registerBlock(tableIronborn, "tableIronborn");
		registerBlock(tableVolantis, "tableVolantis");
		registerBlock(tableBraavos, "tableBraavos");
		registerBlock(tablePentos, "tablePentos");
		registerBlock(tableNorvos, "tableNorvos");
		registerBlock(tableTyrosh, "tableTyrosh");
		registerBlock(tableLorath, "tableLorath");
		registerBlock(tableQohor, "tableQohor");
		registerBlock(tableMyr, "tableMyr");
		registerBlock(tableLys, "tableLys");
		registerBlock(tableQarth, "tableQarth");
		registerBlock(tableGhiscar, "tableGhiscar");
		registerBlock(tableAsshai, "tableAsshai");
		registerBlock(tableIbben, "tableIbben");
		registerBlock(trapdoorSpruce, "trapdoorSpruce");
		registerBlock(trapdoorBirch, "trapdoorBirch");
		registerBlock(trapdoorCatalpa, "trapdoorCatalpa");
		registerBlock(trapdoorJungle, "trapdoorJungle");
		registerBlock(trapdoorAcacia, "trapdoorAcacia");
		registerBlock(trapdoorDarkOak, "trapdoorDarkOak");
		registerBlock(trapdoorIbbinia, "trapdoorIbbinia");
		registerBlock(trapdoorUlthos, "trapdoorUlthos");
		registerBlock(trapdoorCharred, "trapdoorCharred");
		registerBlock(trapdoorApple, "trapdoorApple");
		registerBlock(trapdoorPear, "trapdoorPear");
		registerBlock(trapdoorCherry, "trapdoorCherry");
		registerBlock(trapdoorMango, "trapdoorMango");
		registerBlock(trapdoorAramant, "trapdoorAramant");
		registerBlock(trapdoorBeech, "trapdoorBeech");
		registerBlock(trapdoorHolly, "trapdoorHolly");
		registerBlock(trapdoorBanana, "trapdoorBanana");
		registerBlock(trapdoorMaple, "trapdoorMaple");
		registerBlock(trapdoorLarch, "trapdoorLarch");
		registerBlock(trapdoorDatePalm, "trapdoorDatePalm");
		registerBlock(trapdoorMangrove, "trapdoorMangrove");
		registerBlock(trapdoorChestnut, "trapdoorChestnut");
		registerBlock(trapdoorBaobab, "trapdoorBaobab");
		registerBlock(trapdoorCedar, "trapdoorCedar");
		registerBlock(trapdoorFir, "trapdoorFir");
		registerBlock(trapdoorPine, "trapdoorPine");
		registerBlock(trapdoorLemon, "trapdoorLemon");
		registerBlock(trapdoorOrange, "trapdoorOrange");
		registerBlock(trapdoorLime, "trapdoorLime");
		registerBlock(trapdoorMahogany, "trapdoorMahogany");
		registerBlock(trapdoorWillow, "trapdoorWillow");
		registerBlock(trapdoorCypress, "trapdoorCypress");
		registerBlock(trapdoorOlive, "trapdoorOlive");
		registerBlock(trapdoorAspen, "trapdoorAspen");
		registerBlock(trapdoorGreenOak, "trapdoorGreenOak");
		registerBlock(trapdoorFotinia, "trapdoorFotinia");
		registerBlock(trapdoorAlmond, "trapdoorAlmond");
		registerBlock(trapdoorPlum, "trapdoorPlum");
		registerBlock(trapdoorRedwood, "trapdoorRedwood");
		registerBlock(trapdoorPomegranate, "trapdoorPomegranate");
		registerBlock(trapdoorPalm, "trapdoorPalm");
		registerBlock(trapdoorDragon, "trapdoorDragon");
		registerBlock(trapdoorKanuka, "trapdoorKanuka");
		registerBlock(trapdoorRotten, "trapdoorRotten");
		registerBlock(trapdoorWeirwood, "trapdoorWeirwood");
		registerBlock(cobblebrick, "cobblebrick", GOTItemBlockMetadata.class);
		registerBlock(bank, "bank");
		registerBlock(barrier, "barrier");
		registerBlock(buttonLabradorite, "buttonLabradorite");
		registerBlock(stairsLabradorite, "stairsLabradorite");
		registerBlock(stairsLabradoriteBrick, "stairsLabradoriteBrick");
		registerBlock(stairsLabradoriteBrickCracked, "stairsLabradoriteBrickCracked");
		registerBlock(stairsLabradoriteBrickMossy, "stairsLabradoriteBrickMossy");
		registerBlock(pressurePlateLabradorite, "pressurePlateLabradorite");
		for (GOTEnumDyeColor color : GOTEnumDyeColor.values()) {
			concretePowder.put(color, new GOTBlockConcretePowder(color));
			concrete.put(color, new GOTBlockConcrete(color));
			registerBlock(concretePowder.get(color), "concrete_powder_" + color.getUnlocalizedName(), GOTItemBlockConcrete.class);
			registerBlock(concrete.get(color), "concrete_" + color.getUnlocalizedName(), GOTItemBlockConcrete.class);
		}
		registerBlock(tableDothraki, "tableDothraki");
		registerBlock(tableJogos, "tableJogos");
		registerBlock(tableMossovy, "tableMossovy");
		registerBlock(kelp, "kelp", GOTItemKelp.class);
		registerBlock(ricePlant, "rice");
		registerBlock(leavesSnowy, "leavesSnowy");
	}
}