package got.common.database;

import got.common.GOTConfig;
import got.common.enchant.GOTEnchantmentHelper;
import got.common.entity.other.GOTEntityNPC;
import got.common.entity.other.utils.GOTTradeEntry;
import got.common.entity.other.utils.GOTTradeEntryBarrel;
import got.common.entity.other.utils.GOTTradeSellResult;
import got.common.item.other.GOTItemMug;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MathHelper;

import java.util.*;

public class GOTTradeEntries {
	public static final GOTTradeEntries BAELISH_BUY;
	public static final GOTTradeEntries C_ALCHEMIST_BUY;
	public static final GOTTradeEntries C_BAKER_BUY;
	public static final GOTTradeEntries C_BAKER_SELL;
	public static final GOTTradeEntries C_BARTENDER_BUY;
	public static final GOTTradeEntries C_BARTENDER_SELL;
	public static final GOTTradeEntries C_BLACKSMITH_SELL;
	public static final GOTTradeEntries C_TRAMP_BUY;
	public static final GOTTradeEntries C_TRAMP_SELL;
	public static final GOTTradeEntries C_BREWER_BUY;
	public static final GOTTradeEntries C_BREWER_SELL;
	public static final GOTTradeEntries C_BUTCHER_BUY;
	public static final GOTTradeEntries C_BUTCHER_SELL;
	public static final GOTTradeEntries C_FARMER_BUY;
	public static final GOTTradeEntries C_FARMER_SELL;
	public static final GOTTradeEntries C_FISHMONGER_BUY;
	public static final GOTTradeEntries C_FISHMONGER_SELL;
	public static final GOTTradeEntries C_FLORIST_BUY;
	public static final GOTTradeEntries C_GOLDSMITH_BUY;
	public static final GOTTradeEntries C_GOLDSMITH_SELL;
	public static final GOTTradeEntries C_LUMBERMAN_BUY;
	public static final GOTTradeEntries C_LUMBERMAN_SELL;
	public static final GOTTradeEntries C_MAESTER_BUY;
	public static final GOTTradeEntries C_MAESTER_SELL;
	public static final GOTTradeEntries C_MINER_BUY;
	public static final GOTTradeEntries C_MINER_SELL;
	public static final GOTTradeEntries C_SHAMAN_BUY;
	public static final GOTTradeEntries C_SHAMAN_SELL;
	public static final GOTTradeEntries CROWNLANDS_ALCHEMIST_BUY;
	public static final GOTTradeEntries DAVOS_BUY;
	public static final GOTTradeEntries ESSOS_BLACKSMITH_BUY;
	public static final GOTTradeEntries SUD_MASON_BUY;
	public static final GOTTradeEntries IBBEN_BLACKSMITH_BUY;
	public static final GOTTradeEntries IBBEN_MASON_BUY;
	public static final GOTTradeEntries LHAZAR_BLACKSMITH_BUY;
	public static final GOTTradeEntries MOSSOVY_BLACKSMITH_BUY;
	public static final GOTTradeEntries QOHOR_BLACKSMITH_BUY;
	public static final GOTTradeEntries SOTHORYOS_BLACKSMITH_BUY;
	public static final GOTTradeEntries SUMMER_BLACKSMITH_BUY;
	public static final GOTTradeEntries THENN_BLACKSMITH_BUY;
	public static final GOTTradeEntries WESTEROS_BLACKSMITH_BUY;
	public static final GOTTradeEntries NORD_MASON_BUY;
	public static final GOTTradeEntries YITI_BLACKSMITH_BUY;
	public static final GOTTradeEntries YITI_MASON_BUY;

	private static final int VALYRIAN_INGOT_SELL = 512;
	private static final int GOLD_INGOT_SELL = 128;
	private static final int SILVER_INGOT_SELL = 32;
	private static final int VALYRIAN_INGOT_BUY = 768;
	private static final int GOLD_INGOT_BUY = 192;
	private static final int SILVER_INGOT_BUY = 48;
	private static final int AMBER_SELL = 30;
	private static final int AMETHYST_SELL = 20;
	private static final int DIAMOND_SELL = 60;
	private static final int EMERALD_SELL = 40;
	private static final int OPAL_SELL = 30;
	private static final int PEARL_SELL = 30;
	private static final int RUBY_SELL = 30;
	private static final int SAPPHIRE_SELL = 30;
	private static final int TOPAZ_SELL = 20;
	private static final int AMBER_BUY = 45;
	private static final int AMETHYST_BUY = 30;
	private static final int DIAMOND_BUY = 90;
	private static final int EMERALD_BUY = 60;
	private static final int OPAL_BUY = 45;
	private static final int PEARL_BUY = 45;
	private static final int RUBY_BUY = 45;
	private static final int SAPPHIRE_BUY = 45;
	private static final int TOPAZ_BUY = 30;

	private static final List<GOTTradeEntry> BAELISH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_ALCHEMIST_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BAKER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BAKER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BARTENDER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BARTENDER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BLACKSMITH_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BOMZH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BOMZH_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BREWER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BREWER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BUTCHER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_BUTCHER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_FARMER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_FARMER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_FISHMONGER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_FISHMONGER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_FLORIST_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_GOLDSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_GOLDSMITH_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_MAESTER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_MAESTER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_MINER_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_MINER_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_SHAMAN_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_SHAMAN_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_LUMBERMAN_S_L = new ArrayList<>();
	private static final List<GOTTradeEntry> C_LUMBERMAN_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> IBBEN_MASON_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> YITI_MASON_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> SUD_MASON_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> NORD_MASON_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> ESSOS_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> IBBEN_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> LHAZAR_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> MOSSOVY_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> QOHOR_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> SOTHORYOS_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> SUMMER_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> THENN_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> WESTEROS_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> YITI_BLACKSMITH_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> CROWNLANDS_ALCHEMIST_B_L = new ArrayList<>();
	private static final List<GOTTradeEntry> DAVOS_B_L = new ArrayList<>();

	static {
		BAELISH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.baelishDagger), 5000));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bottlePoison), 10));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 1), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 10), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 12), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 13), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 2), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 3), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 4), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 5), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 6), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 8), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lingeringPotion, 1, 9), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 1), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 10), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 12), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 13), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 2), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 3), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 4), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 5), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 6), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 8), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 9), 128));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.appleCrumble), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.berryPie), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ceramicPlate), 2));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.cherryPie), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.cornBread), 5));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lemonCake), 15));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.marzipan), 6));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.marzipanBlock), 20));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.marzipanChocolate), 10));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.oliveBread), 6));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.plate), 4));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(Items.bread), 5));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cake), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cookie), 4));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.almond), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.appleGreen), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.cherry), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.clayPlate), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lemon), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.olive), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.salt), 10));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.apple), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 1, 3), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.egg, 2), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.milk_bucket), 4));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.sugar, 2), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 2), 1));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.aleHorn), 5));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.camelCooked), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ceramicMug), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ceramicPlate), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.deerCooked), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.gammon), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.gobletCopper), 3));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.gobletWood), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.kebab), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lemonCake), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mug), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugAle, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugAppleJuice), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugAraq, 1, 9999), 10));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCactusLiqueur, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugChocolate), 4));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCider, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugLemonLiqueur, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugLimeLiqueur, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugMead, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugOrangeJuice), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPerry, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugRedWine, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugWhiteWine, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.muttonCooked), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.oliveBread), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.orange), 3));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.plate), 4));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.plum), 3));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.rabbitCooked), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.rabbitStew), 10));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.shishKebab), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.waterskin), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.woodPlate), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.baked_potato, 2), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.bread), 5));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_beef), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_chicken), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_fished), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_porkchop), 7));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.appleGreen), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.clayMug), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.clayPlate), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.date), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.deerRaw), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.beaverRaw), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.beaverTail), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lemon), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lime), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.muttonRaw), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.orange), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pipeweed, 3), 10));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.rabbitRaw), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.salt), 10));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.apple), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.beef), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.chicken), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.coal, 2, 32767), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.fish), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.porkchop), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.potato, 2), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 2), 1));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.alloySteelIngot), 12));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_ingot), 9));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeIngot), 6));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.copperIngot), 3));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.diamond), 25));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pearl), 25));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sapphire), 12));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.tinIngot), 3));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.coal, 2, 32767), 1));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.leather), 2));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.string, 3), 1));
		C_BOMZH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.saltedFlesh), 7));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.chestnut, 2), 1));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.fur), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.partyHat, 1, 32767), 100));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pipeweed, 3), 10));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.feather), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.flint), 1));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.leather), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.rotten_flesh), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.stick, 8), 1));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat_seeds, 2), 1));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugAle, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugAppleJuice), 6));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugAraq, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugBananaBeer, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugBlackberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugBlueberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCactusLiqueur, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCarrotWine, 1, 9999), 12));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCherryLiqueur, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugChocolate), 6));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCider, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCranberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugElderberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugLemonLiqueur, 1, 9999), 12));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugLimeLiqueur, 1, 9999), 12));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugMangoJuice), 8));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugMead, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugMead, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugMelonLiqueur, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugOrangeJuice), 6));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPerry, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPlumKvass, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPomegranateJuice), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPomegranateWine, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugRaspberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugRedGrapeJuice), 8));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugRedWine, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugSourMilk, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugVodka, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugWhiteGrapeJuice), 8));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugWhiteWine, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugAle, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugAraq, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugCactusLiqueur, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugCarrotWine, 1, 2), 140));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugCherryLiqueur, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugCider, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugLemonLiqueur, 1, 2), 140));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugLimeLiqueur, 1, 2), 140));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugMead, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugPerry, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugPlumKvass, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugPomegranateWine, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugRedWine, 1, 2), 160));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugSourMilk, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugVodka, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTItems.mugWhiteWine, 1, 2), 160));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.cactus), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 1), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 3), 9));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.appleGreen), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.banana), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.cherry), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.date), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.grapeRed), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.grapeWhite), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lemon), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lime), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mango), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.orange), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pear), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.plum), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pomegranate), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.apple), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.carrot), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 15), 9));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 5), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.milk_bucket), 4));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.potato), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.sugar, 2), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 2), 1));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.deerRaw), 4));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.beaverRaw), 3));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.beaverTail), 3));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.gammon), 6));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.muttonRaw), 5));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.rabbitRaw), 4));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.beef), 5));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.chicken), 4));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.leather), 3));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.porkchop), 5));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeDagger), 3));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironDagger), 3));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.salt), 10));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_ingot), 3));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(Items.lead), 4));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 3), 1));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hay_block), 12));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block), 18));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 1), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 3), 10));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.wool), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.almond), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.brandingIron), 16));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.corn), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.cornStalk), 1));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.driedReeds), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.grapeRed), 4));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.grapeWhite), 4));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.leek), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lemon), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lettuce), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lime), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mango), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.orange), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.pipeweedPlant), 10));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.plum), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pomegranate), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.reeds), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.turnip), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.carrot), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 1, 3), 8));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.lead), 8));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 15), 10));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 5), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.milk_bucket), 8));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.potato), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.wheat), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.wheat_seeds), 1));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeHoe), 6));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 6, 15), 1));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_hoe), 8));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.stone_hoe), 1));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sponge), 15));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pearl), 50));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.boat), 5));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 1, 0), 4));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 0), 4));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 1), 6));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 2), 8));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 3), 12));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fishing_rod), 8));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.leather_boots), 5));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 0), 1));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeDagger), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironDagger), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.salt), 10));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_ingot), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.stick, 8), 1));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.string, 3), 1));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 0), 15));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 1), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 4), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 5), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 0), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 1), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 2), 6));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 3), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 4), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 5), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 6), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 7), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 8), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.yellow_flower, 1, 8), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bluebell, 1, 0), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.doubleFlower, 1, 0), 25));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.doubleFlower, 1, 1), 10));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.doubleFlower, 1, 2), 45));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.doubleFlower, 1, 3), 45));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.essosFlower, 1, 0), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.essosFlower, 1, 1), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.essosFlower, 1, 2), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.essosFlower, 1, 3), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.marigold, 1, 0), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.yitiFlower, 1, 0), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.yitiFlower, 1, 1), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.yitiFlower, 1, 2), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.yitiFlower, 1, 3), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.yitiFlower, 1, 4), 20));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.birdCage, 1, 2), SILVER_INGOT_BUY * 6));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.birdCage, 1, 3), GOLD_INGOT_BUY * 6));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.chandelier, 1, 2), SILVER_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.chandelier, 1, 3), GOLD_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.gobletGold), GOLD_INGOT_BUY * 2));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.gobletSilver), SILVER_INGOT_BUY * 2));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.goldBars), GOLD_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.goldRing), GOLD_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.silverBars), SILVER_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.silverRing), SILVER_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianRing), VALYRIAN_INGOT_BUY));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.amber), AMBER_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.amethyst), AMETHYST_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.diamond), DIAMOND_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.emerald), EMERALD_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.opal), OPAL_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pearl), PEARL_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ruby), RUBY_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sapphire), SAPPHIRE_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.silverIngot), SILVER_INGOT_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.topaz), TOPAZ_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianIngot), VALYRIAN_INGOT_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.gold_ingot), GOLD_INGOT_SELL));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 4), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 2), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 4), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitLeaves, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitLeaves, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitLeaves, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitSapling, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitSapling, 1, 1), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitSapling, 1, 2), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitWood, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitWood, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.fruitWood, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves2, 1, 1), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves2, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves2, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves3, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves3, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves3, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves3, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves4, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves4, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves4, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves4, 1, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 1), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 2), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves5, 1, 3), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves6, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves6, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves6, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves6, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves6, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves6, 1, 3), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves7, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves7, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves8, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves8, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves8, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leaves8, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 10), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 12), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 13), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 14), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 14), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 4), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 5), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 6), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 8), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 9), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks1, 4, 9), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 10), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 10), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 11), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 11), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 12), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 15), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 4), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 4), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 5), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 5), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 6), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 6), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 7), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 7), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 8), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks2, 4, 9), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks3, 4, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks3, 4, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks3, 4, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.planks3, 4, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling2, 1, 0), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling2, 1, 1), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling2, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling2, 1, 2), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling3, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling3, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling3, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling3, 1, 2), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling4, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling4, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling4, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling4, 1, 3), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 0), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 1), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 1), 14));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 2), 14));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling5, 1, 3), 14));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling6, 1, 0), 20));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling6, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling6, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling6, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling6, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling6, 1, 3), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling7, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling7, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling8, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling8, 1, 1), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling8, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling8, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood2, 1, 1), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood2, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood2, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood3, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood3, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood3, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood3, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood4, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood4, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood4, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood4, 1, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 1), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 2), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood5, 1, 3), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood6, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood6, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood6, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood6, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood6, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood6, 1, 3), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood7, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood7, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood8, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood8, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood8, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wood8, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam2, 3, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam2, 3, 1), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam2, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam2, 3, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam3, 3, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam3, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam3, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam3, 3, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam4, 3, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam4, 3, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam4, 3, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam4, 3, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 1), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 2), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam5, 3, 3), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam6, 3, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam6, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam6, 3, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam6, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam6, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam6, 3, 3), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam7, 3, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam7, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam8, 3, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam8, 3, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam8, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeam8, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamFruit, 3, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamFruit, 3, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamFruit, 3, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV1, 3, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV1, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV1, 3, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV1, 3, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV1, 3, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV2, 3, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Items.stick, 4), 1));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeAxe), 6));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 6, 15), 1));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_axe), 8));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.shears), 5));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.stone_axe), 1));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bottlePoison), 10));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPlantainBrew), 12));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPoppyMilk), 12));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sulfurMatch), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.book, 1), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.flint_and_steel), 4));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.paper, 2), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.saddle), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.writable_book, 1), 4));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bottlePoison), 5));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPlantainBrew), 6));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPoppyMilk), 6));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sulfurMatch), 1));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.book, 1), 2));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.flint_and_steel), 2));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.paper, 2), 1));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.saddle), 1));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.writable_book, 1), 4));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.amber), AMBER_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.amethyst), AMETHYST_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.diamond), DIAMOND_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.emerald), EMERALD_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.opal), OPAL_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.pearl), PEARL_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ruby), RUBY_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sapphire), SAPPHIRE_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.silverIngot), SILVER_INGOT_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.topaz), TOPAZ_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianIngot), VALYRIAN_INGOT_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(Items.gold_ingot), GOLD_INGOT_BUY));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.torch, 16), 2));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzePickaxe), 6));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.deerCooked), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.muttonCooked), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.rabbitCooked), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bread), 2));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.coal, 2, 32767), 1));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_beef), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_chicken), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_porkchop), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_pickaxe), 8));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.stone_pickaxe), 1));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 3), 6));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bottlePoison), 10));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.dartPoisoned, 4), 10));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugChocolate), 4));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugCocoa, 1, 9999), 12));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mugPoppyMilk), 20));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sapling6, 1, 0), 8));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sarbacane), 25));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.sarbacaneTrap, 4), 5));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosDagger), 12));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosDaggerPoisoned), 20));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.brown_mushroom, 1, 0), 2));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_mushroom, 1, 0), 2));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.banana), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.corn, 2), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.doubleFlower, 2, 2), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.doubleFlower, 2, 3), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.gemsbokHorn), 4));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mango), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.mug), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.obsidianShard), 3));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTItems.rhinoHorn), 5));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.bone), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.glass_bottle), 2));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bomb), 64));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bottlePoison), 10));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.firePot), 32));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sulfurMatch), 1));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.wildFireJar), 128));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.leek), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.leekCrop), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.leekSoup), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.salt), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.saltedFlesh), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_fished), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish), 5));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeCrossbow), 12));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosDagger), 9));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosDaggerPoisoned), 15));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosHammer), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosHorseArmor), 25));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosPike), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosPolearm), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosSpear), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.essosSword), 15));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironCrossbow), 15));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.redSandstone, 8), 12));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.whiteSandstone, 8), 6));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sandstone, 8), 2));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick1, 8, 15), 3));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick3, 1, 15), 4));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick3, 1, 8), 2));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick3, 8, 13), 6));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.pillar1, 4, 15), 6));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.pillar1, 4, 5), 3));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.redSandstone, 8), 4));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.whiteSandstone, 8), 6));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ibbenBoots), 16));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ibbenChestplate), 28));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ibbenHarpoon), 18));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ibbenLeggings), 24));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ibbenSword), 15));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironCrossbow), 15));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailHelmet), 9));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailChestplate), 13));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailLeggings), 11));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailBoots), 7));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.saddle), 15));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.cobblestone, 8), 1));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.dirt, 8), 1));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 1), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 1), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stone, 8), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stonebrick, 8, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick1, 8, 4), 3));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick5, 1, 3), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.rock, 8, 2), 3));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.thatch, 4, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.thatch, 4, 1), 4));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.thatchFloor, 16, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV1, 3, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.woodBeamV1, 3, 1), 2));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeCrossbow), 12));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarBoots), 17));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarChestplate), 32));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarClub), 15));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarDagger), 8));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarDaggerPoisoned), 14));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarHelmet), 20));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarLeggings), 26));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarSpear), 15));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.lhazarSword), 15));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.tableLhazar), 100));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailHelmet), 9));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailChestplate), 13));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailLeggings), 11));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailBoots), 7));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironCrossbow), 15));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironDagger), 9));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironHorseArmor), 25));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironSpear), 16));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.iron_sword), 15));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianBook), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianDagger), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianDaggerPoisoned), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianHammer), VALYRIAN_INGOT_BUY * 4));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianSpear), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianSword), VALYRIAN_INGOT_BUY * 3));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianHelmet), VALYRIAN_INGOT_BUY * 5));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianChestplate), VALYRIAN_INGOT_BUY * 8));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianLeggings), VALYRIAN_INGOT_BUY * 7));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianBoots), VALYRIAN_INGOT_BUY * 4));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianChainmailHelmet), VALYRIAN_INGOT_BUY * 4));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianChainmailChestplate), VALYRIAN_INGOT_BUY * 6));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianChainmailLeggings), VALYRIAN_INGOT_BUY * 6));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.valyrianChainmailBoots), VALYRIAN_INGOT_BUY * 3));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosBattleaxe), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosBoots), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosChestplate), 32));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosDagger), 12));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosHammer), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosHelmet), 20));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosHelmetChieftain), 40));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosLeggings), 25));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosPike), 18));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosSpear), 15));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.sothoryosSword), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.tableSothoryos), 100));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeCrossbow), 12));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerBoots), 17));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerChestplate), 32));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerDagger), 8));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerDaggerPoisoned), 14));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerHelmet), 20));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerLeggings), 26));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerPike), 15));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerSpear), 15));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.summerSword), 14));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.tableSummer), 100));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailHelmet), 9));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailChestplate), 13));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailLeggings), 11));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailBoots), 7));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironCrossbow), 15));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.wildlingDagger), 9));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.wildlingSpear), 16));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.wildlingSword), 15));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailHelmet), 9));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailChestplate), 13));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailLeggings), 11));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeChainmailBoots), 7));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.bow), 12));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironCrossbow), 15));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.westerosDagger), 9));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.westerosHammer), 18));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.westerosHorseArmor), 25));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.westerosSpear), 16));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.westerosSword), 15));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.cobblestone, 8), 1));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stone, 8), 2));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stonebrick, 1, 8), 2));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick1, 1, 5), 2));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick1, 8, 1), 3));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick2, 8, 11), 12));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick4, 1, 6), 12));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick5, 8, 8), 3));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.pillar1, 4, 6), 3));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.rock, 8, 0), 16));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.rock, 8, 1), 3));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.blacksmithHammer), 18));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bomb), 64));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.bronzeBars, 8), 20));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.bronzeCrossbow), 12));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.crossbowBolt, 4), 3));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.ironCrossbow), 15));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.tableYiTi), 100));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiBattleaxe), 18));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiBoots), 17));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiBootsFrontier), 19));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiBootsSamurai), 21));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiChestplate), 32));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiChestplateFrontier), 35));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiChestplateSamurai), 37));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiDagger), 9));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiHelmet), 20));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiHelmetFrontier), 22));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiHelmetSamurai), 24));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiHorseArmor), 37));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiLeggings), 26));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiLeggingsFrontier), 28));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiLeggingsSamurai), 30));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiPike), 16));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiPolearm), 16));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiSpear), 16));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.yitiSword), 15));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTItems.firePot), 32));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.cobblestone, 8), 1));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sandstone, 8), 4));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stone, 8), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stonebrick, 1, 8), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick5, 1, 12), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick5, 1, 15), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick5, 8, 11), 3));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick6, 1, 2), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.brick6, 8, 1), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.pillar2, 4, 8), 3));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.pillar2, 4, 9), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.redSandstone, 8), 12));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.rock, 8, 4), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.tableYiTi), 100));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTBlocks.whiteSandstone, 8), 6));

		BAELISH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, BAELISH_B_L);
		C_ALCHEMIST_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_ALCHEMIST_B_L);
		C_BAKER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BAKER_B_L);
		C_BAKER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BAKER_S_L);
		C_BARTENDER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BARTENDER_B_L);
		C_BARTENDER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BARTENDER_S_L);
		C_BLACKSMITH_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BLACKSMITH_S_L);
		C_TRAMP_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BOMZH_B_L);
		C_TRAMP_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BOMZH_S_L);
		C_BREWER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BREWER_B_L);
		C_BREWER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BREWER_S_L);
		C_BUTCHER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BUTCHER_B_L);
		C_BUTCHER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BUTCHER_S_L);
		C_FARMER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_FARMER_B_L);
		C_FARMER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_FARMER_S_L);
		C_FISHMONGER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_FISHMONGER_B_L);
		C_FISHMONGER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_FISHMONGER_S_L);
		C_FLORIST_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_FLORIST_B_L);
		C_GOLDSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_GOLDSMITH_B_L);
		C_GOLDSMITH_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_GOLDSMITH_S_L);
		C_LUMBERMAN_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_LUMBERMAN_B_L);
		C_LUMBERMAN_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_LUMBERMAN_S_L);
		C_MAESTER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_MAESTER_B_L);
		C_MAESTER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_MAESTER_S_L);
		C_MINER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_MINER_B_L);
		C_MINER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_MINER_S_L);
		C_SHAMAN_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_SHAMAN_B_L);
		C_SHAMAN_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_SHAMAN_S_L);
		CROWNLANDS_ALCHEMIST_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, CROWNLANDS_ALCHEMIST_B_L);
		DAVOS_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, DAVOS_B_L);
		ESSOS_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, ESSOS_BLACKSMITH_B_L);
		SUD_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, SUD_MASON_B_L);
		IBBEN_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, IBBEN_BLACKSMITH_B_L);
		IBBEN_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, IBBEN_MASON_B_L);
		LHAZAR_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, LHAZAR_BLACKSMITH_B_L);
		MOSSOVY_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, MOSSOVY_BLACKSMITH_B_L);
		QOHOR_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, QOHOR_BLACKSMITH_B_L);
		SOTHORYOS_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, SOTHORYOS_BLACKSMITH_B_L);
		SUMMER_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, SUMMER_BLACKSMITH_B_L).setVessels(GOTFoods.ESSOS_DRINK);
		THENN_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, THENN_BLACKSMITH_B_L);
		WESTEROS_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, WESTEROS_BLACKSMITH_B_L);
		NORD_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, NORD_MASON_B_L);
		YITI_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, YITI_BLACKSMITH_B_L);
		YITI_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, YITI_MASON_B_L);
	}

	private final GOTTradeEntries.TradeType tradeType;
	private final GOTTradeEntry[] tradeEntries;

	private GOTItemMug.Vessel[] drinkVessels;

	@SuppressWarnings({"WeakerAccess", "unused"})
	public GOTTradeEntries(GOTTradeEntries.TradeType t, List<GOTTradeEntry> list) {
		GOTTradeEntry[] arr = new GOTTradeEntry[list.size()];
		arr = list.toArray(arr);
		tradeType = t;
		tradeEntries = arr;
	}

	public static GOTTradeSellResult getItemSellResult(ItemStack itemstack, GOTEntityNPC trader) {
		GOTTradeEntry[] sellTrades = trader.getTraderInfo().getSellTrades();
		if (sellTrades != null) {
			for (int index = 0; index < sellTrades.length; ++index) {
				GOTTradeEntry trade = sellTrades[index];
				if (trade != null && trade.matches(itemstack)) {
					return new GOTTradeSellResult(index, trade, itemstack);
				}
			}
		}
		return null;
	}

	public GOTTradeEntry[] getRandomTrades(Random random) {
		int numTrades = 3 + random.nextInt(3) + random.nextInt(3) + random.nextInt(3);
		if (numTrades > tradeEntries.length) {
			numTrades = tradeEntries.length;
		}
		GOTTradeEntry[] tempTrades = new GOTTradeEntry[tradeEntries.length];
		System.arraycopy(tradeEntries, 0, tempTrades, 0, tradeEntries.length);
		List<GOTTradeEntry> tempTradesAsList = Arrays.asList(tempTrades);
		Collections.shuffle(tempTradesAsList);
		tempTrades = tempTradesAsList.toArray(tempTrades);
		GOTTradeEntry[] trades = new GOTTradeEntry[numTrades];

		for (int i = 0; i < trades.length; ++i) {
			ItemStack tradeItem = tempTrades[i].createTradeItem();
			float tradeCost = tempTrades[i].getCost();
			int tradeCostI;
			if (tradeItem.getItem() instanceof GOTItemMug && ((GOTItemMug) tradeItem.getItem()).isBrewable() && tradeItem.getItemDamage() == 9999) {
				tradeCostI = 1 + random.nextInt(3);
				tradeItem.setItemDamage(tradeCostI);
				tradeCost *= GOTItemMug.getFoodStrength(tradeItem);
			}
			if (drinkVessels != null && GOTItemMug.isItemFullDrink(tradeItem)) {
				GOTItemMug.Vessel v = drinkVessels[random.nextInt(drinkVessels.length)];
				GOTItemMug.setVessel(tradeItem, v, true);
				tradeCost += v.getExtraPrice();
			}
			if (GOTConfig.enchantingGOT && tradeType == GOTTradeEntries.TradeType.WE_CAN_BUY) {
				boolean skilful = random.nextInt(3) == 0;
				GOTEnchantmentHelper.applyRandomEnchantments(tradeItem, random, skilful, false);
				tradeCost *= GOTEnchantmentHelper.calcTradeValueFactor(tradeItem);
			}
			tradeCost *= MathHelper.randomFloatClamp(random, 0.75F, 1.25F);
			tradeCost = Math.max(tradeCost, 1.0F);
			tradeCostI = Math.round(tradeCost);
			tradeCostI = Math.max(tradeCostI, 1);
			trades[i] = new GOTTradeEntry(tradeItem, tradeCostI);
		}
		return trades;
	}

	@SuppressWarnings({"WeakerAccess", "unused"})
	public GOTTradeEntries setVessels(GOTFoods foods) {
		return setVessels(foods.getDrinkVessels());
	}

	@SuppressWarnings({"WeakerAccess", "unused"})
	public GOTTradeEntries setVessels(GOTItemMug.Vessel... v) {
		if (tradeType != GOTTradeEntries.TradeType.WE_CAN_BUY) {
			throw new IllegalArgumentException("Cannot set the vessel types for a sell list");
		}
		drinkVessels = v;
		return this;
	}

	public GOTTradeEntry[] getTradeEntries() {
		return tradeEntries;
	}

	public enum TradeType {
		WE_CAN_BUY, WE_CAN_SELL
	}
}