package got.common.database;

import got.common.GOTConfig;
import got.common.enchant.GOTEnchantmentHelper;
import got.common.entity.other.GOTEntityNPC;
import got.common.entity.other.GOTTradeEntry;
import got.common.entity.other.GOTTradeEntryBarrel;
import got.common.entity.other.GOTTradeSellResult;
import got.common.item.other.GOTItemMug;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MathHelper;

import java.util.*;

public class GOTTradeEntries {
	public static List<GOTTradeEntry> BAELISH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_ALCHEMIST_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BAKER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BAKER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BARTENDER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BARTENDER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BLACKSMITH_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BOMZH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BOMZH_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BREWER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BREWER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BUTCHER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_BUTCHER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_FARMER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_FARMER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_FISHMONGER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_FISHMONGER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_FLORIST_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_GOLDSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_GOLDSMITH_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_MAESTER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_MAESTER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_MINER_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_MINER_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_SHAMAN_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_SHAMAN_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_LUMBERMAN_S_L = new ArrayList<>();
	public static List<GOTTradeEntry> C_LUMBERMAN_B_L = new ArrayList<>();

	public static List<GOTTradeEntry> IBBEN_MASON_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> YITI_MASON_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> SUD_MASON_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> NORD_MASON_B_L = new ArrayList<>();

	public static List<GOTTradeEntry> ESSOS_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> IBBEN_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> LHAZAR_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> MOSSOVY_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> QOHOR_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> SOTHORYOS_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> SUMMER_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> THENN_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> WESTEROS_BLACKSMITH_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> YITI_BLACKSMITH_B_L = new ArrayList<>();

	public static List<GOTTradeEntry> CROWNLANDS_ALCHEMIST_B_L = new ArrayList<>();
	public static List<GOTTradeEntry> DAVOS_B_L = new ArrayList<>();

	public static int VALYRIAN_INGOT_SELL = 512;
	public static int GOLD_INGOT_SELL = 128;
	public static int SILVER_INGOT_SELL = 32;
	public static int VALYRIAN_INGOT_BUY = 768;
	public static int GOLD_INGOT_BUY = 192;
	public static int SILVER_INGOT_BUY = 48;
	public static int AMBER_SELL = 30;
	public static int AMETHYST_SELL = 20;
	public static int DIAMOND_SELL = 60;
	public static int EMERALD_SELL = 40;
	public static int OPAL_SELL = 30;
	public static int PEARL_SELL = 30;
	public static int RUBY_SELL = 30;
	public static int SAPPHIRE_SELL = 30;
	public static int TOPAZ_SELL = 20;
	public static int AMBER_BUY = 45;
	public static int AMETHYST_BUY = 30;
	public static int DIAMOND_BUY = 90;
	public static int EMERALD_BUY = 60;
	public static int OPAL_BUY = 45;
	public static int PEARL_BUY = 45;
	public static int RUBY_BUY = 45;
	public static int SAPPHIRE_BUY = 45;
	public static int TOPAZ_BUY = 30;

	static {
		BAELISH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.baelishDagger), 5000));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bottlePoison), 10));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 1), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 10), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 12), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 13), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 2), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 3), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 4), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 5), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 6), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 8), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lingeringPotion, 1, 9), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 1), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 10), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 12), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 13), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 2), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 3), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 4), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 5), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 6), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 8), 128));
		C_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(Items.potionitem, 1, 9), 128));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.appleCrumbleItem), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.berryPieItem), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ceramicPlate), 2));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.cherryPieItem), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.cornBread), 5));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lemonCakeItem), 15));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.marzipan), 6));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.marzipanBlock), 20));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.marzipanChocolate), 10));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.oliveBread), 6));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.plate), 4));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(Items.bread), 5));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cake), 12));
		C_BAKER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cookie), 4));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.almond), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.appleGreen), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.cherry), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.clayPlate), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lemon), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.olive), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.salt), 10));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.apple), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 1, 3), 2));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.egg, 2), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.milk_bucket), 4));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.sugar, 2), 1));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_BAKER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 2), 1));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.aleHorn), 5));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.camelCooked), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ceramicMug), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ceramicPlate), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.deerCooked), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.gammon), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.gobletCopper), 3));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.gobletWood), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.kebab), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lemonCakeItem), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mug), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugAle, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugAppleJuice), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugAraq, 1, 9999), 10));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCactusLiqueur, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugChocolate), 4));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCider, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugLemonLiqueur, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugLimeLiqueur, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugMead, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugOrangeJuice), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPerry, 1, 9999), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugRedWine, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugWhiteWine, 1, 9999), 12));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.muttonCooked), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.oliveBread), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.orange), 3));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.plate), 4));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.plum), 3));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rabbitCooked), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rabbitStew), 10));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.shishKebab), 8));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.waterskin), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodPlate), 2));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.baked_potato, 2), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.bread), 5));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_beef), 7));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_chicken), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_fished), 6));
		C_BARTENDER_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_porkchop), 7));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.appleGreen), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.clayMug), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.clayPlate), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.date), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.deerRaw), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lemon), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lime), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.muttonRaw), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.orange), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pipeweed, 3), 10));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rabbitRaw), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.salt), 10));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.apple), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.beef), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.chicken), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.coal, 2, 32767), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.fish), 2));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.porkchop), 3));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.potato, 2), 1));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_BARTENDER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 2), 1));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.alloySteelIngot), 12));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_ingot), 9));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeIngot), 6));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.copperIngot), 3));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.diamond), 25));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pearl), 25));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapphire), 12));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.tinIngot), 3));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.coal, 2, 32767), 1));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.leather), 2));
		C_BLACKSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.string, 3), 1));
		C_BOMZH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.saltedFlesh), 7));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.chestnut, 2), 1));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fur), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.partyHat, 1, 32767), 100));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pipeweed, 3), 10));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.feather), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.flint), 1));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.leather), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.rotten_flesh), 2));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.stick, 8), 1));
		C_BOMZH_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat_seeds, 2), 1));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugAle, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugAppleJuice), 6));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugAraq, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugBananaBeer, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugBlackberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugBlueberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCactusLiqueur, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCarrotWine, 1, 9999), 12));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCherryLiqueur, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugChocolate), 6));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCider, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCranberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugElderberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugLemonLiqueur, 1, 9999), 12));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugLimeLiqueur, 1, 9999), 12));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugMangoJuice), 8));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugMead, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugMead, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugMelonLiqueur, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugOrangeJuice), 6));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPerry, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPlumKvass, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPomegranateJuice), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPomegranateWine, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugRaspberryJuice), 5));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugRedGrapeJuice), 8));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugRedWine, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugSourMilk, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugVodka, 1, 9999), 10));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugWhiteGrapeJuice), 8));
		C_BREWER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugWhiteWine, 1, 9999), 15));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugAle, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugAraq, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugCactusLiqueur, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugCarrotWine, 1, 2), 140));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugCherryLiqueur, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugCider, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugLemonLiqueur, 1, 2), 140));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugLimeLiqueur, 1, 2), 140));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugMead, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugPerry, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugPlumKvass, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugPomegranateWine, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugRedWine, 1, 2), 160));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugSourMilk, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugVodka, 1, 2), 120));
		C_BREWER_B_L.add(new GOTTradeEntryBarrel(new ItemStack(GOTRegistry.mugWhiteWine, 1, 2), 160));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.cactus), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 1), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 3), 9));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.appleGreen), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.banana), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.cherry), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.date), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.grapeRed), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.grapeWhite), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lemon), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lime), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mango), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.orange), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pear), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.plum), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pomegranate), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.apple), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.carrot), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 15), 9));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 5), 2));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.milk_bucket), 4));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.potato), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.sugar, 2), 1));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_BREWER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 2), 1));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.deerRaw), 4));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.gammon), 6));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.muttonRaw), 5));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rabbitRaw), 4));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.beef), 5));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.chicken), 4));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.leather), 3));
		C_BUTCHER_B_L.add(new GOTTradeEntry(new ItemStack(Items.porkchop), 5));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeDagger), 3));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironDagger), 3));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.salt), 10));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_ingot), 3));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(Items.lead), 4));
		C_BUTCHER_S_L.add(new GOTTradeEntry(new ItemStack(Items.wheat, 3), 1));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hay_block), 12));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block), 18));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 1), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.melon_block, 3), 10));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.wool), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.almond), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brandingIron), 16));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.corn), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.cornStalk), 1));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.driedReeds), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.grapeRed), 4));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.grapeWhite), 4));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leek), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lemon), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lettuce), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lime), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mango), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.orange), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pipeweedPlant), 10));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.plum), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pomegranate), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.reeds), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.turnip), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.carrot), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 1, 3), 8));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.lead), 8));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 15), 10));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.melon, 5), 3));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.milk_bucket), 8));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.potato), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.wheat), 2));
		C_FARMER_B_L.add(new GOTTradeEntry(new ItemStack(Items.wheat_seeds), 1));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeHoe), 6));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 6, 15), 1));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_hoe), 8));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.stone_hoe), 1));
		C_FARMER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sponge), 15));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pearl), 50));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.boat), 5));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 1, 0), 4));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 0), 4));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 1), 6));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 2), 8));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish, 1, 3), 12));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.fishing_rod), 8));
		C_FISHMONGER_B_L.add(new GOTTradeEntry(new ItemStack(Items.leather_boots), 5));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 0), 1));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeDagger), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironDagger), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.salt), 10));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_ingot), 3));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.stick, 8), 1));
		C_FISHMONGER_S_L.add(new GOTTradeEntry(new ItemStack(Items.string, 3), 1));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 0), 15));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 1), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 4), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.double_plant, 1, 5), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 0), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 1), 8));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 2), 6));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 3), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 4), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 5), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 6), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 7), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_flower, 1, 8), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.yellow_flower, 1, 8), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bluebell, 1, 0), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.doubleFlower, 1, 0), 25));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.doubleFlower, 1, 1), 10));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.doubleFlower, 1, 2), 45));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.doubleFlower, 1, 3), 45));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosFlower, 1, 0), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosFlower, 1, 1), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosFlower, 1, 2), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosFlower, 1, 3), 30));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.marigold, 1, 0), 3));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiFlower, 1, 0), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiFlower, 1, 1), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiFlower, 1, 2), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiFlower, 1, 3), 20));
		C_FLORIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiFlower, 1, 4), 20));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.birdCage, 1, 2), SILVER_INGOT_BUY * 6));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.birdCage, 1, 3), GOLD_INGOT_BUY * 6));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.chandelier, 1, 2), SILVER_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.chandelier, 1, 3), GOLD_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.gobletGold), GOLD_INGOT_BUY * 2));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.gobletSilver), SILVER_INGOT_BUY * 2));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.goldBars), GOLD_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.goldRing), GOLD_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.silverBars), SILVER_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.silverRing), SILVER_INGOT_BUY));
		C_GOLDSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianRing), VALYRIAN_INGOT_BUY));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.amber), AMBER_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.amethyst), AMETHYST_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.diamond), DIAMOND_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.emerald), EMERALD_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.opal), OPAL_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pearl), PEARL_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ruby), RUBY_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapphire), SAPPHIRE_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.silverIngot), SILVER_INGOT_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.topaz), TOPAZ_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianIngot), VALYRIAN_INGOT_SELL));
		C_GOLDSMITH_S_L.add(new GOTTradeEntry(new ItemStack(Items.gold_ingot), GOLD_INGOT_SELL));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.leaves2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 4), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 2), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 4), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitLeaves, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitLeaves, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitLeaves, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitSapling, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitSapling, 1, 1), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitSapling, 1, 2), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitWood, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitWood, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.fruitWood, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves2, 1, 1), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves2, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves2, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves3, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves3, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves3, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves3, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves4, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves4, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves4, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves4, 1, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 1), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 2), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves5, 1, 3), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves6, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves6, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves6, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves6, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves6, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves6, 1, 3), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves7, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves7, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves8, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves8, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves8, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leaves8, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 10), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 12), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 13), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 14), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 14), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 4), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 5), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 6), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 8), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 9), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks1, 4, 9), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 10), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 10), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 11), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 11), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 12), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 15), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 4), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 4), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 5), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 5), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 6), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 6), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 7), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 7), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 8), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks2, 4, 9), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks3, 4, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks3, 4, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks3, 4, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.planks3, 4, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling2, 1, 0), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling2, 1, 1), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling2, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling2, 1, 2), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling3, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling3, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling3, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling3, 1, 2), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling4, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling4, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling4, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling4, 1, 3), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 0), 16));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 1), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 1), 14));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 2), 14));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling5, 1, 3), 14));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling6, 1, 0), 20));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling6, 1, 1), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling6, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling6, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling6, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling6, 1, 3), 12));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling7, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling7, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling8, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling8, 1, 1), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling8, 1, 2), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling8, 1, 3), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood2, 1, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood2, 1, 1), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood2, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood2, 1, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood3, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood3, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood3, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood3, 1, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood4, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood4, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood4, 1, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood4, 1, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 1), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 2), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood5, 1, 3), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood6, 1, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood6, 1, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood6, 1, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood6, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood6, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood6, 1, 3), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood7, 1, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood7, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood8, 1, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood8, 1, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood8, 1, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wood8, 1, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam2, 3, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam2, 3, 1), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam2, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam2, 3, 2), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam3, 3, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam3, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam3, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam3, 3, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam4, 3, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam4, 3, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam4, 3, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam4, 3, 3), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 0), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 0), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 1), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 2), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam5, 3, 3), 7));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam6, 3, 0), 10));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam6, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam6, 3, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam6, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam6, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam6, 3, 3), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam7, 3, 0), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam7, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam8, 3, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam8, 3, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam8, 3, 2), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeam8, 3, 3), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamFruit, 3, 0), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamFruit, 3, 1), 5));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamFruit, 3, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV1, 3, 0), 2));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV1, 3, 1), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV1, 3, 2), 3));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV1, 3, 2), 4));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV1, 3, 2), 8));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV2, 3, 0), 6));
		C_LUMBERMAN_B_L.add(new GOTTradeEntry(new ItemStack(Items.stick, 4), 1));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeAxe), 6));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.dye, 6, 15), 1));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_axe), 8));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.shears), 5));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.stone_axe), 1));
		C_LUMBERMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bottlePoison), 10));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPlantainBrew), 12));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPoppyMilk), 12));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sulfurMatch), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.book, 1), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.flint_and_steel), 4));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.paper, 2), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.saddle), 2));
		C_MAESTER_B_L.add(new GOTTradeEntry(new ItemStack(Items.writable_book, 1), 4));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bottlePoison), 5));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPlantainBrew), 6));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPoppyMilk), 6));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sulfurMatch), 1));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.book, 1), 2));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.flint_and_steel), 2));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.paper, 2), 1));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.saddle), 1));
		C_MAESTER_S_L.add(new GOTTradeEntry(new ItemStack(Items.writable_book, 1), 4));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.amber), AMBER_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.amethyst), AMETHYST_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.diamond), DIAMOND_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.emerald), EMERALD_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.opal), OPAL_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pearl), PEARL_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ruby), RUBY_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapphire), SAPPHIRE_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.silverIngot), SILVER_INGOT_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.topaz), TOPAZ_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianIngot), VALYRIAN_INGOT_BUY));
		C_MINER_B_L.add(new GOTTradeEntry(new ItemStack(Items.gold_ingot), GOLD_INGOT_BUY));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.torch, 16), 2));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzePickaxe), 6));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.deerCooked), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.muttonCooked), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rabbitCooked), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bread), 2));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.bucket), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.coal, 2, 32767), 1));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_beef), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_chicken), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_porkchop), 3));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.iron_pickaxe), 8));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.stone_pickaxe), 1));
		C_MINER_S_L.add(new GOTTradeEntry(new ItemStack(Items.water_bucket), 4));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sapling, 1, 3), 6));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bottlePoison), 10));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.dartPoisoned, 4), 10));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugChocolate), 4));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugCocoa, 1, 9999), 12));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mugPoppyMilk), 20));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sapling6, 1, 0), 8));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sarbacane), 25));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sarbacaneTrap, 4), 5));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosDagger), 12));
		C_SHAMAN_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosDaggerPoisoned), 20));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.brown_mushroom, 1, 0), 2));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Blocks.red_mushroom, 1, 0), 2));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.banana), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.corn, 2), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.doubleFlower, 2, 2), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.doubleFlower, 2, 3), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.gemsbokHorn), 4));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mango), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.mug), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.obsidianShard), 3));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rhinoHorn), 5));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.bone), 1));
		C_SHAMAN_S_L.add(new GOTTradeEntry(new ItemStack(Items.glass_bottle), 2));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bomb), 64));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bottlePoison), 10));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.firePot), 32));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sulfurMatch), 1));
		CROWNLANDS_ALCHEMIST_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wildFireJar), 128));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leek), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leekCrop), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.leekSoup), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.salt), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.saltedFlesh), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(Items.cooked_fished), 5));
		DAVOS_B_L.add(new GOTTradeEntry(new ItemStack(Items.fish), 5));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeCrossbow), 12));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosDagger), 9));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosDaggerPoisoned), 15));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosHammer), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosHorseArmor), 25));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosPike), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosPolearm), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosSpear), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.essosSword), 15));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironCrossbow), 15));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		ESSOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.redSandstone, 8), 12));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.whiteSandstone, 8), 6));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sandstone, 8), 2));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick1, 8, 15), 3));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick3, 1, 15), 4));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick3, 1, 8), 2));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick3, 8, 13), 6));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pillar1, 4, 15), 6));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pillar1, 4, 5), 3));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.redSandstone, 8), 4));
		SUD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.whiteSandstone, 8), 6));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ibbenBoots), 16));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ibbenChestplate), 28));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ibbenHarpoon), 18));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ibbenLeggings), 24));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ibbenSword), 15));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironCrossbow), 15));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailHelmet), 9));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailChestplate), 13));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailLeggings), 11));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailBoots), 7));
		IBBEN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.saddle), 15));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.cobblestone, 8), 1));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.dirt, 8), 1));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.log, 1, 1), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.planks, 4, 1), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stone, 8), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stonebrick, 8, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick1, 8, 4), 3));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick5, 1, 3), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rock, 8, 2), 3));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.thatch, 4, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.thatch, 4, 1), 4));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.thatchFloor, 16, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamS, 3, 0), 4));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamS, 3, 1), 8));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV1, 3, 0), 2));
		IBBEN_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.woodBeamV1, 3, 1), 2));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeCrossbow), 12));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarBoots), 17));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarChestplate), 32));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarClub), 15));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarDagger), 8));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarDaggerPoisoned), 14));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarHelmet), 20));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarLeggings), 26));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarSpear), 15));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.lhazarSword), 15));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.tableLhazar), 100));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailHelmet), 9));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailChestplate), 13));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailLeggings), 11));
		LHAZAR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailBoots), 7));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironCrossbow), 15));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironDagger), 9));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironHorseArmor), 25));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironSpear), 16));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.iron_sword), 15));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		MOSSOVY_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianBook), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianDagger), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianDaggerPoisoned), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianHammer), VALYRIAN_INGOT_BUY * 4));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianSpear), VALYRIAN_INGOT_BUY));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianSword), VALYRIAN_INGOT_BUY * 3));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianHelmet), VALYRIAN_INGOT_BUY * 5));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianChestplate), VALYRIAN_INGOT_BUY * 8));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianLeggings), VALYRIAN_INGOT_BUY * 7));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianBoots), VALYRIAN_INGOT_BUY * 4));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianChainmailHelmet), VALYRIAN_INGOT_BUY * 4));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianChainmailChestplate), VALYRIAN_INGOT_BUY * 6));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianChainmailLeggings), VALYRIAN_INGOT_BUY * 6));
		QOHOR_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.valyrianChainmailBoots), VALYRIAN_INGOT_BUY * 3));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosBattleaxe), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosBoots), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosChestplate), 32));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosDagger), 12));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosHammer), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosHelmet), 20));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosHelmetChieftain), 40));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosLeggings), 25));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosPike), 18));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosSpear), 15));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.sothoryosSword), 16));
		SOTHORYOS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.tableSothoryos), 100));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeCrossbow), 12));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerBoots), 17));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerChestplate), 32));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerDagger), 8));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerDaggerPoisoned), 14));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerHelmet), 20));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerLeggings), 26));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerPike), 15));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerSpear), 15));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.summerSword), 14));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.tableSummer), 100));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailHelmet), 9));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailChestplate), 13));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailLeggings), 11));
		SUMMER_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailBoots), 7));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironCrossbow), 15));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wildlingDagger), 9));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wildlingSpear), 16));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.wildlingSword), 15));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailHelmet), 9));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailChestplate), 13));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailLeggings), 11));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeChainmailBoots), 7));
		THENN_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.bow), 12));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironCrossbow), 15));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.westerosDagger), 9));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.westerosHammer), 18));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.westerosHorseArmor), 25));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.westerosSpear), 16));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.westerosSword), 15));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_helmet), 12));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_chestplate), 16));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_leggings), 14));
		WESTEROS_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Items.chainmail_boots), 10));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.cobblestone, 8), 1));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stone, 8), 2));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stonebrick, 1, 8), 2));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick1, 1, 5), 2));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick1, 8, 1), 3));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick2, 8, 11), 12));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick4, 1, 6), 12));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick5, 8, 8), 3));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pillar1, 4, 6), 3));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rock, 8, 0), 16));
		NORD_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rock, 8, 1), 3));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.blacksmithHammer), 18));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bomb), 64));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeBars, 8), 20));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.bronzeCrossbow), 12));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.crossbowBolt, 4), 3));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.ironCrossbow), 15));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.tableYiTi), 100));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiBattleaxe), 18));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiBoots), 17));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiBootsFrontier), 19));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiBootsSamurai), 21));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiChestplate), 32));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiChestplateFrontier), 35));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiChestplateSamurai), 37));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiDagger), 9));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiHelmet), 20));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiHelmetFrontier), 22));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiHelmetSamurai), 24));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiHorseArmor), 37));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiLeggings), 26));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiLeggingsFrontier), 28));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiLeggingsSamurai), 30));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiPike), 16));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiPolearm), 16));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiSpear), 16));
		YITI_BLACKSMITH_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.yitiSword), 15));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.cobblestone, 8), 1));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.sandstone, 8), 4));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stone, 8), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(Blocks.stonebrick, 1, 8), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick5, 1, 12), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick5, 1, 15), 2));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick5, 8, 11), 3));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick6, 1, 2), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.brick6, 8, 1), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pillar2, 4, 8), 3));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.pillar2, 4, 9), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.redSandstone, 8), 12));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.rock, 8, 4), 8));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.tableYiTi), 100));
		YITI_MASON_B_L.add(new GOTTradeEntry(new ItemStack(GOTRegistry.whiteSandstone, 8), 6));
	}

	public static GOTTradeEntries BAELISH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, BAELISH_B_L);
	public static GOTTradeEntries C_ALCHEMIST_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_ALCHEMIST_B_L);
	public static GOTTradeEntries C_BAKER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BAKER_B_L);
	public static GOTTradeEntries C_BAKER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BAKER_S_L);
	public static GOTTradeEntries C_BARTENDER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BARTENDER_B_L);
	public static GOTTradeEntries C_BARTENDER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BARTENDER_S_L);
	public static GOTTradeEntries C_BLACKSMITH_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BLACKSMITH_S_L);
	public static GOTTradeEntries C_BOMZH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BOMZH_B_L);
	public static GOTTradeEntries C_BOMZH_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BOMZH_S_L);
	public static GOTTradeEntries C_BREWER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BREWER_B_L);
	public static GOTTradeEntries C_BREWER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BREWER_S_L);
	public static GOTTradeEntries C_BUTCHER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_BUTCHER_B_L);
	public static GOTTradeEntries C_BUTCHER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_BUTCHER_S_L);
	public static GOTTradeEntries C_FARMER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_FARMER_B_L);
	public static GOTTradeEntries C_FARMER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_FARMER_S_L);
	public static GOTTradeEntries C_FISHMONGER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_FISHMONGER_B_L);
	public static GOTTradeEntries C_FISHMONGER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_FISHMONGER_S_L);
	public static GOTTradeEntries C_FLORIST_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_FLORIST_B_L);
	public static GOTTradeEntries C_GOLDSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_GOLDSMITH_B_L);
	public static GOTTradeEntries C_GOLDSMITH_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_GOLDSMITH_S_L);
	public static GOTTradeEntries C_LUMBERMAN_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_LUMBERMAN_B_L);
	public static GOTTradeEntries C_LUMBERMAN_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_LUMBERMAN_S_L);
	public static GOTTradeEntries C_MAESTER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_MAESTER_B_L);
	public static GOTTradeEntries C_MAESTER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_MAESTER_S_L);
	public static GOTTradeEntries C_MINER_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_MINER_B_L);
	public static GOTTradeEntries C_MINER_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_MINER_S_L);
	public static GOTTradeEntries C_SHAMAN_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, C_SHAMAN_B_L);
	public static GOTTradeEntries C_SHAMAN_SELL = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_SELL, C_SHAMAN_S_L);
	public static GOTTradeEntries CROWNLANDS_ALCHEMIST_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, CROWNLANDS_ALCHEMIST_B_L);
	public static GOTTradeEntries DAVOS_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, DAVOS_B_L);
	public static GOTTradeEntries ESSOS_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, ESSOS_BLACKSMITH_B_L);
	public static GOTTradeEntries SUD_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, SUD_MASON_B_L);
	public static GOTTradeEntries IBBEN_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, IBBEN_BLACKSMITH_B_L);
	public static GOTTradeEntries IBBEN_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, IBBEN_MASON_B_L);
	public static GOTTradeEntries LHAZAR_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, LHAZAR_BLACKSMITH_B_L);
	public static GOTTradeEntries MOSSOVY_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, MOSSOVY_BLACKSMITH_B_L);
	public static GOTTradeEntries QOHOR_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, QOHOR_BLACKSMITH_B_L);
	public static GOTTradeEntries SOTHORYOS_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, SOTHORYOS_BLACKSMITH_B_L);
	public static GOTTradeEntries SUMMER_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, SUMMER_BLACKSMITH_B_L).setVessels(GOTFoods.ESSOS_DRINK);
	public static GOTTradeEntries THENN_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, THENN_BLACKSMITH_B_L);
	public static GOTTradeEntries WESTEROS_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, WESTEROS_BLACKSMITH_B_L);
	public static GOTTradeEntries NORD_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, NORD_MASON_B_L);
	public static GOTTradeEntries YITI_BLACKSMITH_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, YITI_BLACKSMITH_B_L);
	public static GOTTradeEntries YITI_MASON_BUY = new GOTTradeEntries(GOTTradeEntries.TradeType.WE_CAN_BUY, YITI_MASON_B_L);

	public GOTTradeEntries.TradeType tradeType;
	public GOTTradeEntry[] tradeEntries;

	public GOTItemMug.Vessel[] drinkVessels;

	public GOTTradeEntries(GOTTradeEntries.TradeType t, List<GOTTradeEntry> list) {
		GOTTradeEntry[] arr = new GOTTradeEntry[list.size()];
		arr = list.toArray(arr);
		tradeType = t;
		tradeEntries = arr;
	}

	public GOTTradeEntry[] getRandomTrades(Random random) {
		int numTrades = 3 + random.nextInt(3) + random.nextInt(3) + random.nextInt(3);
		if (numTrades > tradeEntries.length) {
			numTrades = tradeEntries.length;
		}

		GOTTradeEntry[] tempTrades = new GOTTradeEntry[tradeEntries.length];
		System.arraycopy(tradeEntries, 0, tempTrades, 0, tradeEntries.length);
		List<GOTTradeEntry> tempTradesAsList = Arrays.asList(tempTrades);
		Collections.shuffle(tempTradesAsList);
		tempTrades = tempTradesAsList.toArray(tempTrades);
		GOTTradeEntry[] trades = new GOTTradeEntry[numTrades];

		for (int i = 0; i < trades.length; ++i) {
			ItemStack tradeItem = tempTrades[i].createTradeItem();
			float tradeCost = tempTrades[i].getCost();
			int tradeCostI;
			if (tradeItem.getItem() instanceof GOTItemMug && ((GOTItemMug) tradeItem.getItem()).isBrewable && tradeItem.getItemDamage() == 9999) {
				tradeCostI = 1 + random.nextInt(3);
				tradeItem.setItemDamage(tradeCostI);
				tradeCost *= GOTItemMug.getFoodStrength(tradeItem);
			}

			if (drinkVessels != null && GOTItemMug.isItemFullDrink(tradeItem)) {
				GOTItemMug.Vessel v = drinkVessels[random.nextInt(drinkVessels.length)];
				GOTItemMug.setVessel(tradeItem, v, true);
				tradeCost += v.extraPrice;
			}

			if (GOTConfig.enchantingGOT && tradeType == GOTTradeEntries.TradeType.WE_CAN_BUY) {
				boolean skilful = random.nextInt(3) == 0;
				GOTEnchantmentHelper.applyRandomEnchantments(tradeItem, random, skilful, false);
				tradeCost *= GOTEnchantmentHelper.calcTradeValueFactor(tradeItem);
			}

			tradeCost *= MathHelper.randomFloatClamp(random, 0.75F, 1.25F);
			tradeCost = Math.max(tradeCost, 1.0F);
			tradeCostI = Math.round(tradeCost);
			tradeCostI = Math.max(tradeCostI, 1);
			trades[i] = new GOTTradeEntry(tradeItem, tradeCostI);
		}

		return trades;
	}

	public GOTTradeEntries setVessels(GOTFoods foods) {
		return this.setVessels(foods.getDrinkVessels());
	}

	public GOTTradeEntries setVessels(GOTItemMug.Vessel... v) {
		if (tradeType != GOTTradeEntries.TradeType.WE_CAN_BUY) {
			throw new IllegalArgumentException("Cannot set the vessel types for a sell list");
		}
		drinkVessels = v;
		return this;
	}

	public static GOTTradeSellResult getItemSellResult(ItemStack itemstack, GOTEntityNPC trader) {
		GOTTradeEntry[] sellTrades = trader.traderNPCInfo.getSellTrades();
		if (sellTrades != null) {
			for (int index = 0; index < sellTrades.length; ++index) {
				GOTTradeEntry trade = sellTrades[index];
				if (trade != null && trade.matches(itemstack)) {
					return new GOTTradeSellResult(index, trade, itemstack);
				}
			}
		}

		return null;
	}

	public enum TradeType {
		WE_CAN_BUY, WE_CAN_SELL;
	}
}
